### ISSUE TITLE
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer#1005]
Hi i need to know how to fix this warning . I have write some test cases using Jest framework . I have a mock function displayed below. Inside of mock function if i  coded Promise.resolve()  This warning automatically fixed . But when i used 
Promise.reject(e) OR   throw e This warning appear .  What is the reason for this matter

  InvoiceRowSchema.actions.insert = jest.fn((params) => {
    const e = new Error() // e.name is 'Error'
    e.name = 'SequelizeDatabaseError'
    throw e
    // return Promise.reject(e)
  })

**Comment by icebob** [comment]
You should always call the `broker.stop`, like
```js
beforeAll(() => broker.start());
aftereAll(() => broker.stop());
```
