### ISSUE TITLE
Customer Logger usage

### ISSUE THREAD

**Issue by hoghweed** [moleculerjs/moleculer#1006]
Hi,

while I was looking to setup and use a custom logger with the ServiceBoker, I realized that the sample provided within the [documentation](https://moleculer.services/docs/0.14/logging.html#Custom-logger) is not usable.

Even after having an overview within the codebase, it seems that the LoggerFactory when tries to use the provided logger always raises an error because the **type**  of the logger is always **null**.

I didn't find any sample or info about using the custom logger along with any type information, can you please update the documentation to reflect the real usage requirements for custom loggers?

Many thanks

**Comment by ccampanale** [comment]
In my experience you will see this error if the custom class is not properly extending the base class OR if you somehow have multiple instances of the moleculer framework available and the one starting/running your broker is not the one you are referencing when extending the base. ([this is the check for loggers](https://github.com/moleculerjs/moleculer/blob/master/src/loggers/index.js#L45-L47))

I ran into this same issue in a custom system where our microservice chassis has moleculer installed and uses it to start a broker to run services built on top of the container. One of the packages built on the chassis was using a custom metrics report that was extending the base from an instance of moleculer included as a dependency for that package but not the one built into the chassis image and therefore ran into the same error.

Hopefully this helps you dig into the issue.

**Comment by ccampanale** [comment]
@hoghweed Did the above help?
