### ISSUE TITLE
persist a single payload which is targeted for multiple services

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer#1007]
Whats the recommended way to **persist a single payload which is targeted for multiple services**?
I have two molecular services which are named Invoice and InvoiceRow.
Only one request comes in with a combined payload which holds both invoice and invoice row data.
Currently I'm separating data inside the invoice service action and just make a static action call to invoice row to persist row data. Then same for the invoice main data.
I just want to check with the community on my current practice. In a architecture like one database per service, Whats the recommended way to persist a single payload which is targeted for multiple services?
Sample payload.
```

{
   "customer":1,
   "credit_invoice_id":null,
   "payment_status":1,
   "taxType":null,
   "discountRate": null,
   "invoiceRows": [
            {
           "quantity":213,
           "amount":"3.79",
           "currency": 1,
           "description": ""
       }
     ]
}
```

**Comment by ccampanale** [comment]
This is a rather confusing question and I personally do not think it is an issue for the framework but instead conceptual and theoretical about how to apply the framework to write solutions for various problem domains, a  question likely better suited for the "Discussions" section or in Discord.

The best way I can think to response would be to suggest reading the [Moleculer Documentation for Database Adapters and examples](https://moleculer.services/docs/0.14/moleculer-db.html). Regardless of how you are design the services in your system/application this documentation should be able to shed some light on how one might implement persistence to various database systems.

**Comment by ccampanale** [comment]
@icebob This has been moved to #1009 and can probably be closed...
