### ISSUE TITLE
 single JSON payload in Molecular API documenting

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer#1008]
I'm having hard time documenting API endpoints with the given Molecular API documenting method. I'm just editing raw in public.html page. There's no way to **put a single JSON payload**. Only text and other inputs are there.
Also I'm completely lost on handling **Authorization where I need to send bearer tokens in header**. With the given Molecular API documenting package can I achieve what I'm looking for?

**Comment by icebob** [comment]
The generated public.html is just an example, not a developer tool. You should manage it, or using other stuffs, like Swagger UI
