### ISSUE TITLE
How to implemet  swagger in Molecular 

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer#1010]
I need to implement  **swagger** in molecular service any sample for this . Or any recommended method to implement developer tool

**Comment by AndreMaz** [comment]
Hey @sachinda123456 

Check this repo: https://github.com/grinat/moleculer-auto-openapi

For questions please use [Discord chat](https://discord.gg/TSEcDRP). Github issues are only for bug reports or feature requests
