### ISSUE TITLE
Add support to define services in ESM modules, or using ESM-only dependencies

### ISSUE THREAD

**Issue by piranna** [moleculerjs/moleculer#1014]
At https://github.com/moleculerjs/moleculer/issues/328 there was previous work to add support for ESM modules, but as shown in https://github.com/moleculerjs/moleculer/issues/328#issuecomment-924311630, it's not working. Since `moleculer` is using `require()` everywhere, once that a service use an ESM-only dependency or the service itself is in a ESM module file, running `moleculer-runner` crash on boot. (`moleculer-runner` is the first one [using `require()`](https://github.com/moleculerjs/moleculer/blob/2ae6fa7ccd21682f8046d6b69954712ebc46fc41/bin/moleculer-runner.js#L10) itself...)

To fix that we have two alternatives:

1. The first (and ideal) one is to update `moleculer` source code to use ESM modules itself instead of CommonJS. All maintained versions of Node.js already has unflagged support for ESM modules, so there would not be any compatibility issues, but would be a bit of work and probably it would be set for another major version (the `v0.16`, in this case).

2. The quick solution would be to make use of the [esm](https://www.npmjs.com/package/esm) package, that provides a replacement of the `require()` function that has support for ESM modules, and use it at https://github.com/moleculerjs/moleculer/blob/2ae6fa7ccd21682f8046d6b69954712ebc46fc41/src/service-broker.js#L773 instead of the Node.js builtin one, so ESM services or their ESM dependencies can be loaded without needing to do any other change in the current code base of `moleculer`. If you are interested, we can provide a PR with this change, meanwhile you work towards the first option.

**Comment by icebob** [comment]
I know that nowadays many OS maintainers have been starting to change all their packages from CJS to ESM and generate a lot of extra works for other dependent library maintainers. But I don't plan to start it with Moleculer packages and make issues for developers who use Moleculer in their projects. So option #1 is not an alternative (at least for now, maybe in later major version).

Option #2: I've checked the `esm` package but it looks it's not maintained, last version is published in 2019 however there are reported unresolved issues.

**Comment by piranna** [comment]
Why got this clossed?

**Comment by icebob** [comment]
Because PR created

**Comment by piranna** [comment]
Ok, didn't see it before, thanks :-D
