### ISSUE TITLE
Fetch data from multiple collection(mongodb) in single service

### ISSUE THREAD

**Issue by abinasp** [moleculerjs/moleculer#1018]
How can i use multiple collection in single service. My code looks like below
```js
const DbService = require("moleculer-db");
require("dotenv").config();
const mongoURI = process.env.MONGO;
const MongoAdapter = require("moleculer-db-adapter-mongo");
module.exports={
	name: "dashboard",
	mixins: [DbService],
	adapter: new MongoAdapter(mongoURI,{
		useNewUrlParser: true, 
		reconnectTries: Number.MAX_VALUE,
		reconnectInterval: 500,
		keepAlive: true,
		autoReconnect: true
	}),
	collection: "users",
	actions:{
		counts:{
			async handler(ctx){
				try{
					const totalUsers = await this.adapter.count({query:{type:"api"}});
				}catch(error){
					console.log(error);
				}
			}
		}
	}
}
```

I want to fetch total `posts` and total `texts` from 2 different collection.
how can i pass multiple collection name in `collection` and can access in `adapter`.
Is there any solution for this scenario, could not find any relevant posts like this.

**Comment by AndreMaz** [comment]
> How can i use multiple collection in single service

moleculer-db follows [one-database-per-service pattern](https://microservices.io/patterns/data/database-per-service.html). This means that you need 2 services `posts` and `texts` and call them to fetch the desired data. For more info please check [FAQ](https://moleculer.services/docs/0.14/faq.html#DB-Adapters-moleculer-db)

For questions please use [Discord chat](https://discord.gg/TSEcDRP). Github issues are only for bug reports or feature requests
