### ISSUE TITLE
allow action.cache.keys function access ctx

### ISSUE THREAD

**Issue by 0x0a0d** [moleculerjs/moleculer#1024]
It's easy to allow action's keygen function access `ctx`, just need to add `ctx` as 6th param at https://github.com/0x0a0d/moleculer/blob/master/src/cachers/base.js#L351

In my case, I need to access `ctx.caller`
How do you think?

**Comment by icebob** [comment]
OK. 
_In the next major release, we should refactor it and pass only `ctx`, and `opts` only instead of many parameters._
