### ISSUE TITLE
AMQP Communication - No response from the event you are listening

### ISSUE THREAD

**Issue by xfreak16** [moleculerjs/moleculer#1027]
Hello everyone,

I have a question related to transport, I have a feeling when I am broadcasting an event that I am doing something wrong. I use two separate microservices and I want them to communicate using AMQP, when the gateway broadcasts the "mailer.newUser" event, then the "mailer" microservice does not send data or says in the console: ServiceNotFoundError: Service 'api.test' is not found on 'GATEWAY' node. I just have the impression that all events go local, not the transporter, even though localPrefer is false

On the other hand, the heartbeat is active in the RabbitMQ panel, and the rest of the rest of the queue is idle all the time. I have no idea what to do anymore, because I have been working on it for more than a day.

![obraz](https://user-images.githubusercontent.com/9503221/140918248-eae32d19-73fc-42a0-baa8-32329765ebef.png)

OVERVIEW RABBIT

![obraz](https://user-images.githubusercontent.com/9503221/140918693-7c104da8-3ef5-4d93-a442-be160fa3b210.png)

Do you have ideas? Thanks in advance

**Comment by intech** [comment]
Let's first make sure that brokers can see each other through transport.
To do this, you need to connect, for example, via [`moleculer-repl`](https://moleculer.services/docs/0.14/moleculer-repl.html) and print the command `actions -d`
