### ISSUE TITLE
Custom Load Balancing Strategy Does Not Take Effect

### ISSUE THREAD

**Issue by 0x39** [moleculerjs/moleculer#1036]
## Current Behavior

Custom balancing strategy defined in action does not override global broker balancing strategy

## Expected Behavior

You can overwrite globally defined load balancing strategy in action/event definitions.

## Failure Information

Custom balancing strategy defined in action take place only if also defined in global broker options, while other actions still continue to use default RoundRobin.

### Case 1

```js
import CustomStrategy from './strategies/Custom';

const broker = new ServiceBroker({
    registry: {
		strategy: CustomStrategy,
	},
});

broker.createService({
    name: "test",
    actions: {
        first(ctx) {
            return "Expected to use: CustomStrategy, but RoundRobin takes place"
        },
        second(ctx) {
            strategy: CustomStrategy,
            handler: () =>  "Expected to use: CustomStrategy, it works!"
        },
    }
});
```

### Case 2

```js
import CustomStrategy from './strategies/Custom';

const broker = new ServiceBroker({
    registry: {
		strategy: 'RoundRobin',
	},
});

broker.createService({
    name: "test",
    actions: {
        first(ctx) {
            return "Expected to use: RoundRobin, it works!"
        },
        second(ctx) {
            strategy: CustomStrategy,
            handler: () =>  "Expected to use: CustomStrategy, still RoundRobin in use.."
        },
    }
});
```

### Context

* Moleculer version: 0.14.18
* NodeJS version: Docker FROM node:16.8
* Operating System: Ubuntu 20.04
* Typescript template used
* Multi container environment
* All container src mounted inside volume from single location && built inside container using "ts-node ./node_modules/moleculer/bin/moleculer-runner.js --env --hot --config moleculer.config.ts"

**Comment by icebob** [comment]
The problem is that you use a class reference in the action `strategy` property which is not serializable. So the caller node doesn't see this property and will use the default "RoundRobin". To avoid it, call the `Strategies.register` and register your custom class with a name and use the name in the action schema instead of the class reference.

E.g.:
```js
import CustomStrategy from './strategies/Custom';

import { Strategies } from "moleculer;
Strategies.register("myStrategy", CustomStrategy);

const broker = new ServiceBroker({
    registry: {
		strategy: 'RoundRobin',
	},
});

broker.createService({
    name: "test",
    actions: {
        first(ctx) {
            return "Expected to use: RoundRobin, it works!"
        },
        second(ctx) {
            strategy: "myStrategy",
            handler: () =>  "Expected to use: CustomStrategy, still RoundRobin in use.."
        },
    }
});
```

Please note that the strategy is running on the caller side, so you should do this registration on all nodes which will call this action.

**Comment by AndreMaz** [comment]
Here's a working example https://github.com/moleculerjs/moleculer/blob/issue1036/dev/issue1036.js

**Comment by 0x39** [comment]
Awesome, Thank You Guys!

Will be good to mention that in docs.

**Comment by AndreMaz** [comment]
I've updated the docs. Thank you for reporting 😉

**Comment by icebob** [comment]
Thanks André!

**Comment by mehmetkir84** [comment]
Hi;
I want to assign action custom load balance strategy. Why is it not working?

this.parseServiceSchema({
        name: "Client",
        actions: {
          register: {
            strategy: "RoundRobin",
            preferLocal: true,
            handler: this.register,
          },
        }
      });
