### ISSUE TITLE
SQS Transporter

### ISSUE THREAD

**Issue by devalexandre** [moleculerjs/moleculer#1037]
I believe it has some form, but due to lack of documentation it is quite complicated to guess, I tried the following way, but I was not successful.

https://gist.github.com/devalexandre/1bd272e6929f5db34b24f8b173355b9b

**Comment by AndreMaz** [comment]
What exactly is the issue? What's the error?
The [docs explain](https://moleculer.services/docs/0.14/networking.html#Custom-transporter) how to create and add custom transporter

**Comment by devalexandre** [comment]
so I read this part a lot, I think I should have an example, even if it was simple, because my error was the lack of passing ``` this.onConnected().then(resolve); ``` after the connection is made.

but I took a look at the service-broker source and the existing transports and I got it.

thanks :)
