### ISSUE TITLE
Error with command: npm i moleculer

### ISSUE THREAD

**Issue by mohamedmehdigara** [moleculerjs/moleculer#1038]
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "moleculer" under a 
package
npm ERR! also called "moleculer". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2021-12-03T09_31_37_471Z-debug.log

**Comment by icebob** [comment]
Don't use the "moleculer" name as your project in your package.json. It conflicts with the package name.

**Comment by mohamedmehdigara** [comment]
Yes. Thanks. Same answer like in Stackoverflow.
