### ISSUE TITLE
[FR] Export error types

### ISSUE THREAD

**Issue by DenisFerrero** [moleculerjs/moleculer#1053]
## Is your feature request related to a problem? Please describe.
It's not a problem

## Describe the solution you'd like
I'm building a set of custom errors but I want to use some of the already declared error types in Moleculer. As I saw in the library they are declared just as strings in the error declaration. Is it possible to export them from the error modules (like happens for the API gateway)?
```js
const {
	ERR_NO_TOKEN,
	ERR_INVALID_TOKEN,
	ERR_UNABLE_DECODE_PARAM,
	ERR_ORIGIN_NOT_FOUND,
	ERR_ORIGIN_NOT_ALLOWED
} = require('moleculer-web');
```

## Additional context
At the moment I declare them manually like this
```js
const VALIDATION_ERROR = 'VALIDATION_ERROR';
```

**Comment by AndreMaz** [comment]
Could you create a PR?

You would have to move the hard-coded error types (in `src/errors.js`) to `src/constants.js` and then export them in `index.js` as being done here
https://github.com/moleculerjs/moleculer/blob/422876c8f0142caa313a792f8069ac7aac12fb47/index.js#L46-L49

**Comment by DenisFerrero** [comment]
Hi, I'm in hurry to release a project. When I get some spare time I'll surely do it :ok_hand:
