### ISSUE TITLE
Events signature issues

### ISSUE THREAD

**Issue by ipetrovic11** [moleculerjs/moleculer#1058]
There are 2 signatures for event functions:

- old(payload, sender, event, ctx)
- new(ctx)

This makes things confusing when using moleculer packed with "pkg".

Is there a plan to remove old signature: https://github.com/moleculerjs/moleculer/blob/3d24e11c2dd3633ee530369d9f7effe1ad9ffa98/src/service.js#L463 ?

**Comment by icebob** [comment]
I don't know because it will break old modules. But you can force it with `context: true` in event definition.
Maybe I can add a broker option which disables the legacy signature.

**Comment by ipetrovic11** [comment]
Good to know!

We are still on 0.14.0-beta5 because of changes with fastest validator :(
