### ISSUE TITLE
Authentication error with NATS

### ISSUE THREAD

**Issue by Eliam93** [moleculerjs/moleculer#1061]
Hi all,
I'm using moleculer v. 0.14.19 with nats-server v. 2.7.0.
I've added authorization field in nats-server config, like this:

`authorization = {
    user: admin
    password: admin
}`

and in ServiceBroker config this object:

`url: "nats://localhost:4222",
user: "admin",
pass: "admin"`.

When I try to start the microservice, on nats-server console I see something like:

`[4028] [ERR] 127.0.0.1:51509 - cid:5 - "v2.6.0:nats.js" - authentication error`

and in node console I see:

Connection is failed. 'Authorization Violation'

If it is helpful to understand the problem, I post the log of console.log putted under transporter/nats, constructor function, after microservice start:
`{
url: 'nats://localhost:4222',
user: 'admin',
pass: 'admin',
preserveBuffers: true,
maxReconnectAttempts: -1
}`
...and after the second time it's trying to reconnect:
`{
url: 'nats://localhost:4222',
user: undefined,
pass: undefined,
preserveBuffers: true,
maxReconnectAttempts: -1,
servers: [ 'localhost:4222' ]
}`

Thanks,
Elia

**Comment by icebob** [comment]
Use this shorthand:

```js
transporter: "nats://admin:admin@localhost:4222"
```

or 
```js
	transporter: {
		type: "NATS",
		options: {
			servers: ["nats://localhost:4222"],
			user: "admin",
			pass: "admin"
		}
	}
```

**Comment by Eliam93** [comment]
Thanks a lot! It works with the shorthand.
