### ISSUE TITLE
subscriber's event function ctx with different structure

### ISSUE THREAD

**Issue by lling1105** [moleculerjs/moleculer#1070]
i have 2 clients subscribe the same event, when both receive the notice, one has ctx and can get the params correctlly, but the other one ctx is the params value, no params path, why?

both client service with the same codes,
#1 client event receiver:
     ctx.params  -> {"result":"ok"}

#2 client event receiver:
     ctx  -> {"result":"ok"}  and no ctx.params

**Comment by AndreMaz** [comment]
Hi @lling1105 can you create a repro repo please?

**Comment by lling1105** [comment]
@AndreMaz this issue appeared when use webpack.js to build bundle.js, guess it's about the output setting: libraryTarget: 'commonjs2'. i changed to other kind target, but still the same

**Comment by lling1105** [comment]
solved! set  webpack optimization.minimizer to none

**Comment by ngraef** [comment]
This seems like it's related to moleculer's support for two different function signatures for event handlers (see the [0.14 changelog](https://github.com/moleculerjs/moleculer/blob/master/CHANGELOG.md#context-based-events)). The code that determines which signature to use relies on the name of the parameter being `ctx` or `context`:

https://github.com/moleculerjs/moleculer/blob/422876c8f0142caa313a792f8069ac7aac12fb47/src/service.js#L32-L34

Webpack (or any other) minimizer will usually change the parameter name, causing the function to be passed params for the old event handler signature. As the changelog notes, you can add `context: true` to the event definition to force the new signature if you want to continue using a minimizer.

**Comment by icebob** [comment]
Exactly.
