### ISSUE TITLE
Some deeply nested options fed via docker compose env file are getting ignored

### ISSUE THREAD

**Issue by rohitpatidar007** [moleculerjs/moleculer#1088]
### Prerequisite : 
Code built on latest moleculer version with rabbitmq as transporter . Application is run via docker compose and transporter options are passed via docker-compose.env file.

### **Issue :** 
As suggested by @AndreMaz on how to set deeply nested options via https://moleculer.services/docs/0.14/runner.html#Configuration-loading-logic , I tried to add below parameters to docker-compose.env for configuring RabbitMQ as transporter  :

MOL_TRANSPORTER__TYPE=AMQP
MOL_TRANSPORTER__OPTIONS__URL=amqp://xyz:xyz@localhost:5672/xyz
MOL_TRANSPORTER__OPTIONS__EVENTTIMETOLIVE=10000
MOL_TRANSPORTER__OPTIONS__HEARTBEATTIMETOLIVE=10000
MOL_TRANSPORTER__OPTIONS__PREFETCH=100

When I use above configuration then **type, url, prefetch** works perfectly as I'm able to connect to intended rabbitmq and also the channel formed on rabbitMQ has a prefetch of 100. But **heartBeatTimeToLive and eventTimeToLive** doesn't work. Queues created on rabbitmq related hearbeat and event doesn't have any effect of above parameters, these queues are created using default **heartBeatTimeToLive and eventTimeToLive i.e. 5000** .

**Note :** Transporter configuration inside the dockerized moleculer.config.js is as below **(so it is overriding type, url, prefetch from docker-compose environment variable but not 'eventTimeToLive'** ) : 
`transporter: {
        type: "AMQP",
        options: {
            url: "amqp://localhost",
            eventTimeToLive: 5000,
            prefetch: 2,
            socketOptions: {
                servername: process.env.RABBIT_SERVER_NAME
            },
            // If true, queues will be autodeleted once service is stopped, i.e., queue listener is removed
            autoDeleteQueues: true
        }
`
### **Possible root cause :** 
Did some analysis around moleculer runner.js code and found below : 
This might be due to code `.map(level => level.toLocaleLowerCase())` at line number 232 on https://github.com/moleculerjs/moleculer/blob/master/src/runner.js . 

So when it tries to read 'HEARTBEATTIMETOLIVE' from env parameter then above code in runner.js changes it to 'heartbeattimetolive', and this won't work as correct options used in amqp.js is 'heartBeatTimeToLive' and 'eventTimeToLive' . So because of this the parameter options which have capital letters won't be taken into consideration.

I'm not able to attach the screenshots from rabbitMq due to security restrictions, but hope I made case clear..

**Comment by icebob** [comment]
Duplicated with discussion topic

**Comment by rohitpatidar007** [comment]
Thanks @icebob , it's working . I will put comments in discussion topic for more information.
