### ISSUE TITLE
Streaming does not work with enabled compression

### ISSUE THREAD

**Issue by Jank1310** [moleculerjs/moleculer#1100]
## Current Behavior

Streaming does not work when compression middleware is enabled

## Expected Behavior

Streaming should work

### Steps to Reproduce

1. Add compression middleware
2. Send stream
3. Receive stream => fails

### Failure Logs
```
Cannot read properties of null (reading 'on')
params.on("data", () => {})
```

**Comment by Jank1310** [comment]
@icebob Took some time to find the cause of the problem: sending "large" meta data along with the stream. It works without compression but not with compression enabled. With compression the receiving action handler is called two times. The first time with params = null, the second time with params = stream.

Sample repo: https://github.com/Jank1310/moleculer-compressed-stream-test-js

Steps to reproduce:

1. Start local nats
2. ```npm run dev1```
3. ```npm run dev2```
4. call: sender.send action

Hope it helps :)

**Comment by Jank1310** [comment]
@icebob Did you get a chance to look at the example code?

**Comment by icebob** [comment]
Thanks the repro code. It looks like there is an issue in the stream ordering logic. Without compression, every packet is received one by one in the original order, but with compression, every packet compressing takes a different elapsed time, so the packets are received in random order and the last packet is received at first. This is the problem.
