### ISSUE TITLE
Ignore undefined methods when extends from parent class Service<S = ServiceSettingSchema>

### ISSUE THREAD

**Issue by wince87** [moleculerjs/moleculer#1102]
node_modules/moleculer/index.d.ts
class Service<S = ServiceSettingSchema> implements ServiceSchema {
.......................
......................

		**[name: string]: any** Problem in this line!!!

**Comment by AndreMaz** [comment]
Hi. Can you please provide more info of what exactly is the problem? How solving it will fix the issue and what's the alternative that can improve this situation?
