### ISSUE TITLE
Disable cached response for an action

### ISSUE THREAD

**Issue by haris-reverie** [moleculerjs/moleculer#1103]
I am stuck on one use case, which comprises of disabling the cached response just for some api's , so that i could get a fresh response from that actions. So far i have got someting that only disables caching but noting which bypasses the cached response . 

I was thinking of some option in cache object of action just like "enable" property maybe "enableCached" property which executes the code even though it has cached result.

Only way i could see is cleaning the cache manually before making that request.

**Comment by ColinFrick** [comment]
@haris-reverie Maybe conditionally caching?
https://moleculer.services/docs/0.14/caching.html#Conditional-caching
