### ISSUE TITLE
errorHandler in moleculer.config.js

### ISSUE THREAD

**Issue by HaiBien** [moleculerjs/moleculer#1114]
#moleculer.config.js

"use strict";
module.exports = {
    errorHandler: null,
}

I want to know how errorHandler is used?
I have seen the document (https://moleculer.services/docs/0.14/broker.html#Global-error-handler) but it doesn't help

**Comment by lucduong** [comment]
What exactly do you expect here?

Could you write more detail? Cos that I saw you set `errorHandler` is `null`,

**Comment by HaiBien** [comment]
@lucduong  e chào a ạ. 
em đang muốn bắt một số lỗi và custom lại nó. Em đọc trên docs thì thấy có errorHandler xử lý lỗi, mà e chưa biết phải sử dụng nó như thế nào ạ.
# ảnh lỗi muốn custom: https://prnt.sc/dZBte7wiuh7a
![image](https://user-images.githubusercontent.com/59249915/183024321-3c1a18e7-1500-44ca-8e59-91d719829872.png)

**Comment by intech** [comment]
For 404 handler in `moleculer-web` see [this example](https://github.com/moleculerjs/moleculer-web/blob/master/examples/full/index.js#L164-L169)

**Comment by HaiBien** [comment]
> For 404 handler in `moleculer-web` see [this example](https://github.com/moleculerjs/moleculer-web/blob/master/examples/full/index.js#L164-L169)

This works perfectly. Thanks
