### ISSUE TITLE
Meta data is empty for stream with enabled compression

### ISSUE THREAD

**Issue by Jank1310** [moleculerjs/moleculer#1122]
@icebob The latest release fixed the stream issue but unfortunately meta data sent using `meta` is missing :-/
I've updated the reproduction repository and added a log output for meta which is `{}` is compression is enabled.

https://github.com/Jank1310/moleculer-compressed-stream-test-js

## Steps to Reproduce
Start local nats
npm run dev1
npm run dev2
call: sender.send action
Log on receiver side should contain the meta data

**Comment by icebob** [comment]
Thanks, nice catch. But it looks like a more complicated issue. :(

**Comment by Jank1310** [comment]
Let me know if I can help somehow 🙂

**Comment by icebob** [comment]
@Jank1310 would be good if you can try it in your environment. You can install with `npm i moleculerjs/moleculer#issue-1122`

**Comment by Jank1310** [comment]
It works, thank you very much 🙏

**Comment by icebob** [comment]
Great, then I will fix the E2E issues and I will make a new release.

**Comment by icebob** [comment]
Released as 0.14.23
