### ISSUE TITLE
Slower broker startup times since v0.14.20

### ISSUE THREAD

**Issue by disce-omnes** [moleculerjs/moleculer#1132]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

Since version 0.14.20 broker startup time is much slower if there are many services in it.

In an [example project](https://github.com/disce-omnes/moleculer-slower-start/blob/master/index.js) with 2 brokers & 1 000 services each startup time went from ~620 ms (0.14.19) to ~3 500 ms (0.14.20).

In a real project (~45 nodes, ~600 services) when starting all nodes locally with moleculer-runner startup time went from ~20 seconds to ~35 seconds.

My understanding is that it has to do with [adding](https://github.com/moleculerjs/moleculer/releases/tag/v0.14.20) a debouncer to announce local services as they're coming online instead of waiting for all local services to start.

Was this slowdown an expected trade-off for solving a potential dead-lock?

Would it be a good idea to add an ability to opt-out of this change?

### Steps to Reproduce

Run index.js in the [example project](https://github.com/disce-omnes/moleculer-slower-start/blob/master/index.js)

**Comment by icebob** [comment]
Yeah, the dead-lock resolve PR caused the slowdown. I don't think, we can turn on/off these changes because it would make the startup code too complicated in the broker. 

The slow code is in line 468 (safety object cloning to avoid circular JSON structures), but the root cause is that we call this method after every service starts (while it is only sent once per second):
https://github.com/moleculerjs/moleculer/blob/141e41c27f457c06156d0d8cf0da2cd1fbc76f9a/src/registry/registry.js#L446-L471

In previous versions, we called it only after the broker started.

@AndreMaz do you have an idea, how we can improve it? E.g. only generate the local info when we send it...

**Comment by disce-omnes** [comment]
Stringifying & parsing JSON has a heavy performance penalty. It might be possible to just traverse an object recursively and replace all circular references with something. In fact there is already circularReplacer that does a similar thing. I did that in my project for BaseTraceExporter.flattenTags & got about x3 performance boost.

That & generating info only when sending it should improve startup times.

I can try this solution & if it works, submit a PR.

**Comment by AndreMaz** [comment]
As @icebob mentioned this was introduced in a fix to solve a service deps dead-lock in mixed arch (link to the original issue with an example: https://github.com/moleculerjs/moleculer/issues/1077) 

The solution to overcome this was to emit INFO packets after each service "wakes" up and become available.

However, to avoid emitting a burst of INFO packets (one for each service) we've added a `debounce()` method with a 1000ms delay.
Link to code: https://github.com/moleculerjs/moleculer/blob/master/src/service-broker.js#L304-L306

>  It might be possible to just traverse an object recursively and replace all circular references with something. In fact there is already circularReplacer that does a similar thing. I did that in my project for BaseTraceExporter.flattenTags & got about x3 performance boost.

@disce-omnes can you please check if this brings a significant performance boot?

**Comment by disce-omnes** [comment]
> It might be possible to just traverse an object recursively and replace all circular references with something. In fact there is already circularReplacer that does a similar thing. I did that in my project for BaseTraceExporter.flattenTags & got about x3 performance boost.

Unfortunately, that didn't improve performance.

It would seem that the way to optimize broker startup time is to call `regenerateLocalRawInfo` only once a second, before each INFO packet, instead of each time a local service comes online.

Alternatively, circular reference protection on startup could be dropped, if circular references could only be in metadata (that is only in user-supplied data). Instead there could be a one-time check before service starts, if metadata is circular, then an error is thrown. But that is a breaking change.

**Comment by icebob** [comment]
@disce-omnes I've fixed the issue. Again it starts in 600ms instead of 4sec:

![image](https://user-images.githubusercontent.com/306521/193424048-537d360f-550f-44ed-9aa0-df300247032e.png)

Could you test it plz in your project? For the test, install master with `npm i moleculerjs/moleculer`

**Comment by disce-omnes** [comment]
Yes, it brought startup times almost to the same level as before the change. I tested on two different machines:

First test case:
- 0.14.19: 645 service(s) started successfully in 23s
- 0.14.23: in 40s
- master (c91fa4b5cc8510c51203eb1986bcacc49333f6ae): in 25s

Second test case:
- 0.14.19: 645 service(s) started successfully in 29s
- 0.14.23: in 49s
- master (c91fa4b5cc8510c51203eb1986bcacc49333f6ae): in 30s

Can I ask when is the new release with this change to be expected?

**Comment by icebob** [comment]
Cool. I try release it this week.

**Comment by icebob** [comment]
Released.
