### ISSUE TITLE
mergeSchemas is no longer available as a static class method of Service

### ISSUE THREAD

**Issue by ostracod** [moleculerjs/moleculer#1133]
## :stop_sign: Do you want to ask a question ?

Please head to the [Discord chat](https://discord.gg/TSEcDRP)

## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

## Current Behavior

Under Moleculer 0.14.23, the static class method `mergeSchemas` of `Service` has been changed to be an instance method. As a result, `Service.mergeSchemas` is `undefined`.

## Expected Behavior

I expect `mergeSchemas` to be available as a static class method of `Service`, as documented here: https://moleculer.services/docs/0.14/api/service.html#mergeSchemas

## Failure Information

This breaks compatibility with our microservices which rely on `Service.mergeSchemas`.

### Steps to Reproduce

1. Create a project which has Moleculer 0.14.23 as the only dependency.
2. Run the code snippet below.
3. The output is `undefined`, but I am expecting `[Function: mergeSchemas]`. 

### Reproduce code snippet

```js
const { Service } = require('moleculer');
console.log(Service.mergeSchemas);
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.23
* NodeJS version: 16.16.0
* Operating System: macOS 12.5.1

### Proposed Resolution

We would appreciate if you did one of the following:

- Expose `Service.mergeSchemas` again as specified by the documentation.

OR:

- Update the documentation to specify that `mergeSchemas` is an instance method. It is not a huge deal to call `this.mergeSchemas`, but we want to make sure our code won't break again because of a compatibility issue.

Thanks for any help you can give on this issue.

**Comment by intech** [comment]
@ostracod Thanks for your feedback!
As I understood from the proposed solution, updating the documentation would be a good compromise.
You can read about [this issue](https://github.com/moleculerjs/moleculer/issues/1124#issuecomment-1218366223).

**Comment by ostracod** [comment]
@intech Thanks for updating the docs!
