### ISSUE TITLE
Why remove repl in .d.ts file? its not match document in website.

### ISSUE THREAD

**Issue by moonrailgun** [moleculerjs/moleculer#1134]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

![image](https://user-images.githubusercontent.com/6964737/188200563-5cf41b3a-c3be-4297-9ca5-9a1b1961badd.png)

## Expected Behavior

its looks like remove repl* in 417f893841e9edc18ca79acefede2e9a15af7320

But in website(https://moleculer.services/docs/0.14/configuration.html) and source code(https://github.com/moleculerjs/moleculer/blob/master/src/service-broker.js). those config item is still exist

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. just install latest version of moleculer
2. add `replDelimiter`
3. TS error throw

### Reproduce code snippet

```js
const brokerConfig: BrokerOptions = {
  // ...
  replDelimiter: '$',
}
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.23
* NodeJS version: v16.13.1
* Operating System: windows 10

**Comment by shawnmcknight** [comment]
The types were moved to the repl package itself and augment the base moleculer module. The types don't belong in moleculer itself because the repl is a plugin and without the plugin the types are not relevant.

**Comment by moonrailgun** [comment]
> The types were moved to the repl package itself and augment the base moleculer module. The types don't belong in moleculer itself because the repl is a plugin and without the plugin the types are not relevant.

Hi, @shawnmcknight. Thanks for your reply, so it looks like i have to import `moleculer-repl` in my source code although i not use it directly.

---------

Another problem is its looks like add 3 field and i have to explicit declare it although i not use it. Why not define as a optional?

![image](https://user-images.githubusercontent.com/6964737/188252829-7df337c6-aade-4321-a621-da0dfc774e5f.png)

**Comment by shawnmcknight** [comment]
> Hi, @shawnmcknight. Thanks for your reply, so it looks like i have to import `moleculer-repl` in my source code although i not use it directly.

Not necessarily.  You need to make sure Typescript is aware of the repl's `d.ts` file.  By default, Typescript includes `**` and excludes `node_modules`, so the repl's `d.ts` file won't be visible without importing it.  However, there are a couple of approaches you could take to make it visible without importing.  You could add it to your include paths, or use a technique like indicated [here ](https://www.npmjs.com/package/jest-extended#typescript) for `jest-extended` where you create a `global.d.ts` file that is in your include paths and import the repl.  `jest-extended` is similar in that a consumer would never import it directly but it gets plugged in.  I would recommend that second approach.

> Another problem is its looks like add 3 field and i have to explicit declare it although i not use it. Why not define as a optional?

I can't speak to the content of the types as I did not create them nor have I done much analysis of the code to determine what the types should be.  If there's a problems with those types I'd suggest opening an issue and/or PR in the repl's repo.

**Comment by moonrailgun** [comment]
Thanks for your reply, i will close this issue
