### ISSUE TITLE
I have a problem sending data from frontend (ReactJs) to backend (NodeJs).

### ISSUE THREAD

**Issue by HaiBien** [moleculerjs/moleculer#1136]
I have a problem sending data from frontend (ReactJs) to backend (NodeJs).

**my data**
```
let files = [
{fileName: 'a.png', filePath: './/file/a.png'},
{fileName: 'b.png', filePath: './/file/b.png'}
]
```
**the data i get at the backend**

![image](https://user-images.githubusercontent.com/59249915/190378410-f4e8a948-815a-4ab0-ab85-d3a57d98ac71.png)

`
data  [
{
fileName: ['a.png','b.png'],
filePath: ['.//file/a.png', './/file/b.png']
}
 ]
`

how do i get the data in its correct format

**Comment by intech** [comment]
@HaiBien Make a repro (moleculer) and raw request to API.
What type of data is passed (json/multipart/urlencoded)?

**Comment by HaiBien** [comment]
@intech type of data json

**Comment by icebob** [comment]
Please create a repro code.
