### ISSUE TITLE
Getting **Parsing failed at** error while calling garphql mutation for upload image

### ISSUE THREAD

**Issue by amitpatel9169** [moleculerjs/moleculer#1160]
While calling Garphql mutation for upload image getting parsing failed error attach code and error screenshots for your references.

**My code**
![image](https://user-images.githubusercontent.com/54776777/205010786-d5102273-22cd-4fc5-bb93-6c71808bfe82.png)

**In api.service.js setting of bodyParsers**
![image](https://user-images.githubusercontent.com/54776777/205011260-780817f8-68dc-4a1c-8f19-243a7ed03955.png)

**Error I am getting**
![image](https://user-images.githubusercontent.com/54776777/205011508-9740c2b6-b90a-4d64-9e09-bff148fcd5d2.png)

Please help me how can I resolve this error this same code run smoothly in ExpressJs

**Comment by shawnmcknight** [comment]
I'm assuming that the parsing error is being returned by the called API, but none of that code is shown in your example.  What's the called API look like?

**Comment by amitpatel9169** [comment]
In called API, I get proper response in ExpressJs in molecular I Got Error. Using axios called GraphQL API you can see it in given code.

I think this error because of **FormData().**

![image](https://user-images.githubusercontent.com/54776777/205111675-8f1b493f-d796-4f45-b2b8-f19d38e4b7c3.png)

**Comment by amitpatel9169** [comment]
In called API, I get proper response in ExpressJs in molecular I Got Error. Using axios called GraphQL API you can see it in given code.

I think this error because of **FormData().**

![image](https://user-images.githubusercontent.com/54776777/205111675-8f1b493f-d796-4f45-b2b8-f19d38e4b7c3.png)
