### ISSUE TITLE
Registry with TCP transport in docker is working wrong

### ISSUE THREAD

**Issue by intech** [moleculerjs/moleculer#1180]
## Current Behavior
In the screenshot below, we can see how the nodes have successfully connected. And then, there is a reconnection according to the registry information. As a result, broadcast events work between nodes, but `$node.list` remains empty.
It looks like some recent changes in the registry have broken the interaction with TCP transport.

![Screenshot from 2023-01-26 16-18-12](https://user-images.githubusercontent.com/451306/214834174-7951693b-da8e-437c-ad6f-f4a3a48516ff.png)

## Expected Behavior
The Registry must contain information about the connected node and not trigger reconnect events of this node.

## Failure Information
Then there are endless attempts to discover without any result since the nodes are connected and interact.

### Reproduce code snippet
https://github.com/intech/moleculer-tcp-bug

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.28
* NodeJS version: 19.5.0
* Operating System: Debian GNU/Linux 11 (bullseye)
* Docker: Docker version 20.10.23, build 7155243

**Comment by icebob** [comment]
Thanks the repro, I will check it.

**Comment by icebob** [comment]
The `$node.list` is an action, so you should call it with `broker.call("$node.list")`. In this case the code works, no reconnecting:

![image](https://user-images.githubusercontent.com/306521/215573701-e8b7fcbe-e970-4169-82ec-260aeb697374.png)

**Comment by intech** [comment]
@icebob sorry for wasting your time.
