### ISSUE TITLE
Use broker  Runner: Service name can't be empty

### ISSUE THREAD

**Issue by 532815096** [moleculerjs/moleculer#1213]
when I use broker, Service name can't be empty
code: 
![image](https://github.com/moleculerjs/moleculer/assets/12792386/ce865972-5311-48f9-a1b7-20c32d3ba9c3)
![image](https://github.com/moleculerjs/moleculer/assets/12792386/defe2bdf-d8e6-4652-8c5a-9a4c92da74f5)
And how can I use the Runner to start the server?

**Comment by 532815096** [comment]
When use moleculer-runner must not use broker?

**Comment by AndreMaz** [comment]
With moleculer-runner you need to export service schema from the `api.service.js` 

Example:
```js
module.exports = {
  name: 'api',

  actions: {},

  // other stuff goes here
}
```

For questions please use Discord https://discord.gg/TSEcDRP

**Comment by 532815096** [comment]
But broker how can I use with service schema, please?
