### ISSUE TITLE
moleculer-amqp-queue issue

### ISSUE THREAD

**Issue by CodeFox1119** [moleculerjs/moleculer#1231]
I have one problem in using moleculer-amqp-queue(https://github.com/lehno/moleculer-amqp-queue) in my Moleculer project. I'm using Moleculer v14 with node v18.16.1. when I tried to install moleculer-amqp-queue, it failed with dependencies error.

**Comment by icebob** [comment]
It' not an official module, please open the issue in the repo of the module.
