### ISSUE TITLE
Documentation on cache lock does not match the source

### ISSUE THREAD

**Issue by ponez** [moleculerjs/moleculer#1252]
On https://moleculer.services/docs/0.14/caching#Cache-locking suggests that we can use 

```ts
const broker = new ServiceBroker({  
    cacher: {  
        ttl: 60,  
        lock: true, // Set to true to enable cache locks. Default is disabled.  
    }  
});
```

But in base.js, we're checking that
ts
if (opts.lock.enabled !== false) 
so just passing a boolean won't work here
and in another part, it says 
```ts
const broker = new ServiceBroker({  
    cacher: {  
        ttl: 60,  
        lock: {  
            ttl: 15, // The maximum amount of time you want the resource locked in seconds  
            staleTime: 10, // If the TTL is less than this number, it means that the resources are staled  
        }  
    }  
});
```
but still, there's no enabled key until we reach the third part.

**Comment by icebob** [comment]
The `lock: true` is transferred to `{ enabled: true}` the following code: https://github.com/moleculerjs/moleculer/blob/da2aabcc7e5254ac3ce2de689bac3ce3d16033b8/src/cachers/base.js#L324-L327
