### ISSUE TITLE
using  grunt.loadNpmTasks('grunt-contrib-obfuscator') cause service event context lost, always undefind

### ISSUE THREAD

**Issue by lling1105** [moleculerjs/moleculer#1285]
## Current Behavior

if not using grunt-contrib-obfuscator, every service is working well.  after obfuscator, action and method are working well,but the event method received ctx only has param property, other ctx property lost

## Expected Behavior
use grunt-contrib-obfuscator to obfus the codes and working well.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version:0.14.17
* NodeJS version: 14.18.1
* Operating System:win11

**Comment by icebob** [comment]
Moleculer tries to detect the event handler signature, but if the property name is not `ctx` it uses as a non-context signature. You can force the context signature mode with `context: true` in event properties, like here:

![image](https://github.com/moleculerjs/moleculer/assets/306521/ea858b3f-f664-4f68-b2ba-2d78302eb2ac)

**Comment by lling1105** [comment]
> Moleculer tries to detect the event handler signature, but if the property name is not `ctx` it uses as a non-context signature. You can force the context signature mode with `context: true` in event properties, like here:
> 
> ![image](https://private-user-images.githubusercontent.com/306521/332095064-ea858b3f-f664-4f68-b2ba-2d78302eb2ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzQwMDQsIm5iZiI6MTcxNjM3MzcwNCwicGF0aCI6Ii8zMDY1MjEvMzMyMDk1MDY0LWVhODU4YjNmLWY2NjQtNGY2OC1iMmJhLTJkNzgzMDJlYjJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxMDI4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTlmMmU0Yzk0MWMxZWIxZTliMjUyZDJmNDI2NmJiNjY1OWM2ZmVlMjNmOTlhOTFhZjkxZDY1Mzg5ZGQ2NzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JZEHuX0xYFZj3N8orSbFrefwaVPrOiQbpW4DZvUDK8U)

thanks much @icebob  for your reply! the same time i also find another solution is set the obfus options as below and working well
```javascript
options:{
                reservedNames: ['context','ctx'],
                reservedStrings: ['context','ctx']
}
```
