### ISSUE TITLE
Memory leak when a call to an action stream fails

### ISSUE THREAD

**Issue by Thalandor** [moleculerjs/moleculer#1296]
## :stop_sign: Do you want to ask a question ?

Please head to the [Discord chat](https://discord.gg/TSEcDRP)

## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

When a call to an action stream fails for whatever reason from the service listener, node memory increases non-stop. The more calls you make to the action stream and fails, the more the memory increases until you have an out of memory exception.

## Expected Behavior

When an action stream fails, memory does not increase on the receptor side.

## Failure Information

Checked on moleculer 14 and moleculer 15.

### Steps to Reproduce

1. Create two services, a caller and a listener
2. Listener implements an action stream
3. Caller calls the listener action stream with a big file (test done with a 50mb file)
4. Make listener fail (for example making the action stream just throw an exception) and memory is not released.
5. Caller calls again
6. Listener fails again
7. After several retries listener throws a out of memory exception.

### Reproduce code snippet
I created this repository with a minimal example and a readme to reproduce it
https://github.com/Thalandor/moleculer-issue

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: Tried with 14.33 and 15-beta1
* NodeJS version: 20
* Operating System: Ubuntu
* Services running on docker images. The repo does not have the docker images done, however the memory is increased anyway.

Thib3133 from the discord server provides some hints regarding the possible error:
![image](https://github.com/user-attachments/assets/07736f82-9001-4fbe-a822-6c2d490a8de5)

### Failure Logs

![image](https://github.com/user-attachments/assets/f9704524-089f-4c28-abe3-9b4d9461906a)

**Comment by icebob** [comment]
Pls check it, in 0.14.35. If it still alive, please reopen.
