### ISSUE TITLE
Support gracefully shutdown

### ISSUE THREAD

**Issue by zhaoyao91** [moleculerjs/moleculer#160]
How about supporting gracefully shutdown? Say, when service received SIGTERM, it first stops receiving new actions, and continue processing already received actions, and then, cleanup and really shutdown.

**Comment by icebob** [comment]
Unfortunately not. If exit signal is received, broker calls `stopped` handlers of all services, closes the transporter connection and exit the process.

**Comment by ppzz** [comment]
I have tried this circumstance.

I have a three Services ： A, B and C.
In service A : 
```
  actions: {
    tryToClose (ctx) {
      ctx.broker.stop()
    },
    async longTimeAction () {
      let sleep = async time => new Promise(resolve => setTimeout(resolve, time))
      await sleep(10 * 1000)
      return 'long time action resolved'
    }
  }
```
then I call A.longTimeAction in service B ,
the action would take 10 seconds to return that string .
then  I call A.tryToClose in service C. 
this operation will close Service A immediately.
And service B  is still waiting now .
 then B will get an exception like this:
```
{"level":40,"message":"Node 'T4F-MBP-12164.local.35349' disconnected."}
>> ERROR: Request is rejected when call 'ServiceA.longTimeAction' action on 'MY-MBP-12164.local.35349' node.
RequestRejected: Request is rejected when call 'ServiceA.longTimeAction' action on 'MY-MBP-12164.local.35349' node.
    at pendingRequests.forEach (/Users/zhaopeng/project/demos/penn_demo_2/node_modules/moleculer/src/transit.js:482:16)
...
```

better way to close the service is to wait all requests and events have been done and close it. 

you can change broker.stop()  or add another close method to do that .

**Comment by TomKaltz** [comment]
+1

**Comment by ryanm-pm** [comment]
A possible solution to this would be to leverage a `WeakSet` and add the context to it when created. The handler could look to this in order to determine if a request is currently in progress.

**Comment by icebob** [comment]
Hmm, not bad.

**Comment by zhaoyao91** [comment]
To support graceful shutdown, there should be 2 stages for transporter or broker:
1. stop receiving any new requests, but keep connection on and keep on handling already received requests;
2. when all received requests have been handled, close connection and close the broker (service)

**Comment by icebob** [comment]
Implemented. Released in v0.13

**Comment by TomKaltz** [comment]
Can you point me to the documentation for this feature?

**Comment by icebob** [comment]
It is not released yet. I will write docs about it, if I'm ready with 0.13.

**Comment by icebob** [comment]
Released with 0.12.4

**Comment by cosmin-harangus** [comment]
Can you point me to the documentation where this was released and how to achieve graceful shutdown of current active requests to a service?

**Comment by icebob** [comment]
https://moleculer.services/docs/0.14/context.html#Context-tracking
