### ISSUE TITLE
MsgPack doesn't support Date objects

### ISSUE THREAD

**Issue by juanchristensen** [moleculerjs/moleculer#171]
Hi,

I've found an issue when migrating from JSON as serializer to MsgPack.
While JSON supports Date objects, MsgPack doesn't, and instead "loses" the value and results in an empty object value.

Even though the MsgPack spec doesn't support it, it would be possible to extend the current MsgPack Moleculer serializer to support Date objects by converting them to their ISO string format.

**Comment by icebob** [comment]
Same issue on MsgPack side: https://github.com/mcollina/msgpack5/issues/19

**Comment by baadc0de** [comment]
A timestamp type is defined as the `-1` extension type here:

https://github.com/msgpack/msgpack/blob/master/spec.md#extension-types

**Comment by icebob** [comment]
It's added: https://github.com/mcollina/msgpack5/pull/60
