### ISSUE TITLE
2 events triggered when disableBalancer is set to true expected to see only 1

### ISSUE THREAD

**Issue by mailaneel** [moleculerjs/moleculer#208]
Moleculer Version: 0.12.0-rc1

Test setup, 

Have 3 services math1, math2, math3

`math1` triggers -> `math1.added` just for testing sake it doesn't mean anything
`math2`, `math3` listen to `math1.added` using service events

NodeIDs are different for each of these services `pubsub-transporter-test-${number}`

when called `this.emit('math1.added')`

Below is the log I see
```
PublishedBalanceRequest:MOL.REQB.math1.add
ReceivedBalancedRequest:MOL.REQB.math1.add
PublishedBalanceEvent:MOL.EVENTB.math3.math1.added
PublishedBalanceEvent:MOL.EVENTB.math2.math1.added
Published:MOL.RES.pubsub-transporter-test-1
ReceivedBalancedEvent:MOL.EVENTB.math3.math1.added
ReceivedBalancedEvent:MOL.EVENTB.math2.math1.added
```

Expected is below where one event is emitted and let transporter(in my case google pubsub) handle balancing

```diff
PublishedBalanceRequest:MOL.REQB.math1.add
ReceivedBalancedRequest:MOL.REQB.math1.add
- PublishedBalanceEvent:MOL.EVENTB.math3.math1.added
- PublishedBalanceEvent:MOL.EVENTB.math2.math1.added
+ PublishedBalanceEvent:MOL.EVENTB.math1.added
Published:MOL.RES.pubsub-transporter-test-1
ReceivedBalancedEvent:MOL.EVENTB.math3.math1.added
ReceivedBalancedEvent:MOL.EVENTB.math2.math1.added
```

**Comment by icebob** [comment]
Thanks. I'm checking...

**Comment by icebob** [comment]
@mailaneel What kind of transporter do you use?

**Comment by mailaneel** [comment]
@icebob here is the gist of the transporter that I am working on
https://gist.github.com/mailaneel/ec96a0e7712f10db8a67f141eac36172

**Comment by icebob** [comment]
Thanks. I tried (with NATS), but I think the logic is correct.
Broker **groups** (by service name) and balances the emitted events. It means, only one instance **per service** receives the event.
So if you have math2 service & math3 service and both subscribe to `math1.added`, both services receive the event. Because both are in different groups (`math2` & `math3`). 
It happens only what you expect if you run 2+ instances of math2 or math3.

**Comment by mailaneel** [comment]
I think here the issue I am talking about is at the publish stage. In the scenario that I have mentioned above, I see `2` publish and `2` receive where as I except to see only `1` publish and `2` receives.

Once event is published to topic `math1.added` -> multiple consumers can subscribe to this topic, in this case we see 2 subscriptions to the same topic -> if we add more instances we those consumers will join the same subscription group if exist

Is there any way to chat with you

**Comment by icebob** [comment]
Gitter

**Comment by icebob** [comment]
Can we close it?
