### ISSUE TITLE
Problem running in Kubernetes with 0.12

### ISSUE THREAD

**Issue by kevinsegal** [moleculerjs/moleculer#213]
I have been running Moleculer for my project for several months but just tried to deploy a new cluster running the new 0.12.1 release and it just stalls out when I run with moleculer-runner.  At first I thought it had something to do with the transporter settings (I was using NATS) but even when I run all services from the same node (from a unified services folder) it does not seem to detect any of the services when I run "moleculer-runner" or "moleculer-runner services".  However I was able to get it to run just one service by specifying "services" as SERVICEDIR and "news" as SERVICES as env vars.  Any ideas why its having trouble discovering the services from just a folder, or without any specific directories defined?  Must be a bug in moleculer-runner ? I do not have this problem when running locally, just when I deploy to my Kubernetes cluster (running 1.9.3).

**Comment by icebob** [comment]
Hi @kevinsegal,
Thanks for reporting it. 
Has somebody else similar problem?

**Comment by chux0519** [comment]
@icebob @kevinsegal 
The `ProtocolVersionMismatchError` may be one of the reasons, without a careful look at the code, just guess. In version 0.11.x, `PROTOCOL_VERSION` was "2" and was defined in `packsets.js`. In version 0.12.x, `PROTOCOL_VERSION` was "3" and defined in the `service-broker.js`. When sending the package, payload does not carry version anymore, then `ProtocolVersionMismatchError` would be triggered in `messageHandler` at `transit.js`.

**Comment by icebob** [comment]
@chux0519 In 0.12.x, the payload contains the version, but protocol is changed, so 0.11 can't communicate with 0.12. In this case, broker throws `ProtocolVersionsMismatchError`. But it doesn't affect the service loading logic.

**Comment by kevinsegal** [comment]
I noticed on the updated Docker documentation you have the base image pulling from node 8, I'm running node 9.6 on my current 0.11 cluster and I think it's 9.6 or 9.7 I've been trying to deploy 0.12 with -- could the node version be an issue?

**Comment by icebob** [comment]
I didn't try Docker with Node 9, but Travis tests Moleculer on Node 6, 8, 9. So it should work.

**Comment by kevinsegal** [comment]
I'll keep debugging.  This wouldnt have anything to do with the new ES6 syntax would it?  I rewrote my service files per the new spec I saw in the changelog, does moleculer-runner have any bugs running service files written with ES6?

**Comment by icebob** [comment]
Please reopen if you have addition info about this issue

**Comment by olivinesguerra** [comment]
any update?
