### ISSUE TITLE
Moleculer runner - Environnement variable - middleware

### ISSUE THREAD

**Issue by molobala** [moleculerjs/moleculer#215]
When using environnement variable in case we use moleculer runner, how to register ours middlewares ?

**Comment by icebob** [comment]
You can't register middlewares via environment variables. You need to define them in `moleculer.config.js`.

**Comment by molobala** [comment]
So in production , we need both `moleculer.config.js` and .env file for environnement variable and middlewares

Thank you !

**Comment by icebob** [comment]
Yes, I set `moleculer.config.js` values for development and overwrite some values from env vars in production.
