### ISSUE TITLE
action params validation

### ISSUE THREAD

**Issue by molobala** [moleculerjs/moleculer#216]
I'm getting this error when I add pattern property on my action params:   
`schema.pattern.test is not a function `  
Here my params strcture  
```js
reateDocument: {
      auth: 'required',
      params: {
        name: {
          type: "string",
          pattern: documentNameReg; /// a regexp like /reg here/
        },
        description: {
          type: "string"
        },
      },
   ....
}
```

**Comment by icebob** [comment]
Turn off `preValidation` in moleculer-web settings.

**Comment by icebob** [comment]
No, `preValidation` will be disabled in the next version because in params you can define custom rules, which is won't work on moleculer-web side, because function is not serializable.
