### ISSUE TITLE
Event groups not working in mixins

### ISSUE THREAD

**Issue by ColonelBundy** [moleculerjs/moleculer#217]
Steps to reproduce:

- Create a mixin,
- Create an event with a group other than the name of the mixin.
- Use mixin in a service.
- Try it with: ```broker.broadcast('event-name'), {}, 'group-name')```

**Comment by icebob** [comment]
Fixed in https://github.com/moleculerjs/moleculer/commit/d924b97a61ccacfe657097494dcf310fa6f100da
Please try it with `npm i moleculerjs/moleculer`
