### ISSUE TITLE
[Proposal] broker.broadcast update and broker.send

### ISSUE THREAD

**Issue by ColonelBundy** [moleculerjs/moleculer#221]
### broker.broadcast
A proposal to modify ```broker.broadcast``` method, to allow a node to broadcast to all nodes except itself. This can be done adding a key called ```skipSelf```

Example: (thanks, @quex46)

```js
broker.broadcast('event', {}, {
   skipSelf: true // false by default
   group: ['one', 'two']
});
```

### broker.send

To further extend the functionality of the event system, how about a ```broker.send``` as well? it would take an event name, data, nodeID and optionally a group. This would allow a node to reply to another node, reasoning by keeping the group would be to better support mixin isolation.

Example:

```js
broker.send('event', {}, {
	id: 'node-123', // Node to send to.
	group: ['one', 'two'] // (optional)
});
```

**UPDATED**
```js
broker.broadcast("user.created", { user }, {
   nodeID: "node-123",
   groups: ["user", "purchase"]
});
```

Thoughts?

**Comment by icebob** [comment]
Good idea, but maybe need a better method name. For me the `publish` doesn't mean this logic.

**Comment by ColonelBundy** [comment]
@icebob How about ```broker.emit``` instead?

**Comment by quex46** [comment]
```broker.emit``` is already in use. Maybe just extend options for ```broker.broadcast``` by adding something like this:
```
broker.broadcast("user.created", { user }, {
   services: ["user", "purchase"],
   skipSelf: true
});
```

**Comment by icebob** [comment]
@quex46 Good idea

**Comment by ColonelBundy** [comment]
@quex46 right, forgot about that one. ```skipSelf``` sounds good!

**Comment by icebob** [comment]
Is there somebody to implement it?

**Comment by icebob** [comment]
@ColonelBundy for 2nd proposal: I think no need a new function. It can be merged to the first proposal.
E.g:
broker.broadcast("user.created", { user }, {
   nodeID: "node-123",
   groups: ["user", "purchase"],
   skipSelf: true
});

**Comment by zllovesuki** [comment]
I was under the impression that current code already skips the current node: https://github.com/moleculerjs/moleculer/blob/f6ac90bcd128ded3bacd8220e1ddae97b0e0ce6e/src/service-broker.js#L1288

**Comment by icebob** [comment]
@zllovesuki the mentioned code is applied to only remote nodes. It gathers the ID of remote nodes, so skips the local nodeID and [here](https://github.com/moleculerjs/moleculer/blob/f6ac90bcd128ded3bacd8220e1ddae97b0e0ce6e/src/service-broker.js#L1296) sends to all local nodes.
