### ISSUE TITLE
RedisCacher option "prefix" has no effect

### ISSUE THREAD

**Issue by quex46** [moleculerjs/moleculer#223]
According to the [docs](https://moleculer.services/0.12/docs/cachers.html#Redis-cacher), the plugin can accept "prefix" option, but probably it has no effect. If we look at code [here](https://github.com/moleculerjs/moleculer/blob/master/src/cachers/base.js#L45) we can see `this.prefix` is statically set to "MOL-".

How to implement:

```js
// moleculer.config.js

module.exports = {
  logger:      console,
  transporter: 'TCP',
  cacher:    {
    type:    'Redis',
    options: {
      prefix:  'cache',
      ttl:     30,
      monitor: false,
      redis:   {
        host:     REDIS_HOST,
        port:     REDIS_PORT,
        password: REDIS_PASSWORD,
      },
    },
  },
};
```
expected keys to be prefixed with "cache", but still "MOL-" anyway.

**Comment by icebob** [comment]
Thanks, I will check it.
