### ISSUE TITLE
Help with NATS connectivity and multiple instances of same service

### ISSUE THREAD

**Issue by parveshh** [moleculerjs/moleculer#226]
i am trying to create  a simple demo of moleculer services  to present at my workplace, i am facing 2 issues.

we use kubernetes for deployments hence each service we deploy has multiple instances , when i am trying to add multiple instances of same service connected through NATS Server, each call gets broadcasted to all instances and is executed on all services, is it possible to only execute a service call once even if multiple instances of same service are connected.

second issue i am facing is with NATS connectivity, if i provide multiple NATS server addresses sometimes not all services connect to the first available NATS server, its random, if i start let's say 5 services some get connect to first server and others to the second server due to which not all services are available through API Gateway endpoint, am i using the wrong transporter or is there any way to stop this random nature?

**Comment by tinchoz49** [comment]
Hi @parveshh how are you? 
> we use kubernetes for deployments hence each service we deploy has multiple instances , when i am trying to add multiple instances of same service connected through NATS Server, each call gets broadcasted to all instances and is executed on all services, is it possible to only execute a service call once even if multiple instances of same service are connected.

If you are using `ctx.call` it's already balanced, only one service of the same type is going to receive the request.

What is your moleculer-config?

**Comment by parveshh** [comment]
Hi @tinchoz49  i am very new to moleculer and is just playing around, i created 1 service and 1 api gateway, here is my service:

`import { ServiceBroker } from "moleculer";
const urls = ["nats://localhost:4222", "nats://localhost:4223"];

const broker = new ServiceBroker({
    logger: console,
    transporter: {
        type: "NATS",
        urls: urls
    }
});
const service = broker.createService({
    name: "message",

    actions: {
        print() {
           
            return "Message from message.print";
        }
    }
});

broker.start();`

here is my gateway:
`import { ServiceBroker } from "moleculer";
import * as apiService from "moleculer-web";
const urls = ["nats://localhost:4222", "nats://localhost:4223"];

const broker = new ServiceBroker({
    logger: console,
    transporter: {
        type: "NATS",
        urls: urls
    }
});
const service = broker.createService({
    name: "api",
    mixins: [apiService],
    settings: {
        port: 8080,
        routes: [{
            path: "/api",
            aliases: {
                "message": "message.print"
            }
        }],
    }
});

broker.start();`

what essentially i am doing is running multiple instances of my service and 1 instance of gateway service, could you please advise what is the best way to achieve load balancing among services,
Thanks

**Comment by parveshh** [comment]
it seems that the randomise nature of nats is sorted out using noRandomize property like this:

```javascript
const broker = new ServiceBroker({
    logger: console,
    transporter: {
        type: "NATS",
        urls: urls,
        noRandomize: true
    }
});
```

i am still testing this but initial testing seems to be always connecting to first available NATS server, i am still not sure about the balancing of services

**Comment by tinchoz49** [comment]
What you are doing it's ok, also if you want you can't initialize many gateways behind a reverse proxy like traefik.

about nats: the connection process is something delegated to the node-nats module, I tested what you said and is true, on disconnect, it keeps trying to connect only to the first server. But as I said that is something related with the node-nats module.

On the other hand, I can't reproduce your problem with the balancing request, I thought that maybe it was something related with the nats clustering but I did some test with two clusters and everything works ok.

**Comment by parveshh** [comment]
@tinchoz49  to reproduce, if you run multiple instances of service:

```typescript
import { ServiceBroker } from "moleculer";
const urls = ["nats://localhost:4222", "nats://localhost:4223"];

const broker = new ServiceBroker({
    logger: console,
    transporter: {
        type: "NATS",
        urls: urls
    }
});
const service = broker.createService({
    name: "message",

    actions: {
        print() {
           console.log("message.print called");
            return "Message from message.print";
        }
    }
});

broker.start();

```
i have put a console log in print action, if you fire up multiple terminals and run the service from each terminal you will see when you call the service via api gateway , each terminal will have the message printed, i tried the same with a database call as well and i can see multiple records in database for a single call

**Comment by parveshh** [comment]
found the issue with load balancing, all my nodes had same name which was causing it to call all instances at once.

i am closing this for now

**Comment by tinchoz49** [comment]
ahh great, so it was a nodeID problem, I have a similar issue scaling multiple services with docker compose

**Comment by parveshh** [comment]
@tinchoz49  thanks for your time mate
