### ISSUE TITLE
request muleculerjs + mongoose boilerplate

### ISSUE THREAD

**Issue by Khayrabadi** [moleculerjs/moleculer#227]
This might be usefull to have a boilerplate on the framework. For see some examples: browse [here](http://www.boilrplate.com/language/nodejs)

[this](https://github.com/icebob/nodejs-microservices-boilerplate) one need some attention

**Comment by icebob** [comment]
There is a boilerplate [template project.](https://moleculer.services/0.12/docs/usage.html#Create-a-Moleculer-project)
Or you can use the [realworld app](https://github.com/moleculerjs/moleculer-examples/tree/master/conduit#readme)
