### ISSUE TITLE
[Proposal] moleculer-runner loadServices with custom file mask

### ISSUE THREAD

**Issue by davidfrtala** [moleculerjs/moleculer#234]
Recently, Moleculer v0.12 brought new filemask `**/*.service.js` into loading services, which fortunately led to structure our services into subdirectories.

I'm using typescript in my project, and my `*.ts` files lies together with their compiled files. Recently, I was trying to use `ts-node` execution environment for development purposes. My idea is to compile typescript sourcefiles into separate `/dist` directory and git only .ts sourcefiles. So far, this is quite simple.

The problem is, when I want to attach typescript to moleculer-runner. I'd like to go like this (development mode)
```
node -r ts-node/register --inspect=0.0.0.0:9229 node_modules/moleculer/bin/moleculer-runner --hot --repl services
```
Here is `loadServices` function, which takes an argument filemask. 
https://github.com/moleculerjs/moleculer/blob/ba1fdcb166bee52bc93754135a607cab80509dd3/src/service-broker.js#L505
And here is the function call in `moleculer-runner.js`
https://github.com/moleculerjs/moleculer/blob/ba1fdcb166bee52bc93754135a607cab80509dd3/bin/moleculer-runner.js#L241

I would like to somehow pass the custom filemask to this call. 

We have runner constants like `SERVICES`, `SERVICEDIR`, etc. If I could pass my custom filemask (lets say `SERVICESMASK`) I can pass a mask like this `**/*.services.ts` and the moleculer-runner with typescript registered would work perfectly!

**Comment by icebob** [comment]
Good idea!

I think enough for us if there is a new `--mask **/*.service.ts` CLI option. What do you think?

_I think no need env var for the mask because it won't change when you run in production than `SERVICES` or `SERVICEDIR`._

**Comment by davidfrtala** [comment]
Yes, thats a good solution. Do you think it can be implemented in the next release?

**Comment by icebob** [comment]
Yes, would be good a PR if you can ;)

**Comment by icebob** [comment]
@davidfrtala Are you working on it? If not, I can start it.

**Comment by davidfrtala** [comment]
Yes, I will be working on it this weekend

**Comment by icebob** [comment]
I have changed other things in Runner, so I have implemented it as well, sorry :)
