### ISSUE TITLE
Event payload validation

### ISSUE THREAD

**Issue by zhaoyao91** [moleculerjs/moleculer#241]
How about supporting validation for event payload?

**Comment by icebob** [comment]
It is not supported, because you can't apply middlewares to events.

**Comment by zhaoyao91** [comment]
yeah, I know it is not supported, but I hope it would be supported~

**Comment by zllovesuki** [comment]
`event` at this moment for moleculer is "fire-and-forget", thus I don't think it's a necessity to validate the payload. It would matter if we do decide to implement event sourcing.

**Comment by zhaoyao91** [comment]
No, I didn't mean validating payload in sender, I mean validate received payload in event handler, thus it could reject this event handling before the handler's main logic if data is not as expected.

**Comment by icebob** [comment]
It won't be implemented, because you can check it in your event handler.
