### ISSUE TITLE
No default logger

### ISSUE THREAD

**Issue by zhaoyao91** [moleculerjs/moleculer#242]
When I created broker manually in my test file, I didn't see any logs. After some tryings I found there isn't any default logger when creating broker without moleculer-runner, so I have to set

```
new Broker({logger: console})
```

This is not straightforward for new users.

**Comment by zllovesuki** [comment]
The docs does mention `logger` property: https://moleculer.services/0.12/docs/broker.html

@icebob is it the default to "silent"?

**Comment by icebob** [comment]
Yes, no logger is the default. Maybe I will change it in the next 0.13 version.
