### ISSUE TITLE
moleculer-runner --hot does not watch files required by service file

### ISSUE THREAD

**Issue by zhaoyao91** [moleculerjs/moleculer#245]
say, in development, serviceA require moduleA. if serviceA changed, the runner reload. but if moduleA changed, the runner does not reload.

**Comment by icebob** [comment]
It's true. It doesn't resolve the full dependency of services. It can only watch the service file.

**Comment by zhaoyao91** [comment]
well, but it's not quit useful. for well modularized app, little code is written in service file

**Comment by icebob** [comment]
PR welcome

**Comment by tavurth** [comment]
Why is this issue closed? 

Seems like this is something which should stay open until the issue is resolved. 

Currently I have to run something like this in my project to get a hot-restart model:
```javascript
"scripts": {
    "dev": "nodemon services --exec 'moleculer-runner services'"
}
```

**Comment by icebob** [comment]
Because 0.13 doesn't & won't support it. 0.14 will.

**Comment by tavurth** [comment]
Oh I see, where can I see a list of issues for 0.14?

**Comment by icebob** [comment]
Here: https://github.com/moleculerjs/moleculer/blob/next/CHANGELOG.md
