### ISSUE TITLE
broker.stop() bug

### ISSUE THREAD

**Issue by xuming314** [moleculerjs/moleculer#248]
c.service.js
==
```js
@Service({name:'c', constructOverride:false})
class PulserService extends BaseSchema {
  broker:ServiceBroker;
  @Action() stop() { this.broker.stop(); }
  created() { console.log('---created---'); }
  started() { console.log('---started---'); }
  stoped() { console.log('---stoped---'); }
}
```

step 1:
==
A cmd $: moleculer connect nats://localhost:4222 --id=A
B cmd $: moleculer connect nats://localhost:4222 --id=B
C cmd $: moleculer connect nats://localhost:4222 --id=C
C mol $: load c.service.js 
```
'C' service is registered.
---created---
>> Loaded successfully!
---started---
```

step 2:
==
A mol $: nodes
```
╔═════════╗
║ Node ID ║
╟─────────╢
║ A (*)   ║
║ B       ║
║ C       ║
╚═════════╝
```
B mol $: nodes
```
╔═════════╗
║ Node ID ║
╟─────────╢
║ A       ║
║ B (*)   ║
║ C       ║
╚═════════╝
```
C mol $: nodes
```
╔═════════╗
║ Node ID ║
╟─────────╢
║ A       ║
║ B       ║
║ C (*)   ║
╚═════════╝
```

step 3:
==
A mol $: call c.stop 
```
  ERROR: Request is rejected when call 'c.stop' action on 'C' node.
  RequestRejected: Request is rejected when call 'c.stop' action on 'C' node.
```
A mol $: nodes  
```
╔═════════╗
║ Node ID ║
╟─────────╢
║ A (*)   ║
║ B       ║
╚═════════╝
```

B mol $: nodes 
```
╔═════════╗
║ Node ID ║
╟─────────╢
║ A       ║
║ B(*)    ║
╚═════════╝
```

C mol $: nodes 
```
╔═════════╗
║ Node ID ║
╟─────────╢
║ A       ║
║ B       ║
║ C (*)   ║  [C node not removed!!]
╚═════════╝
```

step 4:
==
C mol $: load c.service.js 
```
---created--- 
```
**[no ---started--- log print!!]**

**Comment by icebob** [comment]
The first issue is fixed, that C is not removed after broker.stop. 
But second is not an issue, because you can't load service after the broker is stopped. The problem is that REPL mode didn't exit when the broker is stopped. But I think it is not a production use case.
