### ISSUE TITLE
The client can be separated from the service side

### ISSUE THREAD

**Issue by wanglong167** [moleculerjs/moleculer#249]
The client can be separated from the service side

**Comment by icebob** [comment]
What do you mean?

**Comment by zllovesuki** [comment]
I think he meant that if a microservice is strictly a "consumer" (as in they only do `broker.call`) instead of providing services.

**Comment by quex46** [comment]
Would be useful, for example, for transparent migration from monolit app to microservices.

But does it worth? If I understand correctly, you can just create `ServiceBroker` instance with no services attached to it and use it as client (after calling `.start()` method on it to ensure transporter is connected).

**Comment by zllovesuki** [comment]
@quex46 it adds overhead. For example, other nodes can care less if the client dies. However, with current architecture, heartbeats and etc will still be sent, which adds overhead.
