### ISSUE TITLE
type of Promise field should probably be `typeof Bluebird<any>`

### ISSUE THREAD

**Issue by millimoose** [moleculerjs/moleculer#251]
https://github.com/moleculerjs/moleculer/blob/60ddf4736aa29a79a30199c9e7cf5a90d40c120d/index.d.ts#L135

Trying to use this field in my code with `return new this.Promise(...)` makes TS complain about there not being a constructor in the value.

**Comment by rmccallum81** [comment]
Just did a check on it and the correct type would be `Promise: typeof Bluebird;`, without the `<any>` as that causes a type error. Your new code would look like `return new this.Promise<any>(...)`. The generic type is optional but this allows the output to be typed.
