### ISSUE TITLE
ISTIO and Moleculer

### ISSUE THREAD

**Issue by ramsundhar20** [moleculerjs/moleculer#257]
Great work, getting started with Moleculer. I feel ISTIO(https://istio.io/docs/concepts/what-is-istio/overview.html) project also address some efforts for similar infrastructure.

Hoping to have a discussion and come up with possible roadmaps for Moleculer

**Comment by soluty** [comment]
istio is a service mesh framework  and this is a node microservice framework,  they has some similar function like service registry but they are not same at all

**Comment by ramsundhar20** [comment]
I do understand that ISTIO tries to handle it at a lower level of
abstraction. According to my understanding, moleculerjs handles more in the
application side where istio concentrates on the infrastructure side.
