### ISSUE TITLE
CPU utilization-based Strategy should use process usage instead of os usage?

### ISSUE THREAD

**Issue by Wallacy** [moleculerjs/moleculer#259]
Hello,

Looking at  moleculer/src/cpu-usage.js, appear to me that current strategy for CPU is tied to entire machine cpu usage.

This is the best way to do that? Because if we run multiples services on the same OS (if inside of the docker probably will be fine) all the services will show the same CPU usage, ever only one is actually processing data. So, one microservice busy doing something has the same probability to receive the call as the one that is idle.

I try to change the implementation to use process.cpuUsage([previousValue]) ( https://nodejs.org/api/process.html#process_process_cpuusage_previousvalue ) but i did not get a good accuracy trying to math the correct CPU %.

Using "pidusage" (https://github.com/soyuka/pidusage) i get good results on Linux, but not a good one on Windows. Note that the "pidusage" get the correct CPU usage for the process per core, so for 100% on a 4 core CPU is 25% of the system, (and 100% of one core of course). But this is fine because NodeJs is one core application anyway, so the load balancer will choose correctly.

PM2 appear to get the correct number too.

Any thoughts?

**Comment by icebob** [comment]
Hello,

I deliberately did so. Because for example, there is an installed DB server which uses 99% of OS, and you have 3 running moleculer node with 0% PID cpu usage, it is not good idea to send requests to them.

**Comment by icebob** [comment]
NodeJS is not a single thread app, javascript can run only in a single thread. So if you make file IO, network IO, or something else which implemented natively as async, it will be running on multiple threads. And I think, the most of use cases, you will use file or DB accessing or networking in your services and not just add two numbers.

Btw, in the next version, I will expose the `getCpuUsage` from registry to the broker and you will able to override with your custom implementation like `broker.getCpuUsage = function() {....}`. And `CpuUsageStrategy` will use these values.

**Comment by Wallacy** [comment]
>  So if you make file IO, network IO, or something else which implemented natively as async, it will be running on multiple threads

Yes, this is true for every language btw.

> And I think, the most of use cases, you will use file or DB accessing or networking in your services and not just add two numbers.

Without a survey this is only a guess. My "guess" was based on docker world. The golden rule is do not put more than one domain in the same context.

> Btw, in the next version, I will expose the getCpuUsage from registry to the broker and you will able to override with your custom implementation like broker.getCpuUsage = function() {....}. And CpuUsageStrategy will use these values.

Thanks. This can solve the problem.

**Comment by icebob** [comment]
In v0.13 with new middlewares you can change it with a similar middleware: 

```js
// middleware.js
module.exports = function ProcessCpuUsageMiddleware() {
    return {
        created(broker) {
            broker.getCpuUsage = function() {
                const avg = 5.0; // Get process CPU usages somehow
                return broker.Promise.resolve({ avg });
            }
        }
    }
};

// broker options
const broker = new ServiceBroker({
    middlewares: [ProcessCpuUsageMiddleware()]
});
```

**Comment by Wallacy** [comment]
Thanks, I will try!
