### ISSUE TITLE
dynamically registered services do not update after broker reconnect

### ISSUE THREAD

**Issue by fugufish** [moleculerjs/moleculer#262]
When a separate broker reconnects, dynamically registered services (any service that calls .createService after moleculer starts) are not updated because the sequence is out of sync.

I traced the issue here:

https://github.com/moleculerjs/moleculer/commit/fbb99106150d4b41798b6d9550c547f83e9f2aa6#diff-bb81619136bf2c8b0778ee961b076a8cR184

Basically, the sequence # sent in the payload is less than the sequence # stored in the remote broker, ensuring that newly created services are not added to the registry.

**Comment by icebob** [comment]
Fixed in https://github.com/moleculerjs/moleculer/commit/080437d40b8c05d4463044d1eef667b75b4bf2b1

**Comment by icebob** [comment]
Released in https://github.com/moleculerjs/moleculer/releases/tag/v0.12.4
