### ISSUE TITLE
transporter for AWS SQS

### ISSUE THREAD

**Issue by digitalysin** [moleculerjs/moleculer#268]
is it possible to implement transporter for AWS SQS ?

**Comment by icebob** [comment]
Yes, if somebody writes it.

**Comment by sanketCactus** [comment]
@icebob so is this available or we are still waiting for a contributor ?

Thank you.

**Comment by icebob** [comment]
I don't know that somebody did it.

**Comment by intech** [comment]
[Amazon SNS](https://aws.amazon.com/sns/) is better for transportation than [Amazon SQS](https://aws.amazon.com/sqs/)
