### ISSUE TITLE
Log: AMQP connection don't close gracefully

### ISSUE THREAD

**Issue by xynon** [moleculerjs/moleculer#270]
Just a wrong log entry.

I'm calling `broker.stop()` 
 - that's calling `broker.transit.disconnect()` in [service-broker.js#L393](https://github.com/moleculerjs/moleculer/blob/master/src/service-broker.js#L393)
 - that's sending `transit.sendDisconnectPacket()` and after
 - that's is calling `transit.tx.disconnect()` in [transit.js#L132-L136](https://github.com/moleculerjs/moleculer/blob/master/src/transit.js#L132-L136)

Here is my issue: After the `transit.tx.disconnect()` `transit.disconnecting` will be set to `false` but closing of connection is not finished. So I got the error `AMQP connection is closed.`.

If I look directly in the transporter [amqp.js#L188](https://github.com/moleculerjs/moleculer/blob/master/src/transporters/amqp.js#L188) there is calling `tx.connection.close()` in a Promise so there should waiting before `transit.disconnecting` going back to `false` but the close handling in [amqp.js#L111](https://github.com/moleculerjs/moleculer/blob/master/src/transporters/amqp.js#L111) is just an event, or?
So they don't wait.
In fact when I debug on this close handler  `transit.disconnecting` is already set to false and so I got this error.

The channel handling has the same problem but that is apparently fast enough - there is the `transit.disconnecting` `true` yet.

All together it's not a big problem because it's just the logging who is looking strange:
```
2018-05-16T12:27:48.245Z - info: AMQP channel is closed gracefully.
2018-05-16T12:27:48.247Z - info: ServiceBroker is stopped successfully. Good bye.
2018-05-16T12:27:48.246Z - error: AMQP connection is closed.
```

**Comment by xynon** [comment]
A proposal for solution an internal `disconnection`-variable of the (amqp)transporter which is set from `transit.disconnection` on the promise of `tx.disconect()`.
 So you can set them in the right order without changing any other behaviour.
 
[disconnect](https://github.com/moleculerjs/moleculer/blob/master/src/transporters/amqp.js#L184-L196)
```node
disconnect() {
  if (this.connection && this.channel && this.bindings) {
    return Promise.all(this.bindings.map(binding => this.channel.unbindQueue(...binding)))
      .then(() => {
        this.channelDisconnecting = this.transit.disconnecting;
        this.connectionDisconnecting = this.transit.disconnecting;
      })
      .then(() => this.channel.close())
      .then(() => this.connection.close())
      .then(() => {
        ...
```

[channel close](https://github.com/moleculerjs/moleculer/blob/master/src/transporters/amqp.js#L137-L145)
```node
.on("close", () => {
  this.connected = false;
  this.channel = null;
  reject();
  if (!this.channelDisconnecting)
    this.logger.warn("AMQP channel is closed.");
  else
    this.logger.info("AMQP channel is closed gracefully.");
  this.channelDisconnecting = false;
})
```

[connection close](https://github.com/moleculerjs/moleculer/blob/master/src/transporters/amqp.js#L137-L145)
```node
.on("close", (err) => {
  this.connected = false;
  reject(err);
  if (!this.connectionDisconnecting)
    this.logger.error("AMQP connection is closed.");
  else
    this.logger.info("AMQP connection is closed gracefully.");
  this.connectionDisconnecting = false;
})
```

**Comment by icebob** [comment]
Nice point. Could you create a fix PR?
