### ISSUE TITLE
Ability to blacklist services to be initialised by moleculer-runner.

### ISSUE THREAD

**Issue by adrianleb** [moleculerjs/moleculer#283]
As of right now one is able to pass as an argument a whitelist of service names for moleculer-runner to load and initialize, or to redefine the filename pattern used by moleculer runner to load and intialize matching service files.
Would be nice to have a way to pass a blacklist of service names as an argument to moleculer-runner so it loads all service files matching the passed in `--mask` argument but ignores blacklisted service names.

**Comment by icebob** [comment]
Hi @adrianleb,
In the next 0.13 version I added matching to service loading.
So besides of current logic, so can use glob patterns to load or skip service.

E.g.: `moleculer-runner --repl services !services/others/**/*.service.js services/mandatory/main.service.js`
Description:
- `services` - legacy mode. Load all services from the `services` folder with `**/*.service.js` file mask
- `!services/others/**/*.service.js` - skipping services from the `services/others` folder and sub-folders.
- `services/mandatory/main.service.js` - load the defined one service

I think it could cover all possibilities.

**Comment by adrianleb** [comment]
Thanks @icebob, can definitely work with that!
