### ISSUE TITLE
typescript show a warning in code: @Action({metrics:{params:true}})

### ISSUE THREAD

**Issue by xuming314** [moleculerjs/moleculer#288]
@Action({metrics:{params:true}}) <== params type show a warning;
in index.d.ts:
``` js
	type MetricsOptions = { params?: "boolean" | "array" | "function", meta?: "boolean" | "array" | "function" };
	interface Action {
		metrics?: MetricsOptions;
	}
```

**Comment by xuming314** [comment]
maybe like this ?
``` js
	type MetricsOptions = { params?: boolean | array | function, meta?: boolean | array | function };
```

**Comment by icebob** [comment]
@rmccallum81 ?

**Comment by rmccallum81** [comment]
Yes that would be correct for the `boolean` type however the array type needs to indicate the type of its values i.e. `Array<string>` and the function should be a signature as there is an expected set of input and outputs for the function. If there are no inputs or outputs it would be `() => void`.

**Comment by icebob** [comment]
@xuming314 Could you create a fix PR?
