### ISSUE TITLE
Please upgrade node-object-hash

### ISSUE THREAD

**Issue by futpib** [moleculerjs/moleculer#290]
They have a bug fix in v1.4.1 SkeLLLa/node-object-hash#11.

I was almost able to submit a trivial PR for this, but presence of both `yarn.lock` and `package-lock.json` in this repo confused me (I'm not sure how to upgrade the dependency properly: either with `yarn` or `npm`).

**Comment by icebob** [comment]
Thanks. Please create a PR. Use the `npm run deps` command and select `node-object-hash` to upgrade and upload the `package.json` and `package-lock.json`. 

>Btw this dependency will be removed in the next 0.13 version.
