### ISSUE TITLE
Authorization between services

### ISSUE THREAD

**Issue by ZeroHackeR** [moleculerjs/moleculer#304]
First of all, Really love the idea and structure of moleculer. Now we are thinking about using it in production. 

From security point of view, we needed to implement “Authorization between Services”. So, what would be the best approaches to achieve this in moleculer?

Eg: let’s say we have a “transferMoney” service and we don’t want it to be accessible by all other services, except a few selected services.

**Comment by icebob** [comment]
It's great! I hope you can use it easily in your project :+1: 

I recommend using middleware for authorization. With is you can check the permission before the real action handler is called. If the caller has no enough permission you can throw an error instead of calling the action handler. I recommend checking the validator middleware code because it does similar things.

Validator middleware code: https://github.com/moleculerjs/moleculer/blob/master/src/validator.js#L43
Docs about middlewares: http://moleculer.services/0.12/docs/broker.html#Middlewares

**Comment by ZeroHackeR** [comment]
@icebob Thanks for your quick response. 

Right now we are using JWT for service to service authorization and we got to do the same or something similar when we switch to moleculer. 

If I understand you correctly, there is no built in functions for service to service authorization/whitelisting. We have to implement ourselves.

**Comment by icebob** [comment]
Yes, there is no built-in authorization between services.

**Comment by ZeroHackeR** [comment]
@icebob noted. I think, I will work on it as a plug-in which would be more useful for a lot of people. 

So, is there a way we can identify the caller service’s name and action?

**Comment by tinchoz49** [comment]
Hi everyone! how are you?

@icebob with the new incoming action hook feature is going to be easier this kind of things right? https://github.com/moleculerjs/moleculer/blob/next/CHANGELOG.md#action-hooks

**Comment by icebob** [comment]
Yes, it's also exactly perfect for this things.
@ZeroHackeR currently you can't detect the caller services. Mainly if you use `broker.call`. Via `ctx.call` you can identify it in caller side (`ctx.service.name`) and you can put it to the `ctx.meta`

**Comment by ZeroHackeR** [comment]
@icebob @tinchoz49 Thank you all for your inputs...

Action Hook & Middleware are a good way to intercept the requests. 
However, they are not secure by default.

Lets continue form the previous example. if we allow requests with "billing" role to access "transferMoney" action, it will prevent from other services calling this action easily. But, as soon as they find out that they can bypass security check by adding "billing" role in their requests, we will be screwed. 

So, I am thinking about Node level verification/authorization before allowing an action to be called. As of now, I am not sure how can I do that with moleculer yet... :P

**Comment by ZeroHackeR** [comment]
@icebob can namespace be used to isolate services? or it also is not secure?

**Comment by tinchoz49** [comment]
> But, as soon as they find out that they can bypass security check by adding "billing" role in their requests, we will be screwed.

If you work with a signed token it doesn't matter if they add the "billing" role, the token signature is not going to pass the validation.

Another option is to encrypt the object with security information (in this case the roles) using something like https://github.com/hueniverse/iron

I understand that it's better having some isolation (doing some services not visible for others) but that approach I think is better in scenarios where you have a strong isolation in different areas, like having a set of services for the frontend and another one for the backend. You can isolate this services, for example, using docker with different networks and connect them only by a secure gateway where actually you can define the rules to expose which actions do you want to be public/private.

**Comment by ghqppio** [comment]
I have create and Identity service which is responsible for authentication and authorization.
Each service has it's own token, which is passed in each request between the services. 
Before processing the request, each endpoint calls the authorization service with the token and the desired action. 

Voila!

Basically, I've applied the same logic as I would process clients requests to the frontend api.

**Comment by katsanva** [comment]
Hey, @ghqppio 
What about overhead and delay with your authorization calls between the services?
