### ISSUE TITLE
Socket.io API gateway service for moleculer

### ISSUE THREAD

**Issue by tiaod** [moleculerjs/moleculer#310]
😄 Hi all! I wrote an API gateway service for the moleculer framework using Socket.io. It can let you call moleculer service by doing:
```javascript
socket.emit('call', 'math.add', { a:1, b: 2 }, function( err, res) {
    // get the result here.
})
```
Not just that, there are more features, please checkout: [moleculer-io](https://github.com/tiaod/moleculer-io)

**Comment by icebob** [comment]
Great job @tiaod!

**Comment by icebob** [comment]
Added to the site: http://moleculer.services/modules.html#gateway
