### ISSUE TITLE
Update Benchmarks

### ISSUE THREAD

**Issue by Wallacy** [moleculerjs/moleculer#319]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Update benchmarks to v0.13
(https://moleculer.services/docs/0.13/benchmark.html) (same results from 0.12)

**Describe alternatives you've considered**
N/A

**Additional context**
Update the benchmark is good to keep tracking of the "cost" of any new implementation. For some projects, performance is not a problem, for others is.

**Comment by icebob** [comment]
Ok, I will update it.

**Comment by icebob** [comment]
Updated
