### ISSUE TITLE
moleculer-runner to support removing and adding services

### ISSUE THREAD

**Issue by amiralibamilo** [moleculerjs/moleculer#327]
**Is your feature request related to a problem? Please describe.**

moleculer-runner doesn't detect and run or stop services that are removed or added.
**Describe the solution you'd like**

moleculer-runner should support stoping services by removing the bluh.service.js and add services if new services are added (a new bluh.service.js)
**Describe alternatives you've considered**

**Additional context**

**Comment by icebob** [comment]
It can be a good feature. PR is welcome.

**Comment by skyFi** [comment]
in progress?

**Comment by mormubis** [comment]
Hey @icebob, I was trying to help with something and realized this feature is already part of `moleculer`.  Should we close this issue?

**Comment by icebob** [comment]
Yeah, it's covered by hot reload middleware. I'm closing...
