### ISSUE TITLE
RabbitMQ with MQTT Plugin manipulates Topic Separator which breaks Moleculer Transport

### ISSUE THREAD

**Issue by nmarus** [moleculerjs/moleculer#344]
**Is your feature request related to a problem? Please describe.**
When using MQTT transport with RabbitMQ and the RabbitMQ MQTT Plugin, all dots get converted to slashes and vice versa. As such, nodes on this transport are not able to see each other as the topics are seen with slashes if published with dots. (see blurb at bottom)

**Describe the solution you'd like**
From what i can discern, MQTT Topic separators are `/` while AMPQ uses `.` for topic separation. If this is indeed part of the MQTT spec, it would be nice if the topic separator was set accordingly. 

**Describe alternatives you've considered**
Switch to AMPQ (not ideal for my scenario),  spin up different MQTT Cluster on a different platform, or fork the RabbitMQ MQTT Plugin (not ideal either).  

**Additional context**
From: https://www.rabbitmq.com/mqtt.html

> Note that MQTT uses slashes ("/") for topic segment separators and AMQP 0-9-1 uses dots. This plugin translates patterns under the hood to bridge the two, for example, cities/london becomes cities.london and vice versa. This has one important limitation: MQTT topics that have dots in them won't work as expected and are to be avoided, the same goes for AMQP 0-9-1 routing keys that contains slahes.

**Comment by nmarus** [comment]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349375

**Comment by icebob** [comment]
Implemented. Will be released in 0.13.2
