### ISSUE TITLE
Moleculer-runner cannot load service with compiled code from es6

### ISSUE THREAD

**Issue by picosix** [moleculerjs/moleculer#346]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository

## Expected Behavior

- I wrote code on es6 and beyond
- I compiled it and load by moleculer-runner
- It can load all services successful

## Current Behavior

- Moleculer-runner throw a exeception

"ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema."

## Failure Information

The reason is at this line
https://github.com/moleculerjs/moleculer/blob/master/src/service-broker.js#L533
The `schema` will be

```js
{
 default: {
  name: 'service-name',
 ...
}
}
``` 

### Steps to Reproduce

1. Write some code on es6
2. Compile it by babel-cli
3. Load all services by `moleculer-runner`

### Reproduce code snippet

user.service.js
```js
export default {
 name: 'user',
 action: {
  login: async () => 'success'
 }
}
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.1
* NodeJS version: 8.11.1
* Operating System: macOS

### Failure Logs
```
yarn run v1.5.1
$ NODE_ENV=production moleculer-runner -E .env.production
[2018-07-28T03:17:32.865Z] INFO  yaorut2s-macbook-pro.local-2644/BROKER: Moleculer v0.13.1 is starting...
[2018-07-28T03:17:32.867Z] INFO  yaorut2s-macbook-pro.local-2644/BROKER: Node ID: yaorut2s-macbook-pro.local-2644
[2018-07-28T03:17:32.867Z] INFO  yaorut2s-macbook-pro.local-2644/BROKER: Namespace: <not defined>
[2018-07-28T03:17:32.867Z] INFO  yaorut2s-macbook-pro.local-2644/REGISTRY: Strategy: RoundRobinStrategy
[2018-07-28T03:17:32.870Z] INFO  yaorut2s-macbook-pro.local-2644/BROKER: Serializer: JSONSerializer
[2018-07-28T03:17:32.871Z] INFO  yaorut2s-macbook-pro.local-2644/BROKER: Transporter: RedisTransporter
[2018-07-28T03:17:32.872Z] INFO  yaorut2s-macbook-pro.local-2644/BROKER: Registered 10 internal middleware(s).
ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c NODE_ENV=production moleculer-runner -E .env.production
Directory: /Users/picosix/Company/crawlers/facebook-graph
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/picosix/Company/crawlers/facebook-graph/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by icebob** [comment]
Duplicated #328

**Comment by picosix** [comment]
Sorry. I was only searched by google. It's my fault

**Comment by icebob** [comment]
No problem.
