### ISSUE TITLE
There should be a means to prevent ServiceBroker from calling process.exit() within stop()

### ISSUE THREAD

**Issue by cameronbraid** [moleculerjs/moleculer#349]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Expected Behavior

When a ServiceBroker is embedded into an existing application it should allow the application to implement the graceful shutdown process.

There should be a means to prevent ServiceBroker from calling process.exit() within the stop() function

## Current Behavior

When ServiceBroker.stop() is called, either by the hosting app, or when stop signals are sent ot the process (SIGTERM etc..) process,exit() is called, crashing my application which is going through a graceful shutdown process

**Comment by cameronbraid** [comment]
I can see that service broker has _closeFn which can be overriden like :

```
      this.broker._closeFn = ()=>{}
```

However, my concern would be that _closeFn is a private function and may change in the future.

**Comment by cameronbraid** [comment]
```broker._closeFn = ()=>{}``` doesn't work since the function is passed as the process kill event handler

Would you accept a PR that adds a new boolean option ```gracefulShutdown``` :+1: 
```
			if (this.options.gracefulShutdown != false) {
				// Graceful exit
				this._closeFn = () => {
					/* istanbul ignore next */
					this.stop()
						.catch(err => this.logger.error(err))
						.then(() => process.exit(0));
				};

				process.setMaxListeners(0);
				process.on("beforeExit", this._closeFn);
				process.on("exit", this._closeFn);
				process.on("SIGINT", this._closeFn);
				process.on("SIGTERM", this._closeFn);
			}
```

**Comment by icebob** [comment]
The `broker.stop` doesn't call `process.exit`. But the `_closeFn` does, because it is triggered by `process.on`. However #336 fixes this issue, so you will able to disable it with new `skipProcessEventRegistration` in the next release.
