### ISSUE TITLE
Moleculer Runner starts an additional service with emtpy configuration

### ISSUE THREAD

**Issue by PetrykowskiM** [moleculerjs/moleculer#353]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository

## Expected Behavior
Starting a service should not start an additional "Ghost Service"

## Current Behavior
I have the following project structure

- root
|_ index.js
|_ package.json

index.js
```
const { ServiceBroker } = require("moleculer");

const broker = new ServiceBroker({
  namespace: "",
  logLevel: "info",
  transporter: "nats"
});

broker.createService({
  name: "firstService",
  version: "1",
  actions: {
    add(ctx) {
      return Number(ctx.params.a) + Number(ctx.params.b);
    }
  }
});
```

package.json
```
{
  "name": "mail-service",
  "version": "1.0.0",
  "description": "A service that deals with sending emails",
  "main": "index.js",
  "private": true,
  "dependencies": {
    "moleculer": "^0.13.1"
  },
  "scripts": {
    "start": "moleculer-runner index.js"
  }
}
```

## Failure Information

`ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema.``

I found out that moleculer tries to start a service without any config when I run `moleculer-runner index.js`

### Steps to Reproduce

1. Copy code 
2. yarn 
3. yarn start

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer-Runner version: 0.13.1
* NodeJS version: 10.7
* Operating System: Macos

### Failure Logs
```
ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema.
```

**Comment by Wallacy** [comment]
This is related to #328 and the problem was correct on #348.

Just wait the 0.13.2 or 0.14.

**Comment by icebob** [comment]
It's a common mistake. If you uses Moleculer Runner, you don't need to start broker in service file. Just create simple service schema files and load them with Runner. 
Similar issue: https://github.com/moleculerjs/moleculer-web/issues/69#issuecomment-409690015
