### ISSUE TITLE
Injecting new config into services during runtime

### ISSUE THREAD

**Issue by PetrykowskiM** [moleculerjs/moleculer#354]
**Is your feature request related to a problem? Please describe.**
I would like to change the routes of the api-service during runtime.

**Describe the solution you'd like**
It would be great to have a service update function that allows me to inject a new config into a service.

**Describe alternatives you've considered**
An alternative would be to write the API service by myself and change the routes according to incoming messages.

**Comment by icebob** [comment]
I think we can create a universal service update function because all services have different logic to apply changes. 
For `moleculer-web` I think it can be easier with a small code.
```js
"use strict";

const ApiGateway = require("moleculer-web");

module.exports = {
    name: "api",
    mixins: [ApiGateway],

    settings: {
        port: process.env.PORT || 3001,

        routes: [{
            path: "/api",
            whitelist: [
                // Access to any actions in all services under "/api" URL
                "**"
            ],
            bodyParsers: {
                json: true
            }
        }]
    },

    events: {
        "api.routes.changed"(payload) {
            this.routes = payload.routes.map(route => this.createRoute(route));
        }
    }
}; 
```
So you can update the routes with `broker.broadcast("api.routes.changed", { routes: [...] })`.
_Please note, it's just a pseudo untested code_

**Comment by PetrykowskiM** [comment]
But this does not solve the problem of actually forwarding and responding to *http* requests.
