### ISSUE TITLE
How do I get the IP / hostname of node from action

### ISSUE THREAD

**Issue by PetrykowskiM** [moleculerjs/moleculer#355]
## Problem
For dispatched actions I would like to be able to find out the corresponding IP of the action's dispatcher.

## Use Case
I would like to handle all incoming API request from one service. With this I only need to expose one certain container type to the public and not all.
This service should be able to delegate certain routes or maybe even all to the regarding microservice. For actual frontends i would like to directly forward the incoming request to the corresponding service. 

The API service should be dynamic. Therefore when a service launches that needs to lets say publish a frontend, it dispatches an action that says: "Hey, i want to expose my frontend `calculator` from route `/calculator`".
To be able to forward the request correctly I need the senders IP / hostname. Is that possible at the moment?

**Comment by icebob** [comment]
Hi,
I don't understand what you need. Could you explain? Are you using moleculer-web or custom gateway?

**Comment by PetrykowskiM** [comment]
Hi,
I currently use neither of those two. I tried to explain it in my use case.

Imagine following services:
ApiService: All incoming Requests are being handled by this service. It's the single entry point
![image](https://user-images.githubusercontent.com/5831420/43825910-3ec9ce30-9af6-11e8-9f80-695d3e1f3258.png)

Service1: Offers a backend that provides some buttons

What I want to do is, that `Service1` subscribes at the API service for certain routes. If I call on of this routes, the `ApiService` is being called, it accepts the request und forwards the incoming http Request to `Service1`.

**Comment by icebob** [comment]
I think that moleculer-web has the same functionality. It is the single entry point, gets requests, transfers data to the services and sends back the results.

**Comment by PetrykowskiM** [comment]
Not exactly. I need to **forward** a request from `ApiService` to `Service1`. This forward is **not** a message but a real http-request.

That means that I want `Service1` to also expose an http server that handles a request. And it gets all his requests from `ApiService`.

If you think that `molecular-web` can do this, can you provide an example on how to do that?

**Comment by icebob** [comment]
In this case all your services should be a http server too. In this case you ApiGateway in all services as a mixin and configure to expose only local actions.
