### ISSUE TITLE
How to get FormData object in request body?

### ISSUE THREAD

**Issue by maitrucquynhq111** [moleculerjs/moleculer#357]
i have a FormData object in front-end (ReactJs) and i add it to body of request
how i can get this object in moleculer back-end.
i try this.ctx.params but it is not work

**Comment by quex46** [comment]
Moleculer service hasn't http server by default. If you want accept http requests, you should mixin your service with http server (create http server in `created` hook, start listen on `started` hook, then handle requests and call appropriate methods of your service).

**Comment by siridho** [comment]
@quex46 hi, I am newbie in nodejs and i still confusing what the should I do to "create http server in `created` hook start listen on `started` hook, then handle requests and call appropriate methods of your service" may I see the example code for the `created` and `started` function, thanks for the help

**Comment by ccampanale** [comment]
@siridho The base `moleculer` framework provides the components to build brokered microservices which can communicate with each other using the broker over a multitude of transports. It's as simple as that. If you want/need to create a service which handles HTTP requests itself (essentially either acting as an API gateway routing requests to the service itself or other services registered on the bus) you may want to look at the [Moleculer-Web](https://moleculer.services/docs/0.13/moleculer-web.html) project. It's a service mixin which will provide the HTTP server setup for you, you simple need to configure it.

You can of course set this up yourself but I personally think that this mixin works great and is highly configurable so you will probably find that it will do exactly what you need.
