### ISSUE TITLE
How to use  Relations / Associations (Joins) in moleculer framework with Mysql.

### ISSUE THREAD

**Issue by nimesh-s** [moleculerjs/moleculer#366]
Hello,

I want to understand how to use sequelize funtionality in Moleculer framework. Actually, I want to carry out some result across the tables using Relations / Associations (Joins) in moleculer framework with Mysql.

I am using three models - users, posts, and comments as below.

/* ############### Users(Model) ###############  */
'use strict'

"use strict";
const Sequelize = require("sequelize");
module.exports = {
    name: "users",
    define: {
      id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.UUIDV4,
        allowNull: false
      },
        name: {
            type: Sequelize.STRING,
            required: false
        },        
        username: {
          type: Sequelize.STRING,
          required: true
        },
        role: {
          type: Sequelize.ENUM,
          values: ['user', 'admin', 'disabled']
    
        },
        created_at: {
          type: Sequelize.DATE,
          allowNull: false
        },
        updated_at:  Sequelize.DATE,
        deleted_at: Sequelize.DATE
    },
    options: {}
};

/* ############### Posts(Model) ###############  */
"use strict";
const Sequelize = require("sequelize");
module.exports = {
    name: "post",
    define: {     
      id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.UUIDV4,
        allowNull: false
      },
      user_id: {
        type: Sequelize.UUID,
        allowNull: false
      },
      content: {
        type: Sequelize.TEXT,
        required: true
      },
      created_at: {
        type: Sequelize.DATE,
        allowNull: false
      },
      updated_at:  Sequelize.DATE,
      deleted_at: Sequelize.DATE
    },
    options: {}
};

/* ############### Comments(Model) ###############  */
"use strict";
const Sequelize = require("sequelize");
module.exports = {
    name: "comments",
    define: {          
      id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.UUIDV4,
        allowNull: false
      },
      post_id: {
        type: Sequelize.UUID,
        allowNull: false
      },
      content: {
        type: Sequelize.TEXT,
        required: true
      },
      commenter_username: {
        type: Sequelize.STRING,
        required: true
      },
      commenter_email: {
        type: Sequelize.STRING,
        required: true
      },
      status: {
        type: Sequelize.ENUM,
        values: ['approved', 'rejected', 'in review']  
      },
      created_at: {
        type: Sequelize.DATE,
        allowNull: false
      },
      updated_at:  Sequelize.DATE,
      deleted_at: Sequelize.DATE
    },
    options: {}
};

I have followed this example
https://lorenstewart.me/2016/09/12/sequelize-table-associations-joins/

**Comment by quex46** [comment]
You should refuse relationship at database layer and split up this schema to 3 independent services (that can even have separate databases).

IMO using Sequelize with Moleculer is a little confusing. Sequelize is good for writing monoapps, when you store all your data in one database and have good abstraction over it. Against Moleculer, where you writing your app as many independent parts.
