### ISSUE TITLE
how to use sequelize ORM with moleculer Framework

### ISSUE THREAD

**Issue by saurabh-n-crest** [moleculerjs/moleculer#369]
I aware about (moleculer-db-adapter-sequelize/
) https://github.com/moleculerjs/moleculer-db/tree/master/packages/moleculer-db-adapter-sequelize

But can anyone explain with good example like how to generate model from DB, How to set migrations and how to bind model with service, is there any good example to use sequelize ORM with moleculer
Framwork. As i m creating medical related application and which is big and contains 500+ tables.

**Comment by pewh** [comment]
Hi @saurabh-n-crest, have you figure out how to set migrations from moleculer-db?
