### ISSUE TITLE
Google Cloud Platform deployment

### ISSUE THREAD

**Issue by piotr-pilis** [moleculerjs/moleculer#372]
Hi, 
I'm testing moleculer for one of our project. I wonder if somebody have deployed it to Google Cloud Platform or other cloud provider? Alternatively to Kubernetes. What are the best practices? Is there a reference?

**Comment by kevinsegal** [comment]
I'm using it on GCP with Kubernetes... found it was an extraordinarily easy deployment process for every new iteration of our api, when deployed using gcp's docker/container store.

**Comment by musicformellons** [comment]
@kevinsegal I am new to both moleculerjs and kubernetes (Google Kubernetes Engine):
1. Does the combination Kubernetes Moleculer 'make sense'?
2. GKE has its own loadbalancers, so how does that fit with moleculerjs having loadbalancers as well?
3. GKE offers a proprietary pub/sub messaging solution. I suppose using that does not make sense, as Moleculer already provides its own messaging, right?

**Comment by wollittech** [comment]
@kevinsegal could you give an example of how you have setup your deployment please? Are you using compose on kubernetes?

I'm unsure of the best approach, especially in regards to splitting / scaling individual services...

**Comment by tobydeh** [comment]
@kevinsegal could you give an example of how you have setup your deployment please? Are you using compose on kubernetes?

I'm unsure of the best approach, especially in regards to splitting / scaling individual services...
