### ISSUE TITLE
Error property 'map' of undefined cpu-usage.js

### ISSUE THREAD

**Issue by yohanyars** [moleculerjs/moleculer#379]
### Context

* Moleculer version: moleculer@^0.13.2
* NodeJS version: v8.9.3
* Operating System: Ubuntu 16.04

### Failure Logs
```
TypeError: Cannot read property 'map' of undefined
    at Timeout.setTimeout [as _onTimeout] (/home/devuser/project/node_modules/moleculer/src/cpu-usage.js:23:28)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by icebob** [comment]
Somebody can reproduce it?

**Comment by yohanyars** [comment]
Sometimes os.cpus() returns undefined.
https://github.com/nodejs/node/issues/19022

**Comment by icebob** [comment]
Thx the info.

**Comment by yohanyars** [comment]
Error are not fixed moleculer@^0.13.3

Try this example:

`
try {
setTimeout(function () {
   a.map(function () {})
}, 5000)

}catch(e) {
   console.log(111); 
}
`

**Comment by icebob** [comment]
@faeron it's true. The outter `try...catch` can't catch the setTimeout callback errors. Could you fix it?

**Comment by faeron** [comment]
Yes. I catch the errors now seperately for each timeout.
