### ISSUE TITLE
TCP transporter IP bug

### ISSUE THREAD

**Issue by 0x39** [moleculerjs/moleculer#380]
I'm testing TCP transporter.
All nodes is docker containers managed by rancher.

Transporter configuration, kind:
```js
nodeID: 'node-id-1',
transporter: {
        type: 'TCP',
        options: {
            udpDiscovery: false,
            useHostname: true, //have tried true/false
            urls: [
               container_hostname:6000/node-id-1,
               ...
            ],
        }
    }
```

Problem is when i upgrade my rancher service, container IP changes, but all moleculer nodes still try to use old IP.

Some logs: [https://gist.github.com/0x39/25bcf691268858155f8efeb210651ce8](https://gist.github.com/0x39/25bcf691268858155f8efeb210651ce8)

![screenshot from 2018-09-23 01 11 32](https://user-images.githubusercontent.com/15102988/45922185-c0fa4380-becd-11e8-8ab9-878c37ad2757.png)

**Comment by zllovesuki** [comment]
As a last resort, you could have an empty moleculer service (with unchanging hostname) which acts an introducer/arbitrator/middle man, then all your other instances _should_ have random hostnames, and use the empty service as the entry point.

**Comment by Wallacy** [comment]
I did not try but using dns.resolve4(hostname[, options], callback) passing a low ttl under options solve the problem? https://nodejs.org/api/dns.html

**Comment by icebob** [comment]
The docs say the `ttl` in option is a boolean. If true, the callback returns the TTL setting. So you can't use it to define TTL for DNS resolving.
