### ISSUE TITLE
AMQP: TypeError: content is not a buffer

### ISSUE THREAD

**Issue by xynon** [moleculerjs/moleculer#384]
## Prerequisites

- [x] I am running the latest version (master, and 0.13.2 - no problem in 0.12.4)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Expected Behavior

AMQP channel create should be work.

## Current Behavior

AMQP failed to create channel.

## Failure Information

Since version 0.13.x or exactly since commit [47d6ad9487e098d7e1b64b045847ca4a5ea08a9b](https://github.com/moleculerjs/moleculer/commit/47d6ad9487e098d7e1b64b045847ca4a5ea08a9b) the AMQP publishing do not work.  
In the version before there is no problem and all works fine.

Maybe the problem is here in [L405](https://github.com/moleculerjs/moleculer/commit/47d6ad9487e098d7e1b64b045847ca4a5ea08a9b#diff-b2879eb0ba697fd1aae416c88481d346L405) - There is a comment 
>  // amqp.node expects data to be a buffer  

Since this change the payload/data is not a buffer anymore and i got the error: `TypeError: content is not a buffer`

### Steps to Reproduce

1. npm install moleculer@0.13.2
2. npm install amqplib
3. install docker image of rabbitmq
4. create a broker on the amqp
5. start the broker

### Reproduce code snippet
I will update this if neccessary

### Context
* Moleculer version: 0.13.x
* NodeJS version:  v10.8
* Operating System: Ubuntu 18.04
* RabbitMQ: 3.7.4

### Failure Logs
```
debug: Connection is failed.
: Send DISCOVER packet to '<all nodes>'
2018-09-26T16:00:39.958Z - error: AMQP failed to create channel.
2018-09-26T16:00:39.959Z - debug:  TypeError: content is not a buffer
    at Connection.C.sendMessage (amqplib/lib/connection.js:540:11)
    at Channel.C.sendMessage (amqplib/lib/channel.js:85:26)
    at Channel.C.publish (amqplib/lib/channel_model.js:158:15)
    at AmqpTransporter.publish (moleculer/src/transporters/amqp.js:427:17)
...
```

**Comment by xynon** [comment]
In a clean setup I can't actually reproduce it - maybe my payload because of the serializer is the problem...
I will be investigate that deeper.

**Comment by xynon** [comment]
Ok, I found my problem: [Json Serializer L36](https://github.com/moleculerjs/moleculer/commit/47d6ad9487e098d7e1b64b045847ca4a5ea08a9b#diff-59a63af8840c5f997abb16515abf5a5fL36)

So it was the correct commit and problem but I was on the wrong place. My json parser returns an string instead of buffer like the old. So that change broke my neck.
Now I can fix this.

Thank you as always for your fast response.

**Comment by icebob** [comment]
Yes, 0.13 was a breaking change because the field types changed to support streaming.

You're welcome.
