### ISSUE TITLE
Unnecessary re-connection attempts when working with multiple servers

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer#387]
I'm working with multiple servers (master-slave) and I came across the following issue:
Assuming I have two broker objects:
```js
GoodBroker = {
        host: 'exist.com',
        protocol: 'mqtts',
        port: 8883
      }
BadBroker = {
        host: 'notExist.com',
        protocol: 'mqtts',
        port: 8883
      }
```

I setup the transporter object like this:
```js
transporter = {
    type: "MQTT",
    options: {
       username: 'username',
       password: 'password',
       servers: [firstBroker, secondBroker]
   }
}
```
Now, what happens is:
1. firstBroker = GoodBroker, secondBroker = BadBroker: Connecting to the first broker as expected
2. firstBroker = BadBroker, secondBroker = GoodBroker: Failed to connect to the first, then successfully connected to the second. So far so good. However at that point it endlessly attempting to connect to the first broker again.

I saw that in src/transit.js there is a a part of code that calls connect again every time it fails. I think this is unnecessary. When I removed it it worked as expected.

It's important to say that I checked to see if maybe that part is important when working with a single broker and I found that from what I can tell it's not. 

I changed the configuration to work with a single broker which was down. When I run the application I got (again, at this point I removed the re-connection):
```js
WARN  - MQTT client is reconnecting...
WARN  - MQTT client is disconnected.
WARN  - MQTT client is reconnecting...
WARN  - MQTT client is disconnected.
WARN  - MQTT client is reconnecting...
// and a lot more
```
Then, I started the broker and it was connected immediately. I think the mqtt module already handles the re-connection mechanism but since I'm new to molecular I wanted to know what you think before I PR.

**Comment by icebob** [comment]
Interesting. Please attach a full log from the start. The reconnecting part is important for all other transporters, so we can't remove it. Would be better to handle this situation in the MQTT transporter code, if it's available.

**Comment by Gadi-Manor** [comment]
INFO  - Moleculer v0.13.2 is starting...
INFO  - Node ID: server-1
INFO  - Namespace: ns
INFO  - Strategy: RoundRobinStrategy
INFO  - Serializer: JSONSerializer
INFO  - Transporter: MqttTransporter
INFO  - Registered 10 internal middleware(s).
INFO  - Connecting to the transporter...
ERROR - MQTT error. connect ECONNREFUSED 34.249.88.38:8883
WARN  - MQTT client is disconnected.
WARN  - Connection is failed. connect ECONNREFUSED 34.249.88.38:8883
WARN  - MQTT client is reconnecting...
INFO  - MQTT client is connected.
INFO  - '$node' service is registered.
INFO  - 'math' service is registered.
**INFO  - ServiceBroker with 2 service(s) is started successfully.**
mol $ INFO  - Reconnecting...
ERROR - MQTT error. connect ECONNREFUSED 34.249.88.38:8883
WARN  - MQTT client is disconnected.
WARN  - Connection is failed. connect ECONNREFUSED 34.249.88.38:8883
WARN  - MQTT client is reconnecting...
WARN  - MQTT client is disconnected.
INFO  - MQTT client is connected.
WARN  - MQTT client is reconnecting...
ERROR - MQTT error. connect ECONNREFUSED 34.249.88.38:8883
WARN  - MQTT client is disconnected.
INFO  - Reconnecting...
WARN  - MQTT client is reconnecting...
INFO  - MQTT client is connected.
WARN  - MQTT client is disconnected.
ERROR - MQTT error. connect ECONNREFUSED 34.249.88.38:8883
WARN  - MQTT client is disconnected.
WARN  - Connection is failed. connect ECONNREFUSED 34.249.88.38:8883
WARN  - MQTT client is reconnecting...


And it goes on and on..
