### ISSUE TITLE
Validator Middleware - No Action Name

### ISSUE THREAD

**Issue by xynon** [moleculerjs/moleculer#395]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I got an ValidationError from the ValidatorMiddleware. 
I can't find (on a easy way) the action which are throw the error.

**Describe the solution you'd like**
Maybe the `Action.name` in the `Error.data` will be really helpful.
A small change here [ValidatorMiddleware](https://github.com/moleculerjs/moleculer/blob/master/src/validator.js#L50) from
```js
return Promise.reject(new ValidationError("Parameters validation error!", null, res));
```
to
```js
res.forEach(function(data) { data.actionName = action.name });
return Promise.reject(new ValidationError("Parameters validation error!", null, res));
```
would be do this job.

**Describe alternatives you've considered**
Alternative a log will be do this job too - but i prefer this information on the error.

**Additional context**
Error before my change above
```js
{ message: 'Parameters validation error! (NodeID: WorkflowService-1)',
  name: 'ValidationError',
  stack: '...',
  code: 422,
  type: 'VALIDATION_ERROR',
  data:
   [ { type: 'number',
       field: 'id',
       message: 'The \'id\' field must be a number!' } ],
  retryable: false,
  nodeID: 'WorkflowService-1',
  ctx: ... }
```
after:
```js
{ message: 'Parameters validation error! (NodeID: WorkflowService-1)',
  name: 'ValidationError',
  stack: '...',
  code: 422,
  type: 'VALIDATION_ERROR',
  data:
   [ { type: 'number',
       field: 'id',
       message: 'The \'id\' field must be a number!',
       actionName: 'WorkflowService.getWorkflow' } ],
  retryable: false,
  nodeID: 'WorkflowService-1',
  ctx: ... }
```

**Comment by icebob** [comment]
The better solution is that the current `data` in ValidationError is wrapped to an Object. E.g.
```js
{
    name: "ValidationError",
    code: 422,
    type: 'VALIDATION_ERROR',
    data: {
        action: "posts.create",
        errors: [ 
            { type: 'number', field: 'id', message: 'The \'id\' field must be a number!' } ]
        ]
    }
}
```
But it cause a breaking change.

**Comment by xynon** [comment]
My proposal were just to evade the breaking changes - but your solution is better.
