### ISSUE TITLE
Restoring unhandled requests

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer#399]
Let's say one of my nodes crashed from any reason and it still had some requests to handle while crashing.
Is there anyway of restoring these requests when it goes back up or route them to a different node? 
Using bulkhead will store requests in a queue but it's saved in-memory so obviously it won't help.

**Comment by icebob** [comment]
The recommended way is that use `requestTimeout` & `retryPolicy`. If a request is timed out, the sender node will call it again on the other node.
