### ISSUE TITLE
Awesome Moleculer repo

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer#405]
Hi guys,

is anyone who would like to create an "awesome" page and maintain it?
In order to collect useful Moleculer services, mixins & middlewares.

**Comment by lucduong** [comment]
@icebob, Just create, I would like to contribute to.

**Comment by AndreMaz** [comment]
Hey guys. What's the status on this? @lucduong is there any repo already?

**Comment by icebob** [comment]
I've just created the repo: https://github.com/moleculerjs/awesome-moleculer

@lucduong I added you to this repo. Thanks in advance!

**Comment by AndreMaz** [comment]
Nice @icebob . I also want to help

**Comment by icebob** [comment]
Thanks @AndreMaz. I've added you, as well.

**Comment by AndreMaz** [comment]
@lucduong the repo is up and running so we just need to fill it :)

**Comment by icebob** [comment]
Thank you @AndreMaz, good job!
