### ISSUE TITLE
Enhanced hot-reload solution

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer#408]
Hi,

I'm working on an enhanced hot-reload function. The current solution watches only the service files. If you use mixins, middlewares or other self-modules in your service, it can't detect changes of these files.

I make a new solution which can detect the module dependency-graph after broker starting and sets watches all dependent files. 
E.g. if you have a database mixin file what is used in many other services and you modify this mixin files, the ServiceBroker will restart all concerned services.

**Example output of the detected dependencies in my project:**
![image](https://user-images.githubusercontent.com/306521/47964949-da4fed00-e040-11e8-9515-7398555bbb90.png)

 I think I can release it in a 0.13 version.

**Comment by caiobessa** [comment]
It will be very good to increase de productivity, good job.  👍 👍
