### ISSUE TITLE
How to identify when the broker is not responding

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer#416]
I'm looking for a way to determined when there is no connection to the broker.
Something like `$broker.stopped` event.

**Comment by Gadi-Manor** [comment]
Basically what I want to achieve is a simple health check of the broker (Not the ServiceBroker instance, the actual broker).
The user will send a REST and will get a response if the broker is working or not.

I thought about implementing a 'ping' action and then the service will send it to itself (or any other instance of it) and if it gets a response it means the broker is up. 
I tried it but I got a response even after I shut down the broker. I guess it's because the action didn't go through the broker because the sending node was the receiving node.

I looked further and saw the field `broker.transit.tx.connected` so for now I'm counting on that. 
Do you think it's enough? Is there a way to force broker.call() to go through the broker?

**Comment by icebob** [comment]
I see.
So there are `$transporter.sconnected` and `$transporter.disconnected` internal events. You can subscribe to it in your service. But the `broker.transit.tx.connected` can be good, but it is an internal property, so it can be changed in the future.

If you set `disableBalancer: true` in broker options, all calls will be transferred via transporter/message broker.

**Comment by Gadi-Manor** [comment]
Thanks!
The `disableBalancer` property is exactly what I was looking for but unfortunately I'm using MQTT which has no built-in balancer. I'll guess I keep using `broker.transit.tx.connected`.
