### ISSUE TITLE
Include Stacktrace in metrics with error information on metrics.trace.span.finish

### ISSUE THREAD

**Issue by sibblegp** [moleculerjs/moleculer#417]
**Is your feature request related to a problem? Please describe.**
Not quite a problem, but we use the metrics functionality to store audits of every service call as required by regulations for our industry and storing more than just the error message would help us comply.

**Describe the solution you'd like**
It would be great if there was an additional field in metrics.trace.span.finish: error.trace

**Describe alternatives you've considered**
I'd be happy with another metrics event that triggered on an error.

**Comment by icebob** [comment]
Implemented in 0.14
