### ISSUE TITLE
Overwriting broker’s deeply nested default options via ENV variables

### ISSUE THREAD

**Issue by drrainlab** [moleculerjs/moleculer#422]
The Moleculer Runner documentation says:

> To overwrite broker’s deeply nested default options, which are not present in moleculer.config.js, via environment variables, use the MOLECULER_ prefix in .env file. For example, to set the cacher prefix to MOL you should declare as MOLECULER_CACHER_OPTIONS_PREFIX=MOL.

But there is a different prefix and parsing logic in moleculer-runner:

```
		const moleculerPrefix = "MOL_";
		Object.keys(process.env)
			.filter(key => key.startsWith(moleculerPrefix))
			.map(key => ({
				key,
				withoutPrefix: key.substr(moleculerPrefix.length)
			}))
			.forEach(variable => {
				const dotted = variable.withoutPrefix
					.split("__")
```

I've tried to use "MOL_" prefix and "__" separator in ENV variables loaded through Docker and it seems to be working fine.

**Comment by icebob** [comment]
Ohh, thanks. Yes, it has been renamed after the PR.

**Comment by icebob** [comment]
Fixed in docs.
