### ISSUE TITLE
Send events even if no service is registered in the Service Registry

### ISSUE THREAD

**Issue by mathiasmoeller** [moleculerjs/moleculer#426]
**Is your feature request related to a problem? Please describe.**
I am building a system of micro services that broadcast events. One of the services will be a Moleculer service.
Even with `disableBalancer: true` Moleculer will only publish events to the transporter (NATS in my case) if another Moleculer service is registered  in the Service Registry of Moleculer. If not no events will be broadcasted.
If you use Moleculer together with other frameworks they will not receive any events unless one of them is a Moleculer service.

**Describe the solution you'd like**
It would be great to have an option that forces Moleculer to send events to the transporter no matter if another service is registered in the Service Registry or not. This is crucial to be able to use Moleculer in an diverse micro service environment.

I created a small project to show the issue:
https://github.com/mathiasmoeller/moleculer-publish-subscribe-demo

**Comment by icebob** [comment]
The problem is here: 
https://github.com/moleculerjs/moleculer/blob/6e76848d932873f492e2dd02cb1b133316deec57/src/service-broker.js#L1080

**Comment by icebob** [comment]
Hi mathias,

The `broker.emit` works just you should add groups always.
E.g.
```js
broker.start().then(() => {
    setInterval(() => {
        broker.emit("test.event", { ddata: "this is test data" }, ["group"]);
    }, 2000);
});


nats.subscribe("MOL.EVENTB.group.test.event", message => {
    broker.logger.info("nodejs-subscriber: Test event received with payload:", message);
});
```

I will fix the `broker.broadcast` too, but I can't do this with `broker.call`. The action calling is very different. The broker always looks up the action definition from registry. And it is not easy to skip this parts.

**Comment by mathiasmoeller** [comment]
Thanks! I will try this approach ASAP.

**Comment by mathiasmoeller** [comment]
It seems to work! Thanks a lot. Should I leave my demo project public so you can use it to test the `broker.broadcast` issue?

**Comment by icebob** [comment]
Not need it. I've created a simple dev example to demonstrate it: https://github.com/moleculerjs/moleculer/blob/fix-426/dev/no-balancer.js
