### ISSUE TITLE
Create an event between applyMixins and registerService

### ISSUE THREAD

**Issue by flaviocordova** [moleculerjs/moleculer#436]
When a service using Mixins is created, the broker applies all the Mixins in the scheme, then registers the new service and only then call `created` method on that service.

The idea here is to create a new event so mixins could modify the scheme before it's registered. It could allow some interesting features like injecting actions or dependencies, or even wrapping actions so the mixins could do something before/after its invocation.

**Comment by intech** [comment]
@flaviocordova please, see PR https://github.com/moleculerjs/moleculer/pull/444

**Comment by icebob** [comment]
New middleware hook `serviceCreating` will be available in 0.14.
