### ISSUE TITLE
Two MQTT ServiceBrokers not working together

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer#438]
I'm writing unit tests for my app and in order to simulate real scenario I created inside my test a different `ServiceBroker` and passed to it the same `transporter` as parameter. My goal was to communicate between my 'real' `broker` and my test one. 

The problem was that once the second broker is created I'm getting endless disconnections and reconnections attempts of the `MQTT transporter` and I don't think that at any point the two brokers were up together.

I wasn't sure that what I was attempting to do was even possible so I switched to `TCP` and it worked. 

Is it a bug or I was I doing something wrong?

**Comment by icebob** [comment]
I don't know, because I don't use MQTT transporter. But if MQTT lib uses some global variables or functions, in this case, multiple MQTT client instances can cause problems.

**Comment by icebob** [comment]
Any news about it?

**Comment by Gadi-Manor** [comment]
Hi,
Sorry it took me sometime to answer.

No, I'm afraid there is no news.
