### ISSUE TITLE
this.broker.call in a method doesn't pass context metas

### ISSUE THREAD

**Issue by duongdev** [moleculerjs/moleculer#447]
As the title. How can I call to another service action inside a service method with context metas passed down?

**Comment by duongdev** [comment]
Currently, I have to call by `ctx.call` inside an action. But I want to split the `call` part into another place so that I won't repeat myself.

**Comment by icebob** [comment]
You should pass the `ctx` from action to method as parameter and you can use `ctx.call` inside method. There is no other way.

**Comment by icebob** [comment]
I think it is not available. The service instance is bound to the methods & actions.
