### ISSUE TITLE
Calling actions on a particular Node

### ISSUE THREAD

**Issue by imvinaypatil** [moleculerjs/moleculer#448]
Is there any way to call actions on a particular node from a broker?

> For example, if we have a node with an ID **node-1** and there're other nodes with different IDs but same services. What if I want to trigger the actions of only from **node-1**? 
> something like, ctx.call("user.create@node-1", {..}) should trigger only the node-1 service.

I found this to be somewhat as a workaround #425. 
I wanted this for an IOT use case where edge devices have similar services with different IDs so we can call the individual services.

**Comment by icebob** [comment]
use direct call: https://moleculer.services/docs/0.13/actions.html#Usages
```
broker.call("$node.health", {}, { nodeID: "node-21" })
```

**Comment by imvinaypatil** [comment]
Yes totally suffice my requirement. I don't know how come I lost this in such a concise doc. Thank you for bringing this to my attention.

**Comment by imvinaypatil** [comment]
Yes totally suffice my requirement. I don't know how come I lost this in such a concise doc. Thank you for bringing this to my attention.
