### ISSUE TITLE
A way to mock service methods/actions ?

### ISSUE THREAD

**Issue by johanlelan** [moleculerjs/moleculer#449]
Is there a way to mock/stub a service method or service action ?

My service use the [moleculer/elasticsearch](https://github.com/moleculerjs/moleculer-addons/tree/master/packages/moleculer-elasticsearch) mixin. For my unit tests, I want to mock a response for it. Have you a best practice ? Should I used [sinonJS](https://sinonjs.org) or something like that?

Any help would be appreciated.

**Comment by johanlelan** [comment]
I think I found the solution : jestJS with `jest.fn()`.

**Comment by icebob** [comment]
Yes, `jest.fn()` is great for mocking. By the way, check the moleculer tests, how I use Jest for mocking.

**Comment by ThyDevourer** [comment]
Sorry to revive this issue, but i'm currently struggling to find a way to mock service actions when the action i'm trying to mock is in the same service (eg. this.actions.find), i've already tried something like the following
```
const broker = new ServiceBroker({ logger: false });
const service = broker.createService(testService);

const findHandler = jest.fn(async () => ['hello']);
jest.spyOn(service.actions, 'find').mockImplementationOnce(findHandler);
```

**Comment by icebob** [comment]
Yeah, your solution can work if you call the local action via `this.actions.find`. If you use `ctx.call` you should mock the Context as well, or mock the `broker.call`. _The `ctx.call` calls the `broker.call`._
Example with `jest-when`: https://replit.com/@icebob/moleculer-jest-mock-demo#index.spec.js

![image](https://user-images.githubusercontent.com/306521/210229015-dd906f8a-c7f0-40dc-af54-8bfb52146ae9.png)

Another example in documentation, how to mock the action handler before `createService`: https://moleculer.services/docs/0.14/testing.html#Services
