### ISSUE TITLE
Broken ES6 example in docs. parseServiceSchema doesn't start the service.

### ISSUE THREAD

**Issue by dilame** [moleculerjs/moleculer#451]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

I follow the documentation for ES6 classes
https://moleculer.services/docs/0.13/services.html#ES6-classes

`this.parseServiceSchema` does not start the service. I think the example in documentation is wrong.

## Expected Behavior
The service will start and `started` callback will invoke.

## Current Behavior
The service doesn't start, only `created` callback does invoke.
### Reproduce code snippet
Exactly from documentation

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.5 
* NodeJS version: v10.14.2
* Operating System: Mac OS

**Comment by EmersonBrSouza** [comment]
Try comment this line: ` dependencies: ["auth", "users"],` on documentation code example. I found this solution at this file: [ES6 Classes](https://github.com/moleculerjs/moleculer/blob/master/examples/es6.class.service.js).
