### ISSUE TITLE
Can't use Logger in Typescript

### ISSUE THREAD

**Issue by darky** [moleculerjs/moleculer#453]
## Expected Behavior

`Logger` exported as typescript `interface`, but should be runtime value

## Current Behavior

```typescript
import { BrokerOptions, Logger } from 'moleculer';

const brokerOptions: BrokerOptions = {
  logger: (bindings) => Logger.extend(/* ... */)
  // [ts] 'Logger' only refers to a type, but is being used as a value here. [2693]
}
```

## Failure Information

`[ts] 'Logger' only refers to a type, but is being used as a value here. [2693]`

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.5

**Comment by AndreMaz** [comment]
@darky  https://github.com/moleculerjs/moleculer/pull/452 solves this issue, right? If so, then this issue can be closed.

**Comment by darky** [comment]
Not, it was other problem
