### ISSUE TITLE
Directly use ioredis API

### ISSUE THREAD

**Issue by shawnmcknight** [moleculerjs/moleculer#456]
**Is your feature request related to a problem? Please describe.**
The moleculer caching API functions accessible at `broker.cacher.???()` offer a good baseline of functionality but an API like ioredis offers significantly more.  It's not reasonable (and probably not desirable) for moleculer to expose all of that functionality through its own API, so it would be beneficial to expose the ioredis client directly.

In review of the `RedisCacher` class, it appears that instance member `client` is the ioredis client and any ioredis API functionality could be accessed via `broker.cacher.client.???()` such as:

`const pipeline = ctx.broker.cacher.client.pipeline();`

The concern I have with doing something like this is that it's not documented as an acceptable use anywhere and I'd like to avoid doing something that might break in the future.

**Describe the solution you'd like**
If this is considered acceptable use, I'd like it to be documented as such in the [Redis cacher docs](https://moleculer.services/docs/0.13/caching.html#Redis-cacher).  It would probably also be sensible to document it with the jsdocs in the [RedisCacher class](https://github.com/moleculerjs/moleculer/blob/master/src/cachers/redis.js).

**Describe alternatives you've considered**
Another alternative I considered was exposing some limited additional functionality through the `RedisCacher` class.  Things I think would be immediately useful are [ioredis pipelines](https://github.com/luin/ioredis#pipelining) and use of [Redis MGET](https://redis.io/commands/mget) because of their ability to batch requests and improve performance significantly.  However, this seems like a slippery slope since Redis has well over 100 commands and exposing them one-by-one whenever a valid use case arises seems like a poor solution.

The other alternative I considered was to simply use moleculer's caching for the scenarios where it works perfectly out of the box for me, and to interact directly with the ioredis api in the scenarios where I need to do something different.  The concern I had with that approach was I'd end up making multiple client instances and connections to do so, and this seemed like a poor solution as well.

**Additional context**
I'm happy to work up a PR to change the documentation if you agree that using `broker.cacher.client` is an acceptable use of the moleculer caching API.

If there is another approach that you think would be better for the package I could probably work on a PR for that as well, but would be interested in hearing your thoughts.

Thank you!

**Comment by icebob** [comment]
You can use the `this.broker.cacher.client` to reach `ioredis` client, I don't plan to change it. Would be good if you create a PR to document this. Thanks in advance

**Comment by shawnmcknight** [comment]
Excellent!  I have created PRs #459 and moleculerjs/site#58 to document this usage.  Let me know if you have any questions or concerns and I will address them.  Thank you!

**Comment by icebob** [comment]
Cool, I've merged them. Thank you for your help, I really appreciate it!
