### ISSUE TITLE
How to set environment variables to a service?

### ISSUE THREAD

**Issue by ambrous** [moleculerjs/moleculer#458]
I have a service that looks almost like this example https://github.com/moleculerjs/moleculer/blob/master/examples/client-server/server.js

That is I run my script just by `node worker.js`. In that case, as I understand, including of moleculer.config.js does not work, does it?

I would like to set some enviroment variables that can be changed on production and that are used in my moleculer service and can be used within my service by `this.settings.someEnvVar`.

Is there a way to do this? Or maybe I have to use a config manager?

Thanks in advance for help!

**Comment by ambrous** [comment]
Hi @tinchoz49!

Thanks for you answer!

How should I run the moleculer-runner if all my code is in worker.js?

I have tried run `moleculer-runner worker.js`, but I recieve an error:

**Service name can't be empty! Maybe it is not a valid Service schema. { ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema.**

I don't see such example in the documentation, so I guess that I can't run by that way)

**Comment by tinchoz49** [comment]
Ah sorry, you're right. Since you are using your own ServiceBroker you can't use moleculer-runner. In this case, a good option is to use https://github.com/motdotla/dotenv

**Comment by ambrous** [comment]
@tinchoz49

thanks a lot, I will try it!
