### ISSUE TITLE
Redis fail cleaning keys

### ISSUE THREAD

**Issue by Fraccaman** [moleculerjs/moleculer#463]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

## Expected Behavior

There shouldn't be an error thrown in console if there are no keys to clean in redis.

## Current Behavior

An error is thrown says that there was an error with ```scanDel``` function of redis.
I think the problem is that ```scanDel``` don't allow an empty ```args``` argument (since there are no keys to delete as redis is empty).

## Failure Information

``` Redis 'scanDel' error. Pattern: MOL-users.* { ReplyError: ERR wrong number of arguments for 'del' command ... } ```

### Steps to Reproduce

Download ``` https://github.com/moleculerjs/moleculer-examples```.
Change cache from memory to redis.
Make a call to create a new user.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: Latest
* NodeJS version: v9.2.0
* Operating System:

### Failure Logs
``` Redis 'scanDel' error. Pattern: MOL-users.* { ReplyError: ERR wrong number of arguments for 'del' command at parseError (/Users/PATH_TO_PROJECT/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/Users/PATH_TO_PROJECT/node_modules/redis-parser/lib/parser.js:302:14) ```

**Comment by icebob** [comment]
Somebody can create a fix PR for this?

**Comment by fugufish** [comment]
verified that this is fixed in master. fixed in https://github.com/moleculerjs/moleculer/commit/01bd281c420146a5ae4ab45c54d31a17e547f023

**Comment by icebob** [comment]
Thank you @fugufish!
