### ISSUE TITLE
Singleton services

### ISSUE THREAD

**Issue by mizzdev** [moleculerjs/moleculer#471]
Hello there,

I'd like to ask if there are any means of ensuring there can be registered only one instance of a service of the certain type (e.g. name) across all nodes on Moleculer (framework) level? I know that singletons generally introduce a single point of failure hence are considered an antipattern, but my use case implies the *stateful* service and my case is not really algorithmically parallelizable thus cannot (and **must not**) be horizontally scalable. I also know singletons may be run as separate nodes and then managed by DevOps on the infrastructural level.

As I didn't find anything related to this neither in the docs nor in the previously closed issues in this repo, the questions are:

1. Is there any undocumented (or documented, if I missed something) to achieve this from the application level (e.g. with some service/broker configuration) for Moleculer without needing to solve this on the infrastructural level?
2. If there is no such feature present, do you ever have this in future plans?

Thanks in advance!

**Comment by mizzdev** [comment]
Already found a solution - just run your service in a separate node and assign a unique nodeID to it - I'm not sure if Molecular itself checks if there are 2 nodes with the same nodeID running, but you may programmatically check if this nodeID is already registered:

```javascript
let singletonWorkerBroker;

const tempBroker = new ServiceBroker();
await tempBroker.start();

tempBroker.ping('singleton-service-node', 1000)
  .then(res => {
    // the node with your singleton service is already present. Do nothing or throw an exception here
  })
  .catch(() => {
    // No such node is registered yet, feel free to create the service
    singletonWorkerBroker = new ServiceBroker({ nodeID: 'singleton-service-node' });
    await singletonWorkerBroker.start();

    singletonWorkerBroker.createService({ ... });
  });
```

**Comment by icebob** [comment]
[NodeID collision detection](https://github.com/moleculerjs/moleculer/issues/331) is coming in 0.14.
