### ISSUE TITLE
There are several security issues introduced through handlebars and lodash

### ISSUE THREAD

**Issue by dkuida** [moleculerjs/moleculer#478]
[snyk.io](https://app.snyk.io) service is reporting several security issues when moleculer is integrated into projects. coming form the usage of outdated versions of lodash and handlebars.

example:
https://github.com/wycats/handlebars.js/commit/7372d4e9dffc9d70c09671aa28b9392a1577fd86
would it be ok if I

- fix those
- create PR
- integrate snyk to run on PRs (it is free for open source)

**Comment by icebob** [comment]
Hi,

yes, it would be good. 
By the way, in the Moleculer core, there are no vulnerabilities: https://snyk.io/test/github/moleculerjs/moleculer
