### ISSUE TITLE
About Redis transporter issue 

### ISSUE THREAD

**Issue by JonWangM** [moleculerjs/moleculer#479]
I use Redis as a transporter,Both nodes use different DBs of the same redis. I want to distinguish whether it is the same transporter according to different DBs.

for example:

Node-1:
transporter:{
		type:"Redis",
		options:{
			host: "localhost",
			port: 6379,
			password:"000000",
			**db: 1**
		}
	},

Node-2:
transporter:{
		type:"Redis",
		options:{
			host: "localhost",
			port: 6379,
			password:"000000",
			**db: 4**
		}
	},

But they are still a same transporter.
How to distinguish different transporters according to db?

@icebob

**Comment by icebob** [comment]
Redis transporter uses Redis PUB/SUB functions but DB setting has no effect with it. More info: https://redis.io/topics/pubsub#database-amp-scoping

**Comment by JonWangM** [comment]
Thanks a lot to @icebob , which solves the problem of using one transporter in multiple environments.

However, when I call multiple node services frequently, it will cause the transporter to crash and the nodes cannot connect.
