### ISSUE TITLE
Service modifications support for ES6 classes

### ISSUE THREAD

**Issue by akazakou** [moleculerjs/moleculer#483]
**Is your feature request related to a problem? Please describe.**
I want to isolate the configuration mechanism from service initialization. In that case, I want to change `settings` property of schema. Regarding to [ES6 classes documentation](https://moleculer.services/docs/0.13/services.html#ES6-classes) I can't use schema modifiers. But `brocker.createService` supporting the second parameter with service modifications. 

I want to implement the second parameter of `Service` class constructor to support schema modifications for ES6 services.

**Describe the solution you'd like**
Update `brocker.createService` functionality to pass schema modifications into creating a new instance of service as the second parameter of `Service` class constructor
```typescript
constructor(broker: ServiceBroker, schemaMods?: ServiceSchema) {}
```

**Describe alternatives you've considered**
Right now I'm using a static property of Service to store schema modifications and apply it in a constructor:
```typescript
class ServiceSession extends Service {
  public static schemaMods: ServiceSchema = {} as ServiceSchema;

  constructor(broker: ServiceBroker) {
    super(broker);

    const serviceSchema: ServiceSchema = {
      /**
       * Name of current service
       */
      name: packageJson.name,
      // ***
    };

    // compile service schema and redefine settings
    this.parseServiceSchema(Object.assign({}, serviceSchema, ServiceSession.schemaMods));
  }
}
```

**Additional context**
The main idea of this feature request isolates Service functionality from environment configuring. Give DevOps team possibility to configure and modify service behavior, without requesting of Development team to code changes. 

It should give the Development team a possibility to isolate business logic inside the service. All API configuration, settings providers, additional middleware and etc should be configured outside of the service.

**Comment by akazakou** [comment]
I guess, it also should be applied to `brocker.loadService` and `brocker.watchService` function too.
`brocker.loadServices` should support object configuration with a key of the service name.

Maybe some implementations too, if it related to service initialization.

**Comment by fugufish** [comment]
Maybe, I don't understand the suggestion, but couldn't settings be modified per-environment just as easily using environment variables by devops without developer intervention?

**Comment by akazakou** [comment]
We have many ways how we can configure our services. Example: AWS Parameters Store, Some specific configuration service, environment variables or other. In that case, if we have different configuration flows for different environments like localhost, test, staging, the production we should support many settings sources in service code.

I want to move all configuration stuff to service runner. And implement separate service runner for each environment. Example:
* localhost environment will connect all available services and configure it from service runner configuration file
* testing environment will connect all available services, but run configuration from AWS Parameters Store
* Staging environment will create a few service runners for different server instances and work with AWS Parameters Store
* Production environment will compose a few different services for server instances. Connect configuration service with possibility restart some services on configuration changes (for example split traffic between services for A/B testing features)

Also, it can be related to different database adapters (like AWS DynamoDB and MongoDB) or allow the DevOps team to connect some additional middlewares to collect extended data. 

So, as I said, the main idea of this - isolate business logic inside of service. But how to run, configure and etc - move these decisions to DevOps team.

**Comment by kevyworks** [comment]
Too complex to understand and if it can be done by extending, there is nothing wrong w/it. There is a 0.14 version comming & i suggest, wait for it Sir..

**Comment by akazakou** [comment]
Here I just try to identify the problem with [brocker.createService](https://github.com/moleculerjs/moleculer/blob/master/src/service-broker.js#L625) method. It has different behavior for ES6 classes and GenerigObject service definitions. If we using GenericObject service definition, we can apply `schemaMods`. But if we using ES6 classes, we can't do it.
