### ISSUE TITLE
Redis Transport occurred "node disconnect" frequently。

### ISSUE THREAD

**Issue by liuwc121709** [moleculerjs/moleculer#484]
evn: 
   Redis 5.0.3
   moleculer 0.13.0

configuration: 
config the transporter with the redis on the moleculer.config.js add the below configuration.
transporter:{
	type:"Redis",
	options:{
		host: xxx,
		port:6379,
		password:xxx,
		db: 1
	}
}

issues: 
 when A service on A node call call the B service  on B node, the transporter occurred "node disconnect" frequently.
  eg: "warn: Node "B" disconnected unexpectedly "

 then A service on A node can't received  the hearbeat from B node and this service occurred the 503 error.  It think that B service is broken.
 {
    "name": "RequestRejectedError",
    "message": "Request is rejected when call 'service b' action on 'B' node.",
    "code": 503,
    "type": "REQUEST_REJECTED",
    "data":{
    "action": "SkuService.skuPermutation",
    "nodeID": "B"
}

Do you have any thoughts on that? Is that redis performance issue or moleculer configuration?

Thanks.

**Comment by icebob** [comment]
RequestRejectedError: answer is in #487. 
By the way, I experienced Redis throw connections which transfers too big data (e.g. with streams). You should increase some limits in Redis conf.

**Comment by liuwc121709** [comment]
Thanks for your help.
i use NATS as one transporter and it occurred  503 error, too.
Then i modify the NATS configuration to improve the payloay and the error is not product.
i will try to modify the redis conf and resolve it.

**Comment by icebob** [comment]
Try with these options: https://redis.io/topics/clients#output-buffers-limits
