### ISSUE TITLE
Is there a way of knowing if an action was called through the API Gateway?

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer#488]
I need to send different responses for actions called through the gateway and actions called the regular way.

**Comment by icebob** [comment]
Use the [`onBeforeHook`](https://moleculer.services/docs/0.12/moleculer-web.html#Route-hooks) and put a flag into ctx.meta.
```js
onBeforeCall(ctx, route, req, res) {
    ctx.meta.fromAPIGateway = true;
}
```

**Comment by Gadi-Manor** [comment]
Missed that part in the doc /:
Thanks a lot!
