### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by nimesh-s** [moleculerjs/moleculer#493]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Reproduce code snippet
```js
const broker = new ServiceBroker({
    logger: console,
    transporter: "NATS"
});

broker.createService({
    name: "test",
    actions: {
        empty(ctx) {
            return "Hello"
        }
    }
});
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version:
* NodeJS version: 
* Operating System:

### Failure Logs
```

```

**Comment by icebob** [comment]
Please don't testing issue opening here, because a lot of people receive e-mail notifications about these issues.
