### ISSUE TITLE
[Question] How do you dynamically route call to an action on a specific node based on an external state

### ISSUE THREAD

**Issue by zllovesuki** [moleculerjs/moleculer#494]
Hypothetically, say an action `create` requires access to a legacy back end, and with multiple nodes running with the same code.

Want: when a caller calls the `create` action, we only want one node to respond to the request (as this node is the “primary” node), and not selected based on strategy or anything (so it doesn’t get routed to the non-primary nodes).

Question: is that doable? Or do we need some sort of external state to keep track of which node is running the “primary” and can service the  `create` action, then do a `mcall()` instead?

**Comment by tiaod** [comment]
There is a calling option:

nodeID: Target nodeID. If set, it will make a direct call to the given node.
