### ISSUE TITLE
Please provide a migration guide

### ISSUE THREAD

**Issue by maisnamraju** [moleculerjs/moleculer#498]
**Is your feature request related to a problem? Please describe.**
I switched from 0.12.0 to the latest build and i always end up with a 404 error on my services because of it and I have to switch back to 0.12.0 to fix it. 

**Describe the solution you'd like**

Please provide a list of breaking changes and a migration guide to fix issues. 

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreMaz** [comment]
Hey @maisnamraju 
Check the [Migration guide](https://github.com/moleculerjs/moleculer/blob/v0.13.0/docs/MIGRATION_GUIDE_0.13.md)
