### ISSUE TITLE
The parentCtx field recursively increases size of INFO packet

### ISSUE THREAD

**Issue by nbvehbq** [moleculerjs/moleculer#503]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Expected Behavior

Expect INFO packet size not change or change but not much.

## Current Behavior

- INFO packet size increase by an order of magnitude
- Packet payload in some services sittings contain 'parentCtx' object

### Steps to Reproduce

1. Add callOtions in routes settings
```js
 routes: [
      {
        ...,
        callOptions:{
          timeout: REQUEST_TIMEOUT
        },
        ...,
      },
      ...
 ]
```
2. npm run dev
3. call some action
3. change your code in whatever service
4. after service reloaded INFO packet increase by an order of magnitude 

### Context

* Moleculer version: 0.13.7
* NodeJS version: 10.14.2
* Operating System:

**Comment by icebob** [comment]
@AndreMaz if you have some time, could you reproduce & check it?

**Comment by AndreMaz** [comment]
Hey @nbvehbq. I can't reproduce the described behavior. Can you please create a repo with the issue?

Also, in your case the error only happens when the `timeout` is set?

**Comment by nbvehbq** [comment]
Hi @AndreMaz error happens when `callOptions` is set in my case. 
In my project 52 services and ~10 items in routes array...

My workaround is straightforward - remove `parentCtx` while get service list for INFO packet in `getLocalNodeServices()` in src/registry/service-catalog.js:
```js
...
item.settings = Object.keys(service.settings).reduce((p, n) => {
  if(n !== "routes")
    return {...p, n: service.settings[n]};
      const routes = service.settings[n].map((i => {
        if (i.callOptions && i.callOptions.parentCtx)
          return {...i, callOptions: _.omit(i.callOptions, "parentCtx")};
        return i;
      }));

  return {...p, routes};
}, {});
```
I capture INFO packet... Hope it helps 

![image](https://user-images.githubusercontent.com/23618586/55056549-707bc280-5077-11e9-9bc2-d07aaf44b563.png)

**Comment by icebob** [comment]
I've found the issue & fixed.
