### ISSUE TITLE
Actions in services with ProtoBuf and NATS cannot return 0 and false.

### ISSUE THREAD

**Issue by alvarocantador** [moleculerjs/moleculer#511]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Expected Behavior

Be able to receive `0` and `false` as a result of some action in a service using NATS and Protobuf.

## Current Behavior

0 and false are received as undefined.

## Failure Information

Protobuf serialize or deserialize the message incorrectly and turns `0` and `false` results into `undefined` 

### Steps to Reproduce

1. step 1
2. step 2
3. you get it...

### Reproduce code snippet
```js

const broker = new ServiceBroker({
    transporter: "NATS",
    serializer: 'ProtoBuf'
});

broker.createService({
    name: "greeter",
   version: 1,
    actions: {
		willReturnFalse() {
			return false;
		},

		willReturnZero() {
			return 0;
		}
});

describe("Test 'greeter' service", () => {

	const broker = new ServiceBroker({ transporter: 'nats://localhost:4222', serializer: 'ProtoBuf' });

	beforeAll(async () => {
		await broker.start();
		await broker.waitForServices([{ name: 'greeter', version: 1 }]);
	});

	afterAll(() => broker.stop());

	describe("Test 'greeter.willReturnFalse' action", () => {
		it("should return false", () => {
			expect(broker.call("v1.greeter.willReturnFalse")).resolves.toBe(false);
		});
	});


	describe("Test 'greeter.willReturnFalse' action", () => {
		it("should return 0", () => {
			expect(broker.call("v1.greeter.willReturnZero")).resolves.toBe(0);
		});
	});
});

// both tests will fail receiving undefined


```
## EXAMPLE READY TO RUN: 
https://github.com/alvarocantador/moleculer-zero-and-false-bug

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.8
* NodeJS version: 10.15.3
* Operating System: MacOS

### Failure Logs
```

```

**Comment by icebob** [comment]
@AndreMaz could you help with it?

**Comment by lucduong** [comment]
@hoanganh25991 Could you check once?

**Comment by hoanganh25991** [comment]
Hi @alvarocantador ,
I've tested ProtoBuf on NATS, the serializer work as expected
![image](https://user-images.githubusercontent.com/8801188/55601463-34d5ac80-578b-11e9-9063-20f7c5d4b037.png)

In my test, I only use moleculer-cli to init minimal project template.
I guested your API service make change on value.

Example ready to run:
https://github.com/hoanganh25991/protobuf-serialize-false-zero

**Comment by alvarocantador** [comment]
@hoanganh25991  In your case, the greeter is a local service and its work as expected. Try to run dev in a shell and call it in another repl, you will see undefined.

I have the bug example here: https://github.com/alvarocantador/moleculer-zero-and-false-bug

**Comment by alvarocantador** [comment]
Only in the `npm run dev` shell:
![image](https://user-images.githubusercontent.com/4078365/55626904-30a59100-5783-11e9-9d32-4db7bdf347c2.png)

Now with an REPL:
![image](https://user-images.githubusercontent.com/4078365/55626909-34d1ae80-5783-11e9-8f76-fa0803b51e06.png)

**Comment by hoanganh25991** [comment]
Hi @alvarocantador ,

By default, broker config "prefer local", which lead to call without send through NATS.
I see your issue when add another repl.

I digging in transporter & serializer code to figure out.

**Comment by hoanganh25991** [comment]
Protobuf serialize flow:
  - Convert data to string
  - Build up buffer from that string
  - Encode with proto/packets.proto.js before send out

I think the if check falsy value on `obj.data` in `serializer/base.js` cause the problem:
  - JSON.stringify never hit
  - cause Buffer.from never hit
  - cause deserialize return undefined

As what I test, remove the falsy check, response return false, 0 as expected

https://github.com/moleculerjs/moleculer/blob/master/src/serializers/base.js#L98

![image](https://user-images.githubusercontent.com/8801188/55651542-2a5ef580-5813-11e9-8bab-34f246f5a047.png)

## Protobuf Serializer

https://github.com/moleculerjs/moleculer/blob/master/src/serializers/protobuf.js

### Serialize

```js
base.js > serializeCustomFields
Falsy value not converted to string

case P.PACKET_RESPONSE: {
  obj.meta = JSON.stringify(obj.meta);
  if (obj.data) {
    if (!obj.stream) {
      obj.data = JSON.stringify(obj.data);
    }
  }
}

protobuf.js > serializeCustomFields
Buffer not built up

case P.PACKET_RESPONSE: {
  if (obj.data && !obj.stream)
    obj.data = Buffer.from(obj.data);
  break;
}
```

### Deserialize

```js
protobuf.js > deserializeCustomFields
No data key on obj, return undefined

case P.PACKET_RESPONSE: {
  if (obj.data && !obj.stream) {
    if (obj.data.length)
      obj.data = obj.data.toString("utf8");
    else 
      obj.data = undefined; 
  }
  break;
}
```

**Comment by icebob** [comment]
@hoanganh25991 good catch. Thank you, I'm fixing.

**Comment by icebob** [comment]
I've fixed. @hoanganh25991 @alvarocantador could you check it to install master with `npm i moleculerjs/moleculer`?

**Comment by hoanganh25991** [comment]
Hi @icebob ,

I've tested your fix on "moleculerjs/moleculer", now Protobuf serialize correctly on false, 0 case. However, it return as "undefined" on null case.

<img width="1988" alt="protobuf-serialize-false-zero-2019-04-07 14-32-45" src="https://user-images.githubusercontent.com/8801188/55680307-5e850400-5942-11e9-9aa2-4c73c35ac83c.png">

As my test above, on "greeter.willReturnNull", Protobuf deserialize as "undefined".

Test example ready to run:
https://github.com/hoanganh25991/protobuf-serialize-false-zero

**Comment by icebob** [comment]
Thanks. I'm checking...

**Comment by icebob** [comment]
I've fixed it.
