### ISSUE TITLE
Kubernetes deployment in Docs?

### ISSUE THREAD

**Issue by jbonnett92** [moleculerjs/moleculer#512]
Could you please add Kubernetes instructions to the documentation?

**Comment by icebob** [comment]
I have not enough experience with Kubernetes, so I can't write it. I need help from somebody who knows well Kubernetes & Moleculer

**Comment by aliazlan4** [comment]
@icebob @jbonnett92  I have just setup my microservices architecture using kubernetes and moleculer. I can help.

**Comment by icebob** [comment]
@aliazlan4  It would be awesome! Please send me the article link when you are done.
By the way, if you can help to improve the documentation with Kubernetes please open a PR on [site repo](https://github.com/moleculerjs/site/tree/master/source/docs/0.13)

**Comment by aliazlan4** [comment]
@icebob sure man. Will do that.

**Comment by lehno** [comment]
I would like to have this link as well, it would be great @aliazlan4

**Comment by olivinesguerra** [comment]
@aliazlan4  would like to add some sample implementing using GCP? Thanks

**Comment by ppamorim** [comment]
Could I have the docs please?

**Comment by rcomiskey** [comment]
I'd really like documentation on this as well.

**Comment by tobydeh** [comment]
+1

**Comment by jbonnett92** [comment]
Didn't think it would get this much traction 😂

**Comment by hatung** [comment]
documentation please!

**Comment by davidroman0O** [comment]
@jbonnett92 Because it would be really awesome 😄

**Comment by lehno** [comment]
I'm trying to implement it as well, finishing a K8s course and see if I can do by myself. Maybe I will write a tutorial as well them

**Comment by jbonnett92** [comment]
Please tell me someone has made progress?

**Comment by tobydeh** [comment]
@jbonnett92 I've got everything setup as per the gist i posted.

**Comment by lehno** [comment]
Im working on it and keeping notes of every change I'm making. The post will be released soon, I will credit @tobydeh for all the help as well

**Comment by hatung** [comment]
any update?

**Comment by lehno** [comment]
For people that want to try now, here is a repo with k8s scripts to run on Google Cloud
https://github.com/lehno/moleculer-k8s-examples

**Comment by dkuida** [comment]
I wrote a post a while ago about that 
https://dankuida.com/moleculer-deployment-thoughts-8e0fc8c0fb07

**Comment by HazemKhaled** [comment]
I created a pull request to add those links in the documentation
https://github.com/moleculerjs/site/pull/86

**Comment by sskhokhar** [comment]
@dkuida I have checked your article, kudos!
But i'm bit confused about why have you created 3 separate repos with moleculer. 
What if all of these services are incorporated in one moleculer project created by moleculer-cli. How will the services be incorporated as separate docker images and kubernetes?
