### ISSUE TITLE
ServiceSchema lifecycle methods TS definitions

### ISSUE THREAD

**Issue by shawnmcknight** [moleculerjs/moleculer#520]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

## Current Behavior
The ServiceSchema lifecycle methods `created`, `started`, and `stopped` are defined in the TS declaration as:
```js
interface ServiceSchema {
...
  created?: () => void;
  started?: () => PromiseLike<void>;
  stopped?: () => PromiseLike<void>;
...
}
```

I believe these should be:
```js
interface ServiceSchema {
...
  created?: () => void | (() => void)[];
  started?: () => PromiseLike<void> | (() => PromiseLike<void>)[];
  stopped?: () => PromiseLike<void> | (() => PromiseLike<void>)[];
...
}
```
After mixins are applied, the service's schema for the lifecycle methods becomes an array.  I also think there's nothing stopping a user from actually providing an array of lifecycle methods in the schema definition.

I can submit a PR for this provided there is agreement that this is the correct path.

Thanks!

**Comment by darky** [comment]
Also please write typescripts tests here:
https://github.com/moleculerjs/moleculer/tree/master/test/typescript/tsd

**Comment by icebob** [comment]
Great, thanks!
