### ISSUE TITLE
When Cacher is an object and type is a redis connection string there is an error

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer#522]
## Current Behavior

I set a cacher object as follows:
` cacher: { options: {
      maxParamsLength: 44
    },
    type: 'redis://myhost.com:6379' }`
 
When I run the app I get an error saying `Invalid cacher type 'redis://myhost.com:6379`
It is happening because the check if the value is a redis connection string only occurs when the cacher is of type string (src/cachers/index.js:45). 
 
## Expected Behavior

There should be another check in `getByName()`.

### Steps to Reproduce

Create a cacher object as shown above. The `type` could be `redis://localhost:6379` .

I could send a PR with my fix once you approved this is indeed a bug.

**Comment by icebob** [comment]
It's not a bug, it follows how transporter config works, as well. You can use shorthand connection string if `cacher` is a string. If you need other options, use this form:
```js
	cacher: {
		type: "Redis",
		options: {
			url: "redis://localhost:6379"
		}
	},
```

**Comment by Gadi-Manor** [comment]
Got it, Thanks!
