### ISSUE TITLE
action params of type number with convert true does not convert bool false to number

### ISSUE THREAD

**Issue by morkeleb** [moleculerjs/moleculer#523]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

I am however unsure if this is the correct repository, it might be in the fast validation repository.

## Current Behavior

We have an action with a following param setup

```
myParam: {
  type: number.
  convert: true
}
```

we pass it an object where the param is of type bool value false.

```
{ "myParam":false }
```

the validation passes, causing sequlize to throw really wierd errors at their end, because its a decimal in the db.

## Expected Behavior

We would expect it to convert false to 0 and true to 1.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create a service with an action that takes a number as a param with convert: true
2. call the action with the param with a false value
3. see that you wont get a validation error, but you the value is still a boolean even though expected is a number.

### Reproduce code snippet

```js
const broker = new ServiceBroker({
    logger: console,
    transporter: "NATS"
});

broker.createService({
    name: "test",
    actions: {
        empty : {
          params: {
            myParam: {
              type: number.
               convert: true
             }
         },
        async handler(ctx) {
            return ctx.params.myParam;
        }
    }
});

broker.call('test.empty', '{"myParam":false}');
```

above code illustrates the issue but is untested.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.8
* NodeJS version: 10.15.2
* Operating System: mac os x 10.14.3

### Failure Logs
```

```

**Comment by icebob** [comment]
The `convert` property doesn't convert the value in `ctx.params` just for validation. For numbers, it uses `Number()` which can convert a string to a number but not a boolean to a number.

Relevant codes: https://github.com/icebob/fastest-validator/blob/a5f2b056bd9d92037b90dd214d0aa2a43073bd6b/lib/rules/number.js#L4-L6
