### ISSUE TITLE
Extend logger error

### ISSUE THREAD

**Issue by xeroxstar** [moleculerjs/moleculer#529]
I am getting an error when i am trying to install the winston logger:
```
 const winston = require("winston");
 const { extend } = require("moleculer").Logger;
 const broker = new ServiceBroker({    
       logger: bindings => extend(winston.createLogger({   });
 })
```
The error:

**ReferenceError: extend is not defined**

Why do you think i am getting this error?
Thank you

**Comment by icebob** [comment]
I've tested and it works.

**Comment by xeroxstar** [comment]
I missed one line there and didn't see it,  the error was my fault, sorry about it. By the way i was wondering when the NATS will be ready for production? Also i can't find the events for transporters (if there is any)...

**Comment by icebob** [comment]
NATS is production ready, NATS Streaming is not.
