### ISSUE TITLE
preferLocal: false not force remote call

### ISSUE THREAD

**Issue by darky** [moleculerjs/moleculer#533]
## Current Behavior

`registry.preferLocal = false` allow to call actions locally

## Expected Behavior

`registry.preferLocal = false` should force remote call
Maybe need some other option like `registry.forceRemote = true`

### Context

* Moleculer version: 0.13.9

**Comment by icebob** [comment]
`preferLocal` doesn't mean that it calls only remote nodes but means that it doesn't call always the local nodes.

**Comment by darky** [comment]
Ok, would be cool to have `registry.forceRemote` flag for this behavior.

**Comment by icebob** [comment]
What is the use case for this feature? Why would be it cool to avoid local action calls?

**Comment by darky** [comment]
In my case custom serialization is used.
For example: iso date string -> Date under the hood
But local action calls avoid custom serialization

**Comment by darky** [comment]
On the other side, I can use middleware for this purpose.
Close it.
