### ISSUE TITLE
HAPI & Context & Tracing

### ISSUE THREAD

**Issue by sysrun** [moleculerjs/moleculer#537]
I am trying to implement an api-gateway via HAPI which is doing the trace logging via jaeger. Every call inside of moleculer is already logged. 

Now i want to start the trace-span in the api-gateway itself. Can't get my head around how to start a trace when the API-Service is getting for example a GET request.

I already create a moleculer context when a request is coming in - but i don't knwo how to start a trace span there :/

**Comment by icebob** [comment]
Check the source of moleculer-web. It defines an `api.rest` action and call when a request arrived. So it will be the start of the trace. After that, you should call the desired action via `ctx.call` and the trace spans will be chained.

**Comment by sysrun** [comment]
Thanks for your help :) i already had a look into the moleculer-web code.

So in my understanding i have to do the following in my api-gateway:

- Create a HAPI Server and the routes
- Create a moleculer broker
- Create a moleculer api-gateway service and pass the hapi server instance
- In the moleculer api-gateway service:
  - add a "request" action which should be called on every hapi request
  -  in the "create" function: attach  the action to the hapi "request" hook and add the ctx to the request

- in the hapi route handler the use the ctx.call fn

Is that the way?

**Comment by icebob** [comment]
Yes, it seems good.

**Comment by sysrun** [comment]
Nice - works now :) 

Followup: 
- How to add tags, & events/logs to the ctx span?
- Is it possible to add subsequent spans?

**Comment by icebob** [comment]
For both questions, in 0.13 it is not available. But in the next version 0.14, it will be supported.

**Comment by sysrun** [comment]
Awesome - just hat a look into the "next" branch :D looking forward to this!
