### ISSUE TITLE
Type of this in hook

### ISSUE THREAD

**Issue by arnoldcui** [moleculerjs/moleculer#540]
**Is your feature request related to a problem? Please describe.**

I trying use `this` in `started` hook,but it has an `any` type 
![image](https://user-images.githubusercontent.com/40977489/58253666-8669e300-7d9b-11e9-830f-e2aa8fe638d6.png)

**Describe the solution you'd like**

Provide a parameter as this.
```
started(this){
}
```

**Describe alternatives you've considered**

Provide an interface.

```
import { IThis } from "moleculer"
......
const this_:IThis = this;
......
```

**Additional context**

**Comment by icebob** [comment]
You can [define](https://github.com/Microsoft/TypeScript/issues/229#issuecomment-257172012) type of this in function.
