### ISSUE TITLE
Question | Is load balance per event/action or per service?

### ISSUE THREAD

**Issue by omerts** [moleculerjs/moleculer#542]
Hey,

I tried understanding from the code, just want to make sure I got it correctly. The load balancer balances per action/event + service, and not just service right?
For example:
I have a user.created and user.deleted events.
Service 1 - listens to both created & deleted events.
Service 2 - listens to only deleted events
If user.created event is dispatched-> Service 1 gets it.
If user.deleted event is dispatched -> Service 1 might get it again, since it is a different event, right?

**Comment by icebob** [comment]
Yes, all events balanced between service instances. So if you have 3 instances of Service 2 and 2 instances of Service 1, only one Service1 & one Service 2 will receive the event.
