### ISSUE TITLE
Can I connect with remote service written by other framework?

### ISSUE THREAD

**Issue by pxuanthu98** [moleculerjs/moleculer#545]
**Connect with remote service written by other framework**
Hello all,
I have some services written by NestJS, using NATS transporter. Now I want to connect them with my services written by MoleculerJS to using built-in Service Discovery and Serivce Register.
Can I do it?
Thanks!

**Comment by icebob** [comment]
No. Moleculer is compatible with other [Moleculer libraries](https://github.com/moleculerjs/moleculer/issues/347)
