### ISSUE TITLE
Middleware createService being invoked too early

### ISSUE THREAD

**Issue by flaviocordova** [moleculerjs/moleculer#556]
I wan't to create a middleware to set defaults to services and actions (things like cache, visibility, etc.).

However, the createService method is called before the mixins are applied to the schema so the middleware has limited access to change the service before it's published.

**Comment by AndreMaz** [comment]
Hi.

The v0.14 will have a new middleware `serviceCreating` that does what you need. It's called _after_ all mixins are applied. [More info here](https://github.com/moleculerjs/moleculer/blob/next/CHANGELOG.md#servicecreating)

**Comment by flaviocordova** [comment]
Hi @AndreMaz , thanks...

that's great news but I got a little worried about the new comm protocol, but I'll open a different issue to discuss it.

by the way, any idea when 0.14 it's going to be released? no need for final date but something like "in a week or in two months" would be enough.. :)

**Comment by AndreMaz** [comment]
> by the way, any idea when 0.14 it's going to be released? no need for final date but something like "in a week or in two months" would be enough.. :)

@icebob can provide more precise time window but I think that in a few weeks a beta version will come out

**Comment by icebob** [comment]
I will release a beta in this or next week. Stable release depends on the results of beta testing but I hope in July or August.
