### ISSUE TITLE
NATS is not working with moleculer-runner

### ISSUE THREAD

**Issue by vbilici** [moleculerjs/moleculer#557]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

I installed moleculer with the default options with `moleculer-cli`

## Current Behavior

after running `npm run dev` 

it throws an error (Error is in the failure logs)

NOTE: If I run it through docker compose, it runs perfectly

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `moleculer init project my-project`
2. cd my-project/
3. npm run dev

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.9
* NodeJS version: 10.15.3
* Operating System: Mac Os Mojave 10.14.5

### Failure Logs
```
INFO  volkanspersonal.fritz.box-63185/BROKER: Moleculer v0.13.9 is starting...
INFO  volkanspersonal.fritz.box-63185/BROKER: Node ID: volkanspersonal.fritz.box-63185
INFO  volkanspersonal.fritz.box-63185/BROKER: Namespace: <not defined>
INFO  volkanspersonal.fritz.box-63185/REGISTRY: Strategy: RoundRobinStrategy
INFO  volkanspersonal.fritz.box-63185/BROKER: Serializer: JSONSerializer
INFO  volkanspersonal.fritz.box-63185/BROKER: Transporter: NatsTransporter
INFO  volkanspersonal.fritz.box-63185/BROKER: Registered 10 internal middleware(s).
INFO  volkanspersonal.fritz.box-63185/API: Register route to '/api'
INFO  volkanspersonal.fritz.box-63185/API: API Gateway created!
INFO  volkanspersonal.fritz.box-63185/TRANSIT: Connecting to the transporter...
ERROR volkanspersonal.fritz.box-63185/TRANSPORTER: NATS error. Could not connect to server: Error: connect ECONNREFUSED 127.0.0.1:4222
WARN  volkanspersonal.fritz.box-63185/TRANSIT: Connection is failed. Could not connect to server: Error: connect ECONNREFUSED 127.0.0.1:4222
```

**Comment by fdjean** [comment]
exact conf and version here: all fine. 
if you start nats with:
`/usr/local/bin/gnatsd -p 4222 -m 8888`
do you see things here 
`http://localhost:8888`

**Comment by vbilici** [comment]
I don't have `/usr/local/bin/gnatsd` on my computer but if I install nats with brew and run it via `nats-server` then run moleculer, it works
If I run nats through docker via nats image, it works
I also tried renaming `/usr/local/bin/nats-server` to `/usr/local/bin/gnatsd` but it didn't work.

**Comment by icebob** [comment]
NATS is not part of the Moleculer, it is an external app. You should start individually.

**Comment by vbilici** [comment]
oh ok, I was suspecting that after doing these trials. Thanks for helping!
