### ISSUE TITLE
What is the appropriate way to delete a key from the cacher?

### ISSUE THREAD

**Issue by Gadi-Manor** [moleculerjs/moleculer#558]
I'm working on the PR for #509 and while I was testing it I came across an issue.
I have an action with the following property: 
```
cache: {
        keys: ['myKey'],
        ttl: 60
}
```

When it's stored in the cacher (`Redis` in my case) the key is a combination of the action name and the value of `myKey` which is created in `Cacher.getCacheKey`.

So, if I want to delete this key later I should call `Cacher.getCacheKey` as well? In that case shouldn't it be part of the `Cacher` declaration?

**Comment by icebob** [comment]
Good idea. In my head, the concept was that if you leave caching to Moleculer than you will delete all entries by service with `broker.cacher.clean("users.**")`. Another way if you put cache entries manually with `broker.cacher.set(key, value)` (not used the hashed key) in this case you can delete it with the key with `broker.cacher.del(key)`.
