### ISSUE TITLE
Regex Cache in Utils

### ISSUE THREAD

**Issue by ccampanale** [moleculerjs/moleculer#560]
I just happened to be reading this code snippet when it occurred to me that this may not be working as expected (assuming it's expected to work as written).

https://github.com/moleculerjs/moleculer/blob/master/src/utils.js#L156-L173

It appears that a `Map` object is created to cache the regex tests when `.match()` is called however, unless I am missing something, the code here will **always** update the pattern before caching the regex object in the map when the cache does not include an entry for the provided pattern.

Since the pattern is always updated before caching, logic would dictate that the original pattern will also **never** match thus completely defeating the purpose of the caching mechanism here.

It would seem that the intention should be to store the the resulting regex object (created using the modified pattern) but with a key which is the original pattern.

I don't think this is really causing any issues but it may significantly speed up the more complex regex based pattern matching as I believe was the intention of the author.

I'm not personally effected by this but (hence, not a bug or feature request technically) but I figured it was worth pointing out.

**Comment by icebob** [comment]
Nice catch. You are right. Thanks! I will fix it.
