### ISSUE TITLE
AMQP 1.0

### ISSUE THREAD

**Issue by nllahat** [moleculerjs/moleculer#561]
Hi guys,

Currently we're using Moleculer.js with ActiveMQ (AWS service) as our MQTT transporter. We cannot use the AMQP transporter because AWS ActiveMQ is using the newer version of AMQP (1.0). We prefer using the AMQP protocol (along with the broker option `disableBalancer: true`) cause we want our messages to be queued to increase persistency.

We can't switch to other MQ servers (like RabbitMQ) cause we want the AWS support for this service.

So we thought maybe we should add another transporter AMQP1.0.

What do you think? 
We will be happy to hear some insights.

@Nathan-Schwartz 
@icebob 

Thanks (:

**Comment by icebob** [comment]
Hi @nllahat,

it would be good. By the way, it means, the AMQP 1.0 is not compatible with previous versions?

**Comment by Nathan-Schwartz** [comment]
We use [amqp.node](https://www.npmjs.com/package/amqplib) for the AMQP transporter and it unfortunately only supports 0-9-1.

It has been discussed for the project here:
https://github.com/squaremo/amqp.node/issues/63
https://github.com/squaremo/amqp.node/issues/486

**Comment by nllahat** [comment]
> Hi @nllahat,
> 
> it would be good. By the way, it means, the AMQP 1.0 is not compatible with previous versions?

@icebob That's right. Because of that we want to add another transporter and not replace the existing.

**Comment by nllahat** [comment]
> We use [amqp.node](https://www.npmjs.com/package/amqplib) for the AMQP transporter and it unfortunately only supports 0-9-1.
> 
> It has been discussed for the project here:
> [squaremo/amqp.node#63](https://github.com/squaremo/amqp.node/issues/63)
> [squaremo/amqp.node#486](https://github.com/squaremo/amqp.node/issues/486)

@Nathan-Schwartz Thanks for the references.
I want to add another transporter that uses [rhea](https://github.com/amqp/rhea).

**Comment by icebob** [comment]
Thanks. In this case, another transporter would be good, @nllahat

**Comment by icebob** [comment]
Any updated about it?

**Comment by nllahat** [comment]
No.. We postpone this task for now..

**Comment by lehno** [comment]
If you decide to move on with this, let me know as it would be good for us as well

**Comment by nllahat** [comment]
Hi @lehno  we are considering it again. Will update here when we start writing the transporter

**Comment by tonychangcheng** [comment]
So what is the solution for connecting ActivMQ? Using the experimental AMQP10 or waiting for a new rhea transporter?

**Comment by bmarchbank** [comment]
@nllahat were you ever able to get this working in AWS MQ?  We are running into issues using the AMQP10 transporter to connect on the SSL port (5671).

**Comment by nllahat** [comment]
We got this working with AWS ActiveMQ. 
@xvld Do you remember if we has any issues with the SSL port ?

**Comment by xvld** [comment]
> We got this working with AWS ActiveMQ. 
> @xvld Do you remember if we had any issues with the SSL port ?

@nllahat I don't remember any issues there

**Comment by bmarchbank** [comment]
@nllahat @xvld - Thanks for the response. Good to know it's possible at least... We'll keep looking into it, it may just be a networking issue in our VPC. Rhea-promise is only returning a "Failed to connect" error with not much extra information.

**Comment by bmarchbank** [comment]
> @nllahat @xvld - Thanks for the response. Good to know it's possible at least... We'll keep looking into it, it may just be a networking issue in our VPC. Rhea-promise is only returning a "Failed to connect" error with not much extra information.

FYI in case anyone else encounters this issue...  I had to provide a "transport" connection option to rhea in the moleculer.config.ts to get this working:
```typescript
  transporter: {
    type: "AMQP10",
    options: {
      url: "amqp+ssl://username:password@aws-mq-host:5671",
      connectionOptions: {
        transport: "tls", // required to talk to AWS MQ
      },
    },
  },
```

I was not able to find a way to do this via the `TRANSPORT` environment variable's string format.
