### ISSUE TITLE
How to Populating one to many in mysql

### ISSUE THREAD

**Issue by nvthuong1996** [moleculerjs/moleculer#565]
Suppose I have a user and post table. The post will contain the user's foreign key
I want to retrieve a user record with all the users' post
-------------------------------------
How can I change properties populate when merging?
I want to populate by author_id. however after merging I want to change author_id to author

{
 "title":"this is title post",
 "author_id":{ ... }
}

**Comment by lucduong** [comment]
This question should not be here. It depends on how use use [`moleculer-db`](https://github.com/moleculerjs/moleculer-db)

**Comment by nvthuong1996** [comment]
oke. thank you
