### ISSUE TITLE
Issue with services losing references to other dependencies

### ISSUE THREAD

**Issue by amroessam** [moleculerjs/moleculer#567]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository

## Current Behavior

Moleculer works fine locally, but once I start it on docker, it doesn't function the same and no error messages spit out.

## Expected Behavior

Error messages

### Steps to Reproduce

I can add whoever wants to figure it out as a contributor to the project

### Context

Works fine on mac and windows. Doesn't work in Docker container, no error logs.

* Moleculer version: Latest
* NodeJS version: Latest
* Operating System: Mac OSX 10.14.3 (18D109)

### Failure Logs
None

**Comment by amroessam** [comment]
So I've done some more testing, whenever I try to run moleculer using NATS it fails midway without any error messages. I'm unable to call services from other services.

**Comment by icebob** [comment]
Could you create a repro repo?

**Comment by amroessam** [comment]
My colleague has actually figured out the issue. @mohammed-ali-1 please chime in

**Comment by mohammed-ali-1** [comment]
Hi, sorry for the delay.

So our code was working fine when we would run it locally. Once we moved to Docker, one of our services just silently fails when it tries to run a database query to retrieve a document from MongoDB.

After some trial and error, I discovered that adding the database mixin and the corresponding model seems to have fixed the issue.

This is what the service code looked like before the fix: 
```
const utils = require('../mixins/utils.mixin')

module.exports = {
  name: 'serviceA',
  mixins: [utils],
  actions: {
    start: {
      async handler(ctx) {
        const {
          JobID,
          JobQueue,
          JobOwner,
          JobSession,
          JobData
        } = await this.GetJobDetails(ctx.params.job.JobID)
...
```
The failure would occur at `await this.GetJobDetails`. `GetJobDetails` is part of the utils mixin - which is already imported. What would happen is that the execution would silently stop at this point. No errors.

And this is the what the code looked like after the fix:
```
const utils = require('../mixins/utils.mixin')
const DbService = require('../mixins/db.mixin')
const JobModel = require('../models/job.model.js')

module.exports = {
  name: 'serviceA',
  mixins: [DbService('jobs'), utils],
  model: JobModel,
  actions: {
    start: {
      async handler(ctx) {
        const {
          JobID,
          JobQueue,
          JobOwner,
          JobSession,
          JobData
        } = await this.GetJobDetails(ctx.params.job.JobID)
...
```

After adding:
```
const DbService = require('../mixins/db.mixin')
const JobModel = require('../models/job.model.js')
```
and 
```
model: JobModel,
```

the code now seems to work on Docker and locally.

**Comment by amroessam** [comment]
Reopening for investigation
