### ISSUE TITLE
Is there a way to restart borker or service?

### ISSUE THREAD

**Issue by AmazingDesign** [moleculerjs/moleculer#575]
I need to create services dynamically from data loaded from database when app starts.

I need to restart broker to get access to newly created services.

`this.broker.stop().then(this.broker.start())` not works because in the meantime every call makes error and moleculer-runner exits.

Any ideas? Is that even possible?

**Comment by AmazingDesign** [comment]
My bad. I don't need to restart broker. I must wait for newly created service before calling it, after `broker.createSrevice`.

Is there a way to  ping service? Other than trying to call its action? @icebob can you help?

**Comment by icebob** [comment]
You can ping only nodes with `broker.ping` or waiting for a service with `broker.waitForServices`.

**Comment by AmazingDesign** [comment]
@icebob thanks. I have another question.

I've been continue working on dynamically created services and now I need to restart some of them.

The services are using DB adapter, so they need to have `settings.fields` configured.
In my case `settings.fields` comes form DB when service is dynamically created.
The issue is when data in DB changes (eg one field is added to the service) when the service is already running. Of course the service do not serve newly created field because, when it was started  `settings.fields` was configured and it can't be changed (or am I wrong and I simply can overwrite this.settings when service is running?). 

I've found https://moleculer.services/docs/0.14/api/service-broker.html#destroyService but it only destroys local service. There is a way to destroy all service instances (after that I will start them again with new config)? Or is a way to restart them?

**Comment by icebob** [comment]
You can't restart or destroy services on remote nodes, just locally. I recommend making a middleware, which listens an event, e.g. `"reload.db-services"`. If event is triggered, it find the local DB services and reload them locally. The middleware should loaded on all nodes. And you can broadcast this event when your DB is changed. WDYT?

**Comment by icebob** [comment]
By the way, in the next 0.14 version, Moleculer Runner will add a restart function to the broker as `broker.runner.restartBroker()`

**Comment by AmazingDesign** [comment]
Thanks! Seems to be a good idea! I will try.
