### ISSUE TITLE
custom validator with fastest-validator throws error: TypeError: this.validator.init is not a function

### ISSUE THREAD

**Issue by ilnuribat** [moleculerjs/moleculer#578]
## Current Behavior

I tried to add  custom validation to fastest-validator schema and set to ServiceBroker.

## Expected Behavior

https://moleculer.services/docs/0.13/validating.html
as seen in this example, I want to use fastest-validator instead of JoiValidator

### Steps to Reproduce

`npm i moleculer fastest-validator`

### Minimal code to reproduce problem

```js
const { ServiceBroker } = require('moleculer');
const Validator = require('fastest-validator');

new ServiceBroker({
  validation: true,
  validator: new Validator(),
});
```

### Context

* Moleculer :^0.13.9
* NodeJS version: 12.7
* Operating System: Ubuntu 18.04 LTS

### Failure Logs
```
Error: this.validator.init is not a function
    at new ServiceBroker (/home/ilnur/test/core_services/node_modules/moleculer/src/service-broker.js:189:21)
    at Object.<anonymous> (/home/ilnur/test/core_services/test.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
```

**UPD**
What I really want to do:

```js
const { ServiceBroker } = require('moleculer');
const Validator = require('fastest-validator');
const moment = require('moment');

const validator = new Validator();

validator.add('momentDate', date => {
  try {
    moment(date).isValid();

    return true;
  } catch (err) {
    return false;
  }
});

const broker = new ServiceBroker({
  validator,
});

broker.createService({
  name: 'test',
  actions: {
    checkDate: {
      params: {
        birthdate: {
          type: 'momentDate',
          convert: true,
        },
      },
      handler(ctx) {
        console.log('date is correct!', ctx.params.birthdate);
      },
    },
  },
});

broker
  .start()
  .then(() => broker.call('test.checkDate', { birthdate: '2000-01-01' }))
  .catch(() => console.log('2000-01-01 date is incorrect'))
  .then(() => broker.call('test.checkDate', { birthdate: 'asdf' }))
  .catch(() => console.log('asdf is invalid date format'));
```

**Comment by AndreMaz** [comment]
I don't fully understand what do you mean by:
>I tried to add custom validation to fastest-validator schema and set to ServiceBroker.

`fastest-validator` is the default validator and it's enabled by default so your code snippet can look like this:
```js
const { ServiceBroker } = require('moleculer');

const broker = new ServiceBroker(); // fastest-validator is enabled by default
```

**Comment by ilnuribat** [comment]
I want to add custom validation, date validation via moment js.
So, the next step was to create instance of fastest validator and do this line
'v.add('momentDate', ...'

**Comment by ilnuribat** [comment]
the problem is that moleculer uses not fastest-validator, but wrapped one, ParamValidator, that has init method.
https://github.com/moleculerjs/moleculer/blob/master/src/service-broker.js#L21 - require validator, 
https://github.com/moleculerjs/moleculer/blob/master/src/validator.js - that is wrapped validator.
So, its impossible just use customized fastest-validator, I must also wrap as `./src/validator.js`
May be it should be documented?

**Comment by AndreMaz** [comment]
[The Joi example](https://moleculer.services/docs/0.13/validating.html#Create-a-Joi-validator) shows that you should extend the BaseValidator class with your custom `constructor`, `compile` and `validate` methods (the `init` method is inherited).  So you should do exactly the same with any custom validation (including custom fastest validator).

But I'll think about how to make things clearer in docs
