### ISSUE TITLE
db adapter issue - can't perform textual search with "list"

### ISSUE THREAD

**Issue by hawkins48b** [moleculerjs/moleculer#585]
## Prerequisites
- mongo db with index for textual search
- moleculer-db
- moleculer-db-adapter-mongo

Create a collection with basic data
```
broker.call('users.create', {
  username: "user01",
  name: "awesome user"
}).then(res => console.log(res));
```

## Current Behavior
Perform a textual search with method 'list' 
```
broker.call('users.list', {
  search: "awesome",
  searchFields: ["name"]
}).then(res => console.log(res));
```
goes 
```
{
  name: "TypeError"
  message: "Converting circular structure to JSON"
  code: 500
}

```

**Please note that the method 'find' works like a charm.** 

## Expected Behavior
Method 'list' should give the same results as 'list' plus the paging data. 

As stated by the documentation, list should be able to perform a textual search : https://moleculer.services/docs/0.13/moleculer-db.html#list

I found out that the base adapter (memory) works. It is related to mongo.
As a workaround, I use the 'find' method and perform the pagination myself. 

## Steps to reproduce
- perform a textual search with method 'list'

I made a repository with the issue and steps to reproduce : 
https://github.com/hawkins48b/moleculer-issue-dbadapter

## Context
- moleculer 0.13.9
- moleculer-db 0.8.2
- moleculer-db-adapter-mongo 0.4.4
- moleculer-web 0.8.5
- NodeJS version: 10.3
- Operating System: Alpine Linux  (run in a docker container on Ubuntu 18.04)

**Comment by intech** [comment]
@hawkins48b relate to https://github.com/moleculerjs/moleculer-db/issues

**Comment by hawkins48b** [comment]
Sorry, I reopened the issue on the right repo https://github.com/moleculerjs/moleculer-db/issues/122
