### ISSUE TITLE
Node created in expressjs can not see node created by Moleculer Runner

### ISSUE THREAD

**Issue by nicolasxu** [moleculerjs/moleculer#587]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior
Node created in expressjs can not see node created by Moleculer Runner
But node created by Moleculer Runner can see node created in expressjs.

## Expected Behavior
the 2 nodes can see each other

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. use molecuer runner to create a node
2. create a node in expressjs code
3. use repl() in both situation

### Reproduce code snippet

```js
    // this is the code I use to create node in expressjs
const { ServiceBroker } = require('moleculer')

let broker = new ServiceBroker({
  // namespace: "room1",
	// nodeID: 'backend_node_333',
	transporter: "nats://localhost:4222",
  })

broker.createService({
  name: "mathNick",
  actions: {
    async add(ctx) {
      // let result = await ctx.call('account.test')
      console.log('mathNick.add called')
      return 'mathNick.add echo'

    }
  }
})

broker.start()
broker.repl();
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.9
* NodeJS version: v11.2.0
* Operating System: MacOS

### Failure Logs
```

```

**Comment by icebob** [comment]
Please show a full reproduction code with expressjs side.
