### ISSUE TITLE
Moleculer Runner Daemon problem

### ISSUE THREAD

**Issue by Eve-node** [moleculerjs/moleculer#592]
How w can I achieve process daemon using Moleculer Runner? Do I have to use docker? Doesn't seem to work with pm2??

**Comment by icebob** [comment]
It can also work with pm2. [Use this form](https://moleculer.services/docs/0.13/faq.html#How-can-I-start-services-with-Moleculer-Runner-in-debug-mode)

**Comment by Eve-node** [comment]
thank you
