### ISSUE TITLE
Breaking changes in version 0.14.0 and roadmap.

### ISSUE THREAD

**Issue by sizovilya** [moleculerjs/moleculer#601]
Hello guys.
We are (me and my team) going to move our architecture to moleculer. We have checked documentation and found the phraze:

> Until Moleculer reaches a 1.0 release, breaking changes will be released with a new minor version. For example 0.13.1, and 0.13.4 will be backward compatible, but 0.14.0 will have breaking changes.

After reading this phraze we began to doubt use moleculer now or wait for 0.14.0. 
Is it possible to answer for a couple simple questions for us ? 

Questions:
1) What breaking changes will be in 0.14.0 ? 
2) Where we can find moleculer roadmap ?

**Comment by vardanator** [comment]
I second that!

**Comment by intech** [comment]
@sizovilya https://github.com/moleculerjs/moleculer/releases/tag/v0.14.0-beta1

**Comment by intech** [comment]
Simple roadmap: https://github.com/moleculerjs/moleculer/projects/5

**Comment by sizovilya** [comment]
@intech thx!

**Comment by icebob** [comment]
@sizovilya 0.14 beta is available. Stable 0.14 will be released at the end of October.

**Comment by sizovilya** [comment]
@icebob thx!

**Comment by MR-omid** [comment]
@icebob can i start project with this beta version?  
project template is compatible with 0.14?

**Comment by icebob** [comment]
Yes, the template is made for 0.13 but compatible with 0.14 as well. After init, you should update the packages with `npm i moleculer@next moleculer-web@next --save`
