### ISSUE TITLE
Documentation - v0.14

### ISSUE THREAD

**Issue by arthurgermano** [moleculerjs/moleculer#602]
## Prerequisites
Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version - **0.14.0-beta5**
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

Hi.. sorry post it here.. I know it is not the channel, but it the website I would like just to add this comment and I did not find where so here it goes:

Just the documentation is a little bit wrong, but I found the solution. 
So just to help I am posting the problem here.

In the page [new custom gauge metrics](https://moleculer.services/docs/0.14/metrics.html#New-metric-registration)
To define a new custom gauge metrics, it states like the following: 
`this.broker.metrics.increment("posts.total", 1, { userID: ctx.params.author });`

But actually it should be:
`this.broker.metrics.increment("posts.total", { userID: ctx.params.author }, 1);`

Anyway, sorry again to post it here. 

Cheers!

**Comment by icebob** [comment]
Thanks, you are right. The docs example is not correct. We will fix it.

**Comment by AndreMaz** [comment]
Closing. Fixed in https://github.com/moleculerjs/site/commit/c5bac11e21c1ebc1aa0cb8ec306051a9d33bf825
Thanks 👍
