### ISSUE TITLE
0.14.0 beta - servicebroker instances not being reclaimed by GC due to tracing and metrics

### ISSUE THREAD

**Issue by kthompson23** [moleculerjs/moleculer#609]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

After upgrading to the latest beta, 0.14.0-beta5 our CI pipeline began failing due to JavaScript heap out of memory errors.

We use Jest for testing and our tests are setup so that for each test suite we create an instance of ServiceBroker and then using that broker instance create the services to test. After each test we call `serviceBroker.destroyService` and at the end of the test block call `serviceBroker.stop` to cleanup. Looking at heap snapshots in the Chrome memory profiler we can see that the service broker instances are not being freed even though they go out of scope. This was not the case when using Moleculer 0.13.0.

## Expected Behavior

Instances of the ServiceBroker should be freed once the test completes and the instance goes out of scope and all cleanup (`destroyService` and `serviceBroker.stop`) have been run.

## Failure Information

I identified three sources of this memory leak. Fixing all three of these causes the ServiceBroker instances to be freed and the memory reclaimed by the garbage collector.

1. metrics/common.js
```js
try {
	gc = (require("gc-stats"))();
} catch (e) {
	// silent
}
```
Invoking this module results in ServiceBroker instances being held by `system/Context`
Merely importing it does not cause the memory leak.

2. service-broker.js
```js
this.tracer = new Tracer(this, this.options.tracing);
```
Calling the constructor results in ServiceBroker instances being held by `AsyncStorage`.

3. service-broker.js
```js
this.scope = new AsyncStorage(this);
this.scope.enable();
```
This also results in ServiceBroker instances being held by `AsyncStorage`
Calling `this.scope.stop()` as part of `serviceBroker.stop` fixed this memory error.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create an instance of ServiceBroker
 - we have metrics and tracing set to false 
 - NODE_ENV='test'
2. Create services using the ServiceBroker
3. Let ServiceBroker instance go out of scope.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.0-beta5
* NodeJS version:  10.15.1
* Operating System: Linux/Windows
* Testing library: Jest

**Comment by kthompson23** [comment]
I'm not sure if this a problem in production where one service broker is created. It is a problem in a test suite though where many service brokers may be created. 

I think the fixes are reasonably simple so if you agree I can make a PR.
1. Only invoke the `gc` function if the require succeeds and metrics are turned on.
2. Only create an instance of `Tracer` if tracing is enabled. Or call `tracer.scope.stop()` as part of the service broker's stop method.
2. Call `this.scope.stop()` as part of the service broker's stop method.

**Comment by kthompson23** [comment]
We also had questions about the `store` map in `AsyncStorage`. Is there a concern that this will fill up indefinitely? Does it somehow get purged?

**Comment by icebob** [comment]
Thanks!

1. It should work as you wrote.
https://github.com/moleculerjs/moleculer/blob/de6c167a62ec019506dfbb383742e292dc457806/src/metrics/commons.js#L143
2. It is not available because core modules should able to create spans when the user disable tracing as well. It will cause big overhead if everywhere need check that tracing is enabled. The spans will be dropped so I don't think it cause memory leak. On the other hand, I'm using 0.14 beta in a real project with disabled metrics & tracing and no memory leak. It runs for weeks with the same memory usage.

3. It can be a problem. Could you create a fix PR?

`AsyncStorage`: the store is maintained in the `_destroy` method. It is called when a async thread is finished, so the `store` should store live async thread items.

**Comment by kthompson23** [comment]
@icebob I updated the title of the issue since I don't think ServiceBroker has a memory leak. More accurately, our test suite has a memory leak due to ServiceBroker instances being held.

1. The problem is where gc-stats is imported.
https://github.com/moleculerjs/moleculer/blob/de6c167a62ec019506dfbb383742e292dc457806/src/metrics/commons.js#L25

It's getting invoked immediately. Maybe something like this?
```js
try {
	gc = require("gc-stats");
} catch (e) {
	// silent
}
...
function startGCWatcher() {
	/* istanbul ignore next */
	if (gc) {
                // invoke if successfully imported.
		gc();
```

I'm not sure how my change would work if node-gyp couldn't build gc-stats. Does the require fail or the first invocation? Or perhaps wrap the require block in an environment variable?

2. I didn't realize that tracing was used that way. 
I could call `this.tracer.scope.stop()` in `serviceBroker.stop`. This fixed the memory leak in our test suite. I would enable it in `serviceBroker.start` along with `this.scope.enable()` if necessary.

**Comment by icebob** [comment]
1. We can move this require into the `startGCWatcher` function inside. The gc-stats is an optional dependency. So if node-gyp can't build id, the built-in metrics won't use it.
On the other hand I consider to remove it and event-loop-stats from the optionalDependency because it can cause other problems as well. And if someone need, it should be installed manually.

2. The problem is that, ServiceBroker should work if you call the stop & start again. But the `tracer.scope.start` is called in ServiceBroker constructor. So if you call the `broker.stop`, it will stop the scope, but `broker.start` won't start it again. I should check that we can move the `scope.start()` into the `broker.start()`. If it works, there will be a side-effect that you can't use tracing in the `created` hooks in service, middleware...etc.

**Comment by kthompson23** [comment]
I've been working on a PR but your last statement about 'side-effects' left me confused about the purpose of the broker. If broker.stop is called then all services are stopped, cacher cleared, incoming requests blocked, etc. With the broker stopped it doesn't seem like anything that could be captured in a span could occur including a service's created hook and middleware. So wouldn't it be safe to enable the tracer's scope in the broker's start lifecycle if it had been disabled in the broker's stop method? 

I was thinking about adding two methods to the tracer class; `enableScope` and `disableScope`. `enableScope` would be a no-op if scope was already enabled. So the Tracer constructor would still enable scope. The Service broker's constructor would create continue to create the Tracer instance and call tracer.init. I'd call `this.tracer.enableScope()` in the broker's start method and call `this.tracer.disableScope()` in the broker stop method.

What do you think?

**Comment by icebob** [comment]
Good idea!

**Comment by icebob** [comment]
Are you working on it? Or do you need help?

**Comment by kthompson23** [comment]
@icebob Sorry for the delay in getting a PR to you.

The new builtin tracing and metrics are awesome. I hooked up Prometheus a few days ago and we're excited to start adding our own custom metrics and to connect everything to Grafana. I also turned on tracing to test my changes and even though it was just emitting to the console it was really cool to see the flow of our services. We have a todo to hook this up to probably Jaeger next year.

Moleculer is awesome.

**Comment by icebob** [comment]
@kthompson23 no problem. Thank you for your contribution.

I'm glad that you like the new features. Yeah, the console tracer is a good tool during development to check the performance & calling chains.
Next weeks I will add the new metrics with Prometheus to my projects, so I want to create a common Moleculer Grafana dashboard which shows the most common Moleculer metric values.

**Comment by kthompson23** [comment]
That would be great. Grafana is tricky to get setup initially.
