### ISSUE TITLE
Add a benchmark to compare performance with `micro`

### ISSUE THREAD

**Issue by jeremyjs** [moleculerjs/moleculer#613]
micro is the most popular microservice option and while it is bare in features and plugins, I would like to see a benchmark to compare it to Moleculer in particular.

https://github.com/zeit/micro

Popularity: https://www.npmtrends.com/cote-vs-seneca-vs-micro-vs-nanoservices-vs-moleculer

**Comment by pibi** [comment]
I've used micro for a large microservie based product recently and I would say that this would not be a fair comparison. Micro should be compared to express/hapijs/koa as it is basically more an http framework than a full featured microservice platform like moleculer. Moleculer is way more "fast" if you look at the development speed, it has all the batteries you would have to code in micro (e.g. the requestId propagation, built in loggers, etc etc)

That said, I'm very pleased to see moleculer taking the lead over seneca in such a small timeframe. keep up the good work @icebob and team!

**Comment by icebob** [comment]
I totally agree with @pibi. `micro` is not a microservice framework, it's just a small HTTP engine without service discovery, service registry and fault-tolerance features. Adding to the compare is not relevant.

Thanks @pibi, yes we could beat the seneca on the NPM what is awesome. It is a very positive feedback from the community.

**Comment by davidnussio** [comment]
Fastify has a tool to benchmark http frameworks and it has published a large comparation list on github README pahe https://github.com/fastify/benchmarks/blob/master/README.md
