### ISSUE TITLE
Share $secureSettings with mixins

### ISSUE THREAD

**Issue by MaciekLeks** [moleculerjs/moleculer#618]
There is no pattern to share $secureSettings with mixins. I'd like to share e.g auth info with my mixin and not to worry about how to secure these data 

I've tried expose $secureSettings with private method from the service to my mixin, but it thows an error as if it was exposed directly via `this.settings.<my_secure_data>`.

If there is a way to bypass the issue, please share it with me.

**Comment by AndreMaz** [comment]
Hey @MaciekLeks  Sorry but I don't fully understand what is the desired behavior

Can you elaborate a little bit more?

**Comment by MaciekLeks** [comment]
Sure. Imagine a mixin which helps you with connecting, logining-in in remote server. Having look at db mixins all connection data (including username, password) are given in plain text in adapter constructor. I do not like this approach. I'd like to hide username, password, token in $secureSettings in my service giving the access to that data only to mixins assign to the schema. Is that still unlear?

**Comment by AndreMaz** [comment]
Ok I think I understand what you want.
Have you considered something like this?
```js
// user.service.js
const DBMixin = require("../mixins/db.mixin");

module.exports = {
  name: "user",

  mixins: [
    DBMixin({
      password: "my-pass", // or process.env.PASSWORD
      collection: "collection" // or process.env.COLLECTION
    })
  ]
};
```

```js
// db.mixin.js
const DBService = require("moleculer-db");
const path = require("path");

module.exports = opt => {
  return {
    mixins: [DBService],
    adapter: new DBService.MemoryAdapter({
      filename: path.join("data", `${opt.collection}.db`)
    })
  };
};
```

**Comment by MaciekLeks** [comment]
I've considered the idea. It does the job. Thank you.
