### ISSUE TITLE
Typescript type check error break hot reload

### ISSUE THREAD

**Issue by NickClark** [moleculerjs/moleculer#622]
## Current Behavior

If a typescript file is saved with any syntax or type error, the dev runner will throw an error (as expected), but after the error is resolved, the reload fails to pick it up again. Compare this to a runtime error, which correctly restarts when a file is saved.

## Expected Behavior

It should reload the service even after type errors.

### Steps to Reproduce

1. Create a new project using any Typescript template
2. Edit a service, leaving a type error behind.
3. Save... 💥 

### Context

* Moleculer version: 0.13 or next
* NodeJS version: 10.15
* Operating System: macOS 10.13.6

**Comment by icebob** [comment]
Fixed in https://github.com/moleculerjs/moleculer/commit/d075f072a8f12101e4ba596bf8e1225dbf8c2617
