### ISSUE TITLE
Kafka Transporter Stable release

### ISSUE THREAD

**Issue by orbelink** [moleculerjs/moleculer#625]
Hey Guys, hope you are doing well,

Question, when do you think the Kafka transporter is going to be stable?

I love the project and I follow all your work, I did some cool stuff with moleculerjs but I really want to use Kafka in production.

Kind Regards,
Leonardo Monge García.

**Comment by intech** [comment]
@orbelink for the transport of kafka, not all the possibilities of kafka are realized. I think that this is the only reason.
It would not be bad to use kafka stream and everything related to queues, balancing and sharding, but this will require significant changes of the transport system in moleculer

**Comment by icebob** [comment]
Kafka transporter will be stable status in the Moleculer 0.14.
However, as @intech said, it doesn't use all Kafka features, just using it as a pub-sub message broker to transfer Moleculer packets.
