### ISSUE TITLE
"onError" hook in action schema

### ISSUE THREAD

**Issue by erfanium** [moleculerjs/moleculer#627]
As far as I know, the only way to catch action errors is by defining an after-hook in service schema, I think at times it can be problematic, for example, I define service actions, events, methods ... in separate files as modules, but I can't define action hooks in the actions module.

My solution is like this:

```js
module.exports = {
  name: 'myService',
  actions: {
    myAction: {
      name: 'myAction',
      handler(ctx){
        /// code
      },

      onError(error , ctx){
        /// called if action throws an error (Error can be in handler or validator or ... )
      }
    }
  },
};
```
I think this solution is much cleaner and rational than current action hooks

**Comment by icebob** [comment]
In the next 0.14 version, you can define actions hooks inside action definition. 
https://moleculer.services/docs/0.14/actions.html#Action-level-declaration

**Comment by erfanium** [comment]
@icebob Very good, I didn't know that, but I think in this usage (catching error), using "onError" method is much easier and fluent instead of defining after hook and checking is there any error ...
