### ISSUE TITLE
HTTP responses enhancements.

### ISSUE THREAD

**Issue by SushKenyNeosoft** [moleculerjs/moleculer#641]
As we have `Errors` class from `moleculer-web` like NotFoundError, BadRequestError?

Do we have all the HTTP errors?

For example, I needed 409 conflict error, 403 forbidden, 413 Entity too large, etc.

Is there any way to extend HTTP Error and create our own errors?

I also wanted to send response status 201 after creating a new entity is it possible to do so? If yes then how can we do it?

**Comment by molobala** [comment]
Hello,

Check this section in the [documentation](https://moleculer.services/docs/0.13/moleculer-web.html#Response-type-amp-status-code) to change status code and status message.

You can also use MoleculerClientError for different error message and code from you service actions

```js
const {
	MoleculerClientError
} = require("moleculer").Errors;
if (!user) throw new MoleculerClientError("Vous sembé ne pas être connecté", 401);
```

**Comment by AndreMaz** [comment]
What @molobala said is correct. 
Status code with Moleculer Error
![image](https://user-images.githubusercontent.com/9802754/64023858-0f2db300-cb31-11e9-8769-e51fefc9036b.png)

Status code with `ctx.meta.$statusCode`
![image](https://user-images.githubusercontent.com/9802754/64024616-b5c68380-cb32-11e9-80cc-a5cf197b832d.png)
