### ISSUE TITLE
[TypeScript] Generic Context error

### ISSUE THREAD

**Issue by nnqq** [moleculerjs/moleculer#642]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

```
Types of parameters 'ctx' and 'ctx' are incompatible.
  Type 'Context<GenericObject, GenericObject>' is not assignable to type 'Context<WelcomeParams, GenericObject>'.
    Property 'name' is missing in type 'GenericObject' but required in type 'WelcomeParams'.
```

## Expected Behavior

No TS errors

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use generic `Context` with params `Context<{ name: string; }>`
3. TS error `ctx` incompatible with `ctx`

### Reproduce code snippet

TS sandbox link, error on line 15 https://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbzgYQgOxgUwB4wDRwDKmUAbsAMaYHFmWYBCUEA1iXAL5wBmzIcAchAQANpgoBXMVAEBuAFDzgGEtwCGVOAHVMIihBCYACmqhqQAZ0Ty4tuGnOYAXHAswoygOYKOimAE8wTG1dfUMAJUwLSDQLYIBeV3cvWThFChE1CysAWVFxKRJacioAUWxzMDE4HCw0ABMrYvprOzh9WPcJChhoAAoAI2Y2KBdmqiZWEgBKVra7CwkgqEHhmYUbedsYAAtgCwA6MFM48cxCCh3MEDU+hE2ttodDFyF8yWkAWji6Kk+cSpiAR4B6PWwaGDAdAWFz3MFggDuoQMzjm8PhOzUDWkLl2+wOSL0KJB6K2HBJpPJoLaHGmChpijaYAkAxElDghLCmD6PWwLlQKlwAB4dETDCYzJYAHzTFyirmRaLQ4Jwx4dNyIeyOThwRK8o6mcwWDZgqCYGASKBoOAAA3lxLgABIEM9MBwbfS7L5fPIcJBYHB6ph1FJ4HkxB8iiQSphyoDMAogA

```ts
import { Context, Service, ServiceBroker } from 'moleculer';

interface WelcomeParams {
    name: string;
}

type WelcomeResponse = string; 

class MoleculerServiceExample extends Service {
    constructor(broker: ServiceBroker) {
        super(broker);

        this.parseServiceSchema({
            name: 'moleculer-service-example',
            // TS error here
            actions: {
                welcome: {
                    handler: this.welcome,
                },
            },
        });
    }

    public welcome(ctx: Context<WelcomeParams>): WelcomeResponse {
        const { name } = ctx.params;

        return `Welcome, ${name}`;
    }
}

export default MoleculerServiceExample;
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* TypeScript version: 3.7.4
* Moleculer version: 0.13.12
* NodeJS version: 12.13.1
* Operating System: macOS 10.15.2

### Failure Logs
```
(property) Moleculer.ServiceSchema<Moleculer.ServiceSettingSchema>.actions?: Moleculer.ServiceActions | undefined
Type '{ welcome: { handler: (ctx: Context<WelcomeParams, Moleculer.GenericObject>) => string; }; }' is not assignable to type 'ServiceActions'.
  Property 'welcome' is incompatible with index signature.
    Type '{ handler: (ctx: Context<WelcomeParams, Moleculer.GenericObject>) => string; }' is not assignable to type 'Action | ActionHandler<any>'.
      Type '{ handler: (ctx: Context<WelcomeParams, Moleculer.GenericObject>) => string; }' is not assignable to type 'Action'.
        Types of property 'handler' are incompatible.
          Type '(ctx: Context<WelcomeParams, GenericObject>) => string' is not assignable to type 'ActionHandler<any>'.
            Type '(ctx: Context<WelcomeParams, GenericObject>) => string' is not assignable to type '(ctx: Context<GenericObject, GenericObject>) => any'.
              Types of parameters 'ctx' and 'ctx' are incompatible.
                Type 'Context<GenericObject, GenericObject>' is not assignable to type 'Context<WelcomeParams, GenericObject>'.
                  Property 'name' is missing in type 'GenericObject' but required in type 'WelcomeParams'.(2322)
input.ts(4, 5): 'name' is declared here.
input.ts(31, 1): The expected type comes from property 'actions' which is declared here on type 'ServiceSchema<ServiceSettingSchema>'
```

**Comment by shawnmcknight** [comment]
This issue was resolved in the beta release via #626 via [this edit](https://github.com/moleculerjs/moleculer/pull/626/files#diff-b52768974e6bc0faccb7d4b75b162c99R35).

This occurs only with TS option for `strictFunctionTypes` enabled which I have personally disabled in my projects as it seems to be a hyper-aggressive option that I don't believe provides a ton of utility.

So potential solves here are:

1. Disable `strictFunctionTypes`
2. Upgrade to beta release
3. Backport that type change to master

**Comment by AndreMaz** [comment]
Thanks @shawnmcknight

**Comment by nnqq** [comment]
@shawnmcknight Thank you. I made small fix and open PR https://github.com/moleculerjs/moleculer/pull/643
