### ISSUE TITLE
Typescript typings missing 'hooks' in ServiceSchema

### ISSUE THREAD

**Issue by JoshGlazebrook** [moleculerjs/moleculer#644]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior
It appears the typescript typings in master do not ever mention the keyword `hooks` at all in index.d.ts.

**Comment by icebob** [comment]
Could you create a fix PR?
