### ISSUE TITLE
Allow broker to watch for events

### ISSUE THREAD

**Issue by srosset81** [moleculerjs/moleculer#645]
**Is your feature request related to a problem? Please describe.**
I'm doing integration tests over multiple Moleculer services, some of them being called through the events system. The problem is that I need to wait for some of these events to have been sent before checking for the result.

Currently only services can watch for events. In order to allow the `broker` to wait for events, I've created a middleware like this:

```js
const EventsWatcher = {
  localEvent(next, event) {
    return function(payload, sender, eventName) {
      event.service.broker.latestEvent = eventName;
      return next(payload, sender, eventName);
    };
  },

  created(broker) {
    // Add a new method to broker object
    broker.watchForEvent = eventName => {
      return new Promise(resolve => {
        setInterval(() => {
          if (broker.latestEvent === eventName) {
            broker.latestEvent = null;
            resolve();
          }
        }, 100);
      });
    };
  }
};
```
This allows me to do [tests like these](https://github.com/assemblee-virtuelle/semapps/blob/2de382b180f56b0da8bec88d944238b1f6e801ac/src/middleware/boilerplates/runner/test/activitypub.test.js):

```js
describe('Posting to followers', () => {
  test('Post follow request', async () => {
    await broker.call('activitypub.outbox.post', {
      username: 'srosset81',
      '@context': 'https://www.w3.org/ns/activitystreams',
      actor: 'http://localhost:3000/activitypub/actor/srosset81',
      type: 'Follow',
      object: 'http://localhost:3000/activitypub/actor/simonLouvet'
    });

    // Wait for actor to be added to the followers collection
    await broker.watchForEvent('activitypub.follow.added');

    const result = await broker.call('activitypub.follow.listFollowers', {
      username: 'simonLouvet'
    });

    expect(result.items).toContain('http://localhost:3000/activitypub/actor/srosset81');
  }, 10000);
});
```

The setInterval is not very clean but it works. The problem is that _the `localEvent` method (or rather the function returned by this method) is only called if a service is listening to an event_. So if I want to watch for an event which is not being listened to, I need to add the event listener somewhere in a service, even if it does nothing.

**Describe the solution you'd like**
Maybe add a parameter to the broker which allows to send events even if there is no listener ? Or, better yet, implement a real `watchForEvent` method, so that the broker can listen for events (not only services like it is done now).

**Describe alternatives you've considered**
I've considered using the Metrics system, but the metrics-related events are calling never registered by the `localEvent` method of the middleware.

Thanks !

**Comment by icebob** [comment]
It will solve: https://github.com/moleculerjs/rfcs/issues/3
