### ISSUE TITLE
Allow customization of tracing span names

### ISSUE THREAD

**Issue by robodude666** [moleculerjs/moleculer#647]
**Is your feature request related to a problem? Please describe.**
The tracing functionality added in v0.14.0 has fixed names for actions: `action '${ctx.action.name}'` and events: `event '${ctx.eventName}' in '${service.fullName}'`.

When pairing the tracing feature with `moleculer-web`, you get a giant list of `api: action 'api.rest'` which isn't very descriptive.

Yes, you can usually filter down by tags, however, it would be nice to be able to customize the span name for each action/event.

**Describe the solution you'd like**
`moleculer` could offer these default templates, and within the `tracing` opts within each action/event we could specify a custom template. Would would allow the `moleculer-web`'s `rest` action to have a customized template that produces an output such as:

```
action 'api.rest' POST /articles
action 'api.rest' GET /articles/:id
```

**Describe alternatives you've considered**
Instead of the per action/event being a complete overwrite, maybe it's something that is appended to the current name:

```javascript
tracing: {
  tags: {
    params: true
  },
  spanName: ctx => `${ctx.params.req.method} ${ctx.params.req.url}`
}
```

**Comment by icebob** [comment]
Good idea, thanks!

**Comment by icebob** [comment]
Implemented in https://github.com/moleculerjs/moleculer/commit/1a2af85ec468d43c3e3e07097dd6069fc251fc20
Will be released in the next beta.
It can be a `String` or a `Function`.
```js
tracing: {
    spanName: ctx => `User access event in '${ctx.service.fullName}' service`
}
```
```js
tracing: {
    spanName: "Static span name"
}
```

**Comment by intech** [comment]
@icebob perfect, thanks!
