### ISSUE TITLE
Detecting Events since last time service ran?

### ISSUE THREAD

**Issue by robodude666** [moleculerjs/moleculer#648]
Is it possible to process/receive events that were published since the last time a service ran?

For example, say you have a `order` service and `fulfillment` service. For whatever reason, your `fulfillment` service crashes and doesn't automatically restart. The `order` service sends out a `order.created` event. At 2 AM you figure out the problem and get the `fulfillment` service back online. 

Will it automatically receive all events that were published since it was last online? If so, is this dependent on what transport is used?

**Comment by icebob** [comment]
No, the events are fire & forget. For these cases, use some [tasks queues].(https://github.com/moleculerjs/awesome-moleculer#tasks-queues-and-jobs)

**Comment by robodude666** [comment]
Would it be possible to have the events be pluggable like the transports are? For example, I could elect to use NATS transport for actions and ampq for events? This would allow your services to continue using the broker.emit/broadcast APIs but back it up with the functionality described above.

**Comment by icebob** [comment]
No, tt's not available. Multiple transporter using is not supported.

**Comment by robodude666** [comment]
Yeah, but wouldn't that be a cool feature? The ability to specify different transports for actions vs events? Could potentially address #83.

**Comment by lamanabie** [comment]
I am actually working on implementation of events since last service run - using bull ( distributed jobs and messages ), I want moleculer with event-driven architecture, that can use persistent retryable events. I will share my implementation, maybe even create module for this :) 

This is big topic and really depends what you expect from your event driven architecture.

**Comment by icebob** [comment]
It will solve it: https://github.com/moleculerjs/rfcs/issues/3
