### ISSUE TITLE
Redis client errors with batch commands (multi)

### ISSUE THREAD

**Issue by roberto-paes** [moleculerjs/moleculer#655]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

## Current Behavior

Hi.

I don't know if it's really a bug, as i'm using the embedded client to call redis directly, and it's not documented. When using embedded redis client to fire commands in batch mode (multi) the client from time to time returns a single "null". This behavior doesn't occurs if I switch to a new instantiated client. 

## Expected Behavior

Embedded client should execute multi commands correctly all times.

### Steps to Reproduce

1. Create a service and put this code on "started" function:

```js
// this.redis = new Redis("redis://redis:6379");
this.redis = this.broker.cacher.client;
setInterval(
      () =>
        this.redis
          .multi()
          .call("SET", "foo", "bar")
          .call("SET", "foo", "bar")
          .exec((err, results) => {
            console.log(err, results);
          }),
      500
    );
```
Ps.: The SET command is an example, in real life I want to call a module command.

2. The output will be like bellow, with errors from time to time ("null null" lines).
```js
null [ [ null, 'OK' ], [ null, 'OK' ] ]
null [ [ null, 'OK' ], [ null, 'OK' ] ]
null null
null [ [ null, 'OK' ], [ null, 'OK' ] ]
```
3. Switch the comment from line 1 to line 2 and observe the clean output.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.9
* NodeJS version: dubnium
* Operating System: ubuntu running docker image "node:dubnium-alpine"

**Comment by icebob** [comment]
You can't use the cacher client to send listing command because it is a pub-sub client.
