### ISSUE TITLE
v0.14.0-rc1 TypeError: Cannot read property 'hooks' of undefined 

### ISSUE THREAD

**Issue by deman4ik** [moleculerjs/moleculer#658]
## Failure Logs

Failed to load service '...' TypeError: Cannot read property 'hooks' of undefined
    at /node_modules/moleculer/src/service.js:647:40

### Steps to Reproduce
Version: v0.14.0-rc1
Service with mixin and action before hook

### Reproduce code snippet
[https://codesandbox.io/s/moleculer-sample-r4o32](https://codesandbox.io/s/moleculer-sample-r4o32)

**Comment by icebob** [comment]
Thanks, fixed. Please upgrade to rc2
