### ISSUE TITLE
Nats trying to reconnect when a i call broker.stop

### ISSUE THREAD

**Issue by reklatsmasters** [moleculerjs/moleculer#660]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed
- [+] I'm reporting the issue to the correct repository

## Current Behavior

I'm trying to implement greaceful shutdown in my app. When i call `broker.stop()` i see multiple messages `NATS client is reconnecting...` (sometimes after `BROKER: ServiceBroker is stopped. Good bye.`).

## Expected Behavior

Moleculer should not trying to reconnect when i want to stop it.

### Steps to Reproduce

* docker-compose up -d
* wait for success start
* docker-compose down

### Reproduce code snippet

```js
const broker = new ServiceBroker({
    logger: console,
    transporter: "nats://nats:4222",
	logLevel: 'INFO'
});

broker.createService({
    name: "test",
    actions: {
        empty(ctx) {
            return "Hello"
        }
    }
});

process.on('SIGTERM', async () => {
	console.log('stopping moleculer');
	await broker.stop();
	console.log('moleculer stopped'); // this message will never showed.
});
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: v0.12.8 and v0.13.12
* NodeJS version: v8.7.0
* Operating System: ubuntu

**Comment by icebob** [comment]
Try to disable process event handlers in ServiceBroker:

```js
const broker = new ServiceBroker({
    logger: console,
    transporter: "nats://nats:4222",
    logLevel: 'INFO',
    skipProcessEventRegistration: true
});

```

**Comment by reklatsmasters** [comment]
Unfortunately, it doesn't help.

**Comment by icebob** [comment]
The reproduce code snippet works for me.

**Comment by reklatsmasters** [comment]
I found the problem! This bug happened when moleculer service stopped before nats server. The solution is just add `nats` to `depends_on`:

```yml
services:
  nats:
    container_name: aom-nats
    image: nats:1.4.1-linux
  myservice:
	container_name: test
	depends_on:
      - redis
      - nats # <<<
```
