### ISSUE TITLE
Console and Event metric reporters are handling snapshot interval incorrectly.

### ISSUE THREAD

**Issue by JordanPawlett** [moleculerjs/moleculer#662]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

The documentation states that the interval for the Event reporter and Console reporter is given in milliseconds. However the `init` function call is handling the interval config option as if it were seconds. Leading to a hilariously long interval time. Giving the perception that the reporter is never firing.

https://github.com/moleculerjs/moleculer/blob/4282274cc8726dd386da8c9864687b6232807194/src/metrics/reporters/console.js#L52

https://github.com/moleculerjs/moleculer/blob/4282274cc8726dd386da8c9864687b6232807194/src/metrics/reporters/event.js#L52

## Expected Behavior

The interval should be treated as if the user specified config was given in milliseconds. There's no need to multiply by 1000.

Or, update the documentation to reflect that the expected input should be given in seconds, similar to how the DataDog reporter behaves.

### Context

* Moleculer version: v0.14.0-rc2
* NodeJS version: node:12.7.0-alpine
* Operating System: node:12.7.0-alpine

**Comment by icebob** [comment]
Thanks! The documentation is outdated, we will update it.
