### ISSUE TITLE
Redis cluster as transporter

### ISSUE THREAD

**Issue by AAfraitane** [moleculerjs/moleculer#669]
On a swarm cluster I would like to have a redis cluster (master, replicates and sentinels) as transporter

It would be nice to have the possibility of giving an array as transporter config option. 
With ioredis [Pub/Sub in cluster mode works exactly as the same as in standalone mode](https://www.npmjs.com/package/ioredis#pubsub-1)

So we will have in RedisTransporter class something like :

```
let clientSub: any;
if (Array.isArray(this.opts)) {
     clientSub = new Redis.Cluster(this.opts);
} else {
     clientSub = new Redis(this.opts);
}
```

Thanks for the great work (:

**Comment by icebob** [comment]
Good idea. Could you create a PR with it?
