### ISSUE TITLE
[Typescript] ActionCacheOptions incorrect interface declaration 

### ISSUE THREAD

**Issue by abdavid** [moleculerjs/moleculer#677]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior
Using the supplied config from the documentation (https://moleculer.services/docs/0.14/caching.html#Conditional-caching)
```
...
cache: {
  enabled: ctx => ctx.params.noCache !== true, //`noCache` passed as a parameter
  keys: ["name"]
},
...
```

Typescript will complain about `enabled` not being boolean due to the current ActionCacheOptions interface.

```
interface ActionCacheOptions {
		enabled?: boolean;
		ttl?: number;
		keys?: Array<string>;
		lock?: {
			enabled?: boolean;
			staleTime?: number;
		};
}
```

~~Also the type definition for generating custom cache keys with `keygen(...)` which was available in 0.13 seems to be missing, and not mentioned in the migration guide from 0.13 to 0.14. But this might have been moved to CacherOptions (👎 )~~

## Expected Behavior

I expect Typescript not to complain when using code examples from the documentation, and the definitions to be consolidated with current behaviour. 

## Failure Information

![Skjermbilde 2020-02-14 kl  11 20 25](https://user-images.githubusercontent.com/1027468/74522718-0b91bb00-4f1c-11ea-8b63-69878f1d19c5.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create moleculer boilerplate with ts support.
2. Add cache config to the greeter service/action and ensure that enabled is a function
3. Typescript errors due to incompatible declarations

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.1
* NodeJS version: 13.7.0
* Operating System: OS X
* Typescript: 3.7.4

### Failure Logs
```
[2020-02-14T10:02:52.131Z] ERROR local/BROKER: Failed to load service '/Users/davborre/Source/abo-api/services/benefit/benefit.service.ts' services/benefit/benefit.service.ts(22,5): error TS2322: Type '{ enabled(ctx: any): boolean; ttl: number; keys: string[]; }' is not assignable to type 'boolean | ActionCacheOptions'.
  Type '{ enabled(ctx: any): boolean; ttl: number; keys: string[]; }' is not assignable to type 'ActionCacheOptions'.
    Types of property 'enabled' are incompatible.
      Type '(ctx: any) => boolean' is not assignable to type 'boolean'.

[Runner] ⨯ Unable to compile TypeScript:
services/benefit/benefit.service.ts(22,5): error TS2322: Type '{ enabled(ctx: any): boolean; ttl: number; keys: string[]; }' is not assignable to type 'boolean | ActionCacheOptions'.
  Type '{ enabled(ctx: any): boolean; ttl: number; keys: string[]; }' is not assignable to type 'ActionCacheOptions'.
    Types of property 'enabled' are incompatible.
      Type '(ctx: any) => boolean' is not assignable to type 'boolean'.
 services/benefit/benefit.service.ts(22,5): error TS2322: Type '{ enabled(ctx: any): boolean; ttl: number; keys: string[]; }' is not assignable to type 'boolean | ActionCacheOptions'.
  Type '{ enabled(ctx: any): boolean; ttl: number; keys: string[]; }' is not assignable to type 'ActionCacheOptions'.
    Types of property 'enabled' are incompatible.
      Type '(ctx: any) => boolean' is not assignable to type 'boolean'.

```

**Comment by shawnmcknight** [comment]
It doesn't appear that the `enabled` flag was ever properly typed (0.13 or 0.14).  Can you submit a PR?

I'm not sure what you're referring to with a `keygen` regression between 0.13 and 0.14.  I don't see `keygen` referenced in the 0.13 types at all.  Can you clarify or submit a PR for your issue?

**Comment by abdavid** [comment]
Sure, I will have a look during the weekend. From the looks of it since `ActionCacheOptions` had the generic `[name: string]: any` it allowed adding a `keygen` property, which I now realise after looking into the cacher is actually not a thing, so that part of the discussion is void.
