### ISSUE TITLE
type based revive option to convert json data

### ISSUE THREAD

**Issue by veeramarni** [moleculerjs/moleculer#682]
**Is your feature request related to a problem? Please describe.**

We want to know if there is away we can provide `revive` option to `JSON.parse` so some objects or string can be converted into right way during deserialization of the json data, whether for `parameters response` or `data response`

**Describe the solution you'd like**

For example, we want to convert a string format of date to `Date` by using `revive` argument in the JSON.parse method.  

If we have leverage to add this `revive` option for specific `action` or `event` parameters also for `response` that gives more flexibility and voids double parsing. 

For example,

JSON.parse(stringOfJson, jsonDateParser);

**Comment by icebob** [comment]
You can cover it with a custom serializer.

```js
const JsonSerializer = require("moleculer").Serializers.JSON;

class MySerializer extends JsonSerializer {

    constructor(revive) {
        super();

        this.revive = revive;
    }

    deserialize(buf) {
        return JSON.parse(buf, this.revive)
    }
}

module.exports = {
    nodeID: "node-100",

    serializer: new MySerializer(function revive() {/*... */})
}
```

**Comment by veeramarni** [comment]
@icebob, does not work for `params`, is it something additional to be done `params`? I do need parameter to be revived before calling the handler.

**Comment by veeramarni** [comment]
It works, thanks
