### ISSUE TITLE
Balanced events arrived twice.

### ISSUE THREAD

**Issue by reklatsmasters** [moleculerjs/moleculer#687]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

I have 2 services - `users` and `clans`. When i send event `member.join.once` from the `clans` using `broker.emit()`, then i receive it twice on `users`.

## Expected Behavior

Event should be received 1 time.

### Steps to Reproduce

1. start 2 services using docker-compose
2. send an event on first service
3. receive in twice on second.

## Code

I use something like this to send event:

```js
function broadcast(event, data) {
	broker.emit(`${event}.once`, data);
	broker.broadcast(event, data);
}

//...

broadcast('member.join', {});
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.13 (other services may use other 0.12 or 0.13 versions)
* NodeJS version: 12.14.1
* Operating System: alpine

**Comment by icebob** [comment]
Please create a repro repo.

**Comment by reklatsmasters** [comment]
Update: I found out using wireshark that it's not a problem of moleculer. This problem related to nats or tcp stack.
