### ISSUE TITLE
Isolation of bad requests

### ISSUE THREAD

**Issue by abhisheksinha1601** [moleculerjs/moleculer#696]
**Is your feature request related to a problem? Please describe.**
I cannot find a way to efficiently debug a service which fails under certain input parameters. Currently the only way is to analyze logs.

**Describe the solution you'd like**
Re-driving of failed requests to certain transports (e.g. Dead Letter Queues) so that bad requests can be easily isolated and fixed. This is possible in case of queuing transporters, but I'm not sure of TCP one.

**Describe alternatives you've considered**
An alternative would be logging failed requests separately inside actions, but that would need logging every time. If someone misses implementing these logs, one would never know what actually is going wrong.

**Additional context**
Below are my use cases:
- I'm using moleculer for my API server, hence I need to isolate bad requests to fix the producers of those requests.
- I'll be using it for data syncing which includes transformation. Hence bad data can't be simply dropped.

**Comment by icebob** [comment]
It can be easy cover with a custom middleware:
```js
module.exports = {
    localAction(next, action) {
        return ctx => {
            return next(ctx).catch(err => {
                if (err instanceof XYZError) {
                    // Logging to file
                    // Send a mail with `ctx.params`
                    // Send a slack message
                    // Save to file the params to further analyzing
                    // ...etc
                }
            });
        }
    }
}
```
