### ISSUE TITLE
Heartbeats pollution problem 

### ISSUE THREAD

**Issue by giang12** [moleculerjs/moleculer#705]
**Is your feature request related to a problem? Please describe.**

Too many heartbeats from large number of services / instances of services..creating a pollution problem..N*N-1 scaling
So rn as I understand it, theres 1 heartbeats Q (I'm using NAT but assume other transporters behave same) for all services/instances to use. This simply works fine up to ~thousands of instances..but when scaling up to >10, 100 thousands instances...a couple problems arise:
1) serviceA spend most cpu time on heartbeat processing for all services connected to the transporter...(even the services that serviceA are not depended on and vice versa..)
2) disconnect/reconnection happen in cycle (from ServiceA Point of view: serviceB disconnected ->serviceB reconnected->serviceB disconnected ->serviceB reconnected...i.e connections thrashing)
3) Any pending requests from disconnected serviceB-inst1 will be discarded from ServiceA..even thought serviceB-inst1 is still indeed alive and processing the request and will be connected again shortly...(LOTS of 503 504 in case serviceA is the api-gateway) https://github.com/moleculerjs/moleculer/blob/cb4ceafaf8ad30bf6d5962999bc3d2cdb73a478f/src/registry/node-catalog.js#L290

Sort of like when we are shouting "I'm alive" in an alley with handful people...every one in the alley can still hear it..but then when we shout "I'm alive" in middle of Time Square with flood of other people doing the same..you can only hear the closest people to you at most..not others far away...

These problems can somewhat be alleviated by decreasing heartbeat interval + increasing heartbeat timeout, but we can only adjust so much until it starts to affect responsiveness of the system; especially dynamic scaling env like k8s with **spiky** traffics
Even adding random factor to start up /heartbeat send as discussed here https://github.com/moleculerjs/moleculer/issues/402#issuecomment-526843439 only help so much..
**Describe the solution you'd like**

Separate the heartbeats Q, so that serviceA ONLY listen to heartbeats of services that it DEPENDs on..not every services/instances connected to the transporter..

**Describe alternatives you've considered**

Suggested solution above only solved the problem under the assumption that serviceA only depend on a small number of other services compared to total of services available..
This will not help api-gateway much..
So I'm just creating this ticket to start a discussion..
**Additional context**

I'm currently away from work (corona pls..) but will attached screen shots of tests if that will help..
Also this is somewhat related to ACL problem
https://engineering.linkedin.com/blog/2019/03/authorization-at-linkedins-scale

**Comment by icebob** [comment]
I've started to work on a solution which enables us to use an external service for service discovery. This service can be a Redis, Consul, etcd....etc.
In this case, the Moleculer nodes don't send DISCOVER, INFO and HEARTBEAT packets via transporter.

**Comment by icebob** [comment]
It's released.

**Comment by wuyuedefeng** [comment]
No Consul support
