### ISSUE TITLE
Need better understanding of the framework

### ISSUE THREAD

**Issue by Karnith** [moleculerjs/moleculer#708]
Hi, after reviewing the documentation, searching through issues and examining https://moleculer.services/docs/0.14/clustering.html, I have several questions. First I'd like to say that I really like this project and see a bright future for it.

Monolithic vs micro service architecture
I understand how the micro services architecture works, at a high level, though I don't understand some key points: 

- when using a micro service architecture does each node use or need a different port for the service it runs when encapsulated in a docker instance?

- how are the different nodes recognized by the service broker? For example, if each service is it's own project (I assume the nano template is used for this), how are these services added to a preexisting running deployment without having a service outage for entire system? Is it that each service not found on the other nodes needs an instance of service broker running then somehow they get registered with the running system? Would this then mean that there needs to be a main project with service broker that all other individual service nodes' brokers connect to?

- is it possible for each service to implement their own front end interface, like the project template used in the cli? If so would each service be able to control it's own routing that then would be merged with the routing of the entire system? An example of this would be a user service would have it's own web interface for user related interactions like updating profile, etc.

The above questions relate to each service being it's own docker instance and the services with their corresponding files being localized to their respective nodes (meaning that the service files are not on any other node than the one they belong to). When a new service is created, how is it then introduced into the system. Looking at the api.services example running on port 3000, this api service has a route of /api and the product service is added to this. If a different service node made with nano template is created, how could it then be integrated into the /api route yet contain it's own routing and asset.

I hope these questions make sense, I'm trying to sort out my understanding of the limitations of this framework and use it to it's full potential.

**Comment by AndreMaz** [comment]
Hi @Karnith 

The template project looks like this in docker deployment:

![1_rwvPhQ8liPWIsgZ6y5eFpg](https://user-images.githubusercontent.com/9802754/78069721-7abf5380-7392-11ea-8f22-fd11eeb10c01.jpeg)


> when using a micro service architecture does each node use or need a different port for the service it runs when encapsulated in a docker instance?

Nodes communicate with each other via broker (see picture above). So the only thing that need to know is the address and the port of the broker. This is done either in `moleculer.config.js` transporter variable or via env. variables. In docker deployment the latter is used. 

https://github.com/moleculerjs/project-demo/blob/050ca31ce5b585c58651863e74c0253847d3b6a1/docker-compose.env#L6

> how are the different nodes recognized by the service broker? For example, if each service is it's own project (I assume the nano template is used for this), how are these services added to a preexisting running deployment without having a service outage for entire system? Is it that each service not found on the other nodes needs an instance of service broker running then somehow they get registered with the running system? Would this then mean that there needs to be a main project with service broker that all other individual service nodes' brokers connect to?

Each Moleculer node has its own registry, which contains info about other nodes, services, actions, and events. Regarding the discovery: Moleculer implements dynamic discovery meaning that the nodes don’t need to know other nodes at start. When a new node starts, it will send information to other nodes that will use the incoming info to update their local service registry. In case of a node crash (or stop) other nodes will detect it and remove the affected services from their registry. This way the following requests will be routed to live nodes.

>  If a different service node made with nano template is created, how could it then be integrated into the /api route yet contain it's own routing and asset.

This is done via the service discovery and registry (see my previous answer). API gateway service dynamically builds the routes for new services. You can see it in action in the template project.
Run `npm run dev` and you will see that api gateway will build the routes for `greeter` and `products` service. If you run `destroy products` you will see that the API gateway will "find" out that greeter is offline and it will regenerate the routes.

![image](https://user-images.githubusercontent.com/9802754/78071996-4483d300-7396-11ea-93ca-6f5cb55281bb.png)


> is it possible for each service to implement their own front end interface, like the project template used in the cli?

The frontend in the project template is made for 2 services (`greeter.service.js` and `products.service.js`). 

Hope it helps.
PS: for questions please use Discord chat (link: https://discord.gg/TSEcDRP)
