### ISSUE TITLE
Stream error when using 0.14.5

### ISSUE THREAD

**Issue by faller** [moleculerjs/moleculer#711]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

It works fine when I'm using 0.14.4 before this pull request(https://github.com/moleculerjs/moleculer/pull/683)

## Failure Information

```
  Service.save (services/store.js:19:43)
  ServiceBroker.timeoutMiddleware (node_modules/moleculer/src/middlewares/timeout.js:35:14)
  ServiceBroker.fallbackMiddleware (node_modules/moleculer/src/middlewares/fallback.js:29:11)
  ServiceBroker.errorHandlerMiddleware (node_modules/moleculer/src/middlewares/error-handler.js:14:10)
  Transit.requestHandler (node_modules/moleculer/src/transit.js:431:30)
  Transit.messageHandler (node_modules/moleculer/src/transit.js:308:17)
  TcpTransporter.wrappedMessageHandler [as messageHandler] (node_modules/moleculer/src/transit.js:66:55)
  TcpTransporter.incomingMessage (node_modules/moleculer/src/transporters/base.js:117:16)
  TcpTransporter.receive (node_modules/moleculer/src/transporters/tcp.js:276:25)
  TcpTransporter.onIncomingMessage (node_modules/moleculer/src/transporters/tcp.js:261:15)
  Parser.<anonymous> (node_modules/moleculer/src/transporters/tcp/tcp-reader.js:100:21)
  Parser._write (node_modules/moleculer/src/transporters/tcp/parser.js:65:10)
```

### Reproduce code snippet

```js
const request = require( 'superagent' );
const stream = require( 'stream' );
const broker = new ServiceBroker({
    transporter: 'TCP'
    serializer: 'Notepack'
});

let file = 'http://';  // some file larger than 256KB
let buffer = ( await request.get( file ).buffer() ).body;
let readable = new stream.PassThrough(); 
readable.end( buffer );
let result = await broker.call( 'store.save', readable, { meta: { bucket: 'aaa' }});

```

```js
const broker = new ServiceBroker({
    transporter: 'TCP'
    serializer: 'Notepack'
});

broker.createService({
    name: 'store',
    actions: {
        async save( ctx ) {
            if ( !ctx.meta.bucket ) throw new Error( 422 );
        }
    }
});

```

### Context

* Moleculer version: 0.14.5
* NodeJS version: v12.16.1
* Operating System: macOS

**Comment by icebob** [comment]
@artur-krueger could you help with it? It seems some other thing has been changed after your streaming PR. Thanks in advance!

**Comment by artur-krueger** [comment]
Sure, I will take a look at it.

**Comment by artur-krueger** [comment]
I could reproduce the described issue and found a solution.
As a workaround you could set maxChunkSize to 0 in the meanwhile.

**Comment by edurdias** [comment]
I would suggest this ticket to stay open until the solution is implemented.
That allows other developers to track the changes as well.

**Comment by icebob** [comment]
The error is fixed & merged and will be released in the next days.
