### ISSUE TITLE
Cannot use custom logger config in typescript environment

### ISSUE THREAD

**Issue by zerocool-kor** [moleculerjs/moleculer#716]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [* ] I am running the latest version (0.14.6)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior
I'm trying to upgrade my application moleculer framework from 0.13 to 0.14.6.
But I can't transpile my typescripts in 0.14.6, because there is no way to define my custom logger interface.

## Expected Behavior
Need to supprt define custom logger class in typescript. 
https://moleculer.services/docs/0.14/logging.html#Custom-logger

## Failure Information

In nodejs, we can define custom logger interface under below (https://moleculer.services/docs/0.14/logging.html#Custom-logger)
```
// moleculer.config.js
 const BaseLogger = require("moleculer").Loggers.Base;

class MyLogger extends BaseLogger {
    getLogHandler(bindings) {
        return (type, args) => console[type](`[MYLOG-${bindings.mod}]`, ...args);
    }
}

module.exports = {
    logger: new MyLogger()
};
```

But in typescript with 0.14.6 moleculer, we can't define. Because there is only 3 types in BrokerOptions.logger interface, and there is no way to get ```BaseLogger``` class type. 
```
// index.d.ts in 0.14.6
	interface BrokerOptions {
...
		logger?: LoggerConfig | Array<LoggerConfig> | boolean;
        }
```

**Comment by erlichmen** [comment]
I think that the line need to chnage to from:

logger?: LoggerConfig | Array<LoggerConfig> | boolean; 

to

logger?: LoggerBase | LoggerConfig | Array<LoggerConfig> | boolean;

**Comment by icebob** [comment]
PR's welcome.
