### ISSUE TITLE
Is there a way to access logger outside service?

### ISSUE THREAD

**Issue by HighSoftWare96** [moleculerjs/moleculer#717]
**Is your feature request related to a problem? Please describe.**

I have some support classes that has not direct access to the context or to a service scope so if I want to log some message inside this classes I must pass the scope reference of a service inside the class in order to use the logger instance. Is there a way to do this differently without recurring to the `console.log`?

**Describe the solution you'd like**

I'd like to have an instance of the Moleculer logger accessible from anywhere in the code even if this requires to specify some context (like the service name or some other info that has to be printed out with the log).

**Describe alternatives you've considered**

1. Pass the context (not always possible) or the service scope to the support class
2. Use the `console.log` (incoerent with the rest of the project)

**Comment by icebob** [comment]
You can create a custom logger instance, so if you pass the ServiceBroker instance to your service, you can create it with `broker.getLogger("MyClass")`

**Comment by HighSoftWare96** [comment]
Ok, so I guess there is no way to access a logger without a reference to the broker or a service?

**Comment by icebob** [comment]
Yes

**Comment by HighSoftWare96** [comment]
Ok, so then there is no way. Thank you.
