### ISSUE TITLE
[TypeScript] mcall type definition missing for Context

### ISSUE THREAD

**Issue by Jank1310** [moleculerjs/moleculer#719]
## Current Behavior

`mcall` missing from Context type definition

## Expected Behavior

`mcall` typed for Context:

`mcall<T>(def: Array<CallDefinition> | { [name: string]: CallDefinition }): Promise<Array<T> | T>;`

**Comment by icebob** [comment]
Could you create a fix PR?

**Comment by Jank1310** [comment]
Sure 👍Am 16.04.2020 8:45 nachm. schrieb Icebob <notifications@github.com>:
Could you create a fix PR?

**Comment by Jank1310** [comment]
#723
