### ISSUE TITLE
 how to integrate Http client and server program in Moleculer?

### ISSUE THREAD

**Issue by meghnamishraa** [moleculerjs/moleculer#729]
I don't understand how to integrate molecular framework for communication between  Http client and server program in node js . I want to send msg from client to server and in response from the server to client in node js by using two brokers for HTTP server and client .can anybody has any idea?

**Comment by AndreMaz** [comment]
If you want to integrate an HTTP server with a moleculer services you can use [`moleculer-web`](https://moleculer.services/docs/0.14/moleculer-web.html). This will create an HTTP server that will be responsible for parsing the incoming HTTP requests and map them into [action](https://moleculer.services/docs/0.14/actions.html) calls. Regarding the HTTP client, you can use [`moleculer-http-client`](https://github.com/moleculerjs/moleculer-http-client) to make allow moleculer services to make HTTP calls to REST APIs. 

Both modules share the same idea. During the [`created()` and `start()`](https://moleculer.services/docs/0.14/lifecycle.html#Service-lifecycle) of a service you init an HTTP client or a server and then do whatever you want with them.

You can check this [example](https://github.com/moleculerjs/moleculer-http-client/blob/master/examples/stream-post/index.js). It has 2 services, 1 with HTTP client and another with HTTP server. The client service sends via HTTP a file to the server service that simply stores it.

Hope this answers your question.
PS: For questions please use [Discord](https://discord.gg/TSEcDRP)

**Comment by meghnamishraa** [comment]
Thank you @AndreMaz . But How to simple send a message to server and response back from server?
Sample code-
const { ServiceBroker } = require("moleculer");
const HTTPServer = require("moleculer-web");
const http=require("http");
// Create the broker for node-1
// Define nodeID and set the communication bus
const brokerNode1 = new ServiceBroker({
  nodeID: "nodenum-1",
  transporter: "TCP"
});

// Create the "gateway" service
brokerNode1.createService({
  // Define service name
  name: "gateway-service",

  // Load the HTTP server
  mixins: [HTTPServer],

  settings: {
     port:9000,
    routes: [
      {
        aliases: {
          // When the "GET /products" request is made the "listProducts" action of "products" service is executed
          "POST /products": "products.start_http_client"
        }
      }
    ]
  }
});

// Create the broker for node-2
// Define nodeID and set the communication bus
const brokerNode2 = new ServiceBroker({
  nodeID: "nodenum-2",
  transporter: "TCP"
});

// Create the "products" service
brokerNode2.createService({
  // Define service name
  name: "products",

  actions: {
    // Define service action that returns the available products
    start_http_client(){

      try{
  
         
  
          var keepAliveAgent1 = new http.Agent({ keepAlive: false, maxSockets: 2});
  
         
  
          var http_options = {
  
           host : "127.0.0.1",
  
              port : 9000,
  
              json : true,
  
              method : 'POST',
  
              agent : keepAliveAgent1,
  
              headers: {
  
                  'Content-Type': 'application/json',
  
              }
  
          };
  
         
  
          var httpreq=http.request(http_options,function(res){
  
             
  
              res.on('request',function(data){
  
              console.log("request client");
  
              });
  
             
  
              res.on('data',function(data){
  
                 
  
                  console.log("Data from server" +data);
  
              });
  
          });
  
         
  
         
  
         var req_data={
           "meghs":"njskz",
           "subhs":"kmsndkjm"
         }
  
          httpreq.end(JSON.stringify(req_data));
  
         
  
          httpreq.on('error',function(err){
  
              console.log("error event "+err);
  
              console.log("error event "+err.stack);
  
          });
  
                 
  
      }
  
      catch(err){
  
          console.log("error occured");
  
         
  
      }
  
    }}
});
Promise.all([brokerNode1.start(), brokerNode2.start()]);

**Comment by AndreMaz** [comment]
```js
const { ServiceBroker } = require("moleculer");
const HTTPClientService = require("moleculer-http-client");

// Create broker
let broker = new ServiceBroker({
  nodeID: "http-client"
});

// Create a service
broker.createService({
  name: "http",

  // Load HTTP Client Service
  mixins: [HTTPClientService],

  settings: {
    // Only GET the body of the response
    httpClient: { responseFormatter: "body" }
  }
});

// Start the broker
broker.start().then(() => {
  broker
    // Make a HTTP GET request
    .call("http.get", {
      url: "https://httpbin.org/json",
      opt: { responseType: "json" }
    })
    .then(res => broker.logger.info(res))
    .catch(error => broker.logger.error(error));
});
```

**Comment by meghnamishraa** [comment]
Yes, I had already checked with this but instead of this website I want my own customize http client to be implemented .In previous code the function start_http_client I want to include. That req_data should be sent to server and some "bye" msg should come back.

**Comment by meghnamishraa** [comment]
hii,
Yes, @AndreMaz <https://github.com/AndreMaz> I had already checked with
this but instead of this website I want my own customize http client to be
implemented .In previous code the function start_http_client I want to
include. That req_data should be sent to server and some "bye" msg should
come back.

**Comment by AndreMaz** [comment]
If you want to create your own client then use [`created()` and `start()`](https://moleculer.services/docs/0.14/lifecycle.html#Service-lifecycle) to create and configure it. After that just use it (e.g. `this.client.get(url, opts)`) within your actions.

**Comment by meghnamishraa** [comment]
how to implement this client?

const req = http.request(
  {
    host: 'localhost',
    port: '5000',
    path: '/posts',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    }
  },
  response => {
    console.log(response.statusCode); // 200
  }
);

req.write(JSON.stringify({
  author: 'Marcin',
  title: 'Lorem ipsum',
  content: 'Dolor sit amet'
}));

req.end();

**Comment by parveshh** [comment]
@meghnamishraa have a look at moleculer-web as @AndreMaz mentioned : https://moleculer.services/docs/0.13/moleculer-web.html
this lets you expose api endpoints.

**Comment by AndreMaz** [comment]
You need to promisify the `http.request`, i.e., wrap your call with a promise.  Quick search gives me the following links: https://stackoverflow.com/questions/38533580/nodejs-how-to-promisify-http-request-reject-got-called-two-times/38543075 and https://medium.com/@gevorggalstyan/how-to-promisify-node-js-http-https-requests-76a5a58ed90c

Once you do it just place your promisified HTTP call inside moleculer action and `resolve` or `reject` it according to the response that your client receives.

**Comment by meghnamishraa** [comment]
start_http_client(){



        try{







            var keepAliveAgent1 = new http.Agent({ keepAlive: false
, maxSockets: 2});







            var http_options = {



             host : "127.0.0.1",



                port : 9001,



                json : true,



                method : 'POST',



                agent : keepAliveAgent1,



                headers: {



                    'Content-Type': 'application/json',



                }



            };







            var httpreq=http.request(http_options,function(res){







                res.on('request',function(data){



                console.log("request client");



                });







                res.on('data',function(data){







                    console.log("Data from server" +data);



                });



            });











            httpreq.end("hii");







            httpreq.on('error',function(err){



                console.log("error event "+err);



                console.log("error event "+err.stack);



            });







        }



        catch(err){



            console.log("error occured");







        }



    }



}

Start-http-server

var http = require("http");

var ip = '127.0.0.1';

var port = 9001;

function start_http_server() {

    try {



        var server = http.createServer(function(req1,resp1) {

     var fullBody ="";

            req1.on('data',function(chunk){

                fullBody += chunk;



            });



            req1.on('end',function(){

                console.log("client data is simulator:"+fullBody);

                resp1.end("bye1");



         });





            req1.on("close", function() {

               console.log("close event");

           });



        });

        server.listen(port, ip, function() {

            console.log("HTTP Server (IP:"+ip+" PORT:"+port+
") is listening successfully");

        });



        server.on('error', function(err) {

            console.log("error - event in server "+err);

            console.log('error code :'+err.code);

        });



       server.on('close', function() {

           console.log("close - event in server");

       });



    } catch (err) {

        console.log("in catch - event "+err);

        }

}



start_http_server();





 How can I use Moleculer-web in between this to communicate between
http-server and http-client in different nodes

**Comment by meghnamishraa** [comment]
can we call 2nd node action from 1st node internally without any route?
