### ISSUE TITLE
Cant discovery local services without external network Interfaces;

### ISSUE THREAD

**Issue by Wallacy** [moleculerjs/moleculer#732]
That was trick. I have several micro-services running on the same machine, and i use the local TCP/udpBroadcast to interconnect then; Works fine, except if i have problems on our local network or install the software on a machine without network; (our services control attached hardwares on the machine, and doesn't need any network)

The problem is here:

```javascript
getBroadcastAddresses() {
		const list = [];
		const interfaces = os.networkInterfaces();
		for (let iface in interfaces) {
			for (let i in interfaces[iface]) {
				const f = interfaces[iface][i];
				if (f.family === "IPv4" && !f.internal) {
					list.push(ipaddr.IPv4.broadcastAddressFromCIDR(f.cidr).toString());
				}
			}
		}
		return list;
	}
```

The code does not connect to a loopback interface, because the `!f.internal`; My suggestion is make this configurable or just remove this restriction; Can I PR this?

**Comment by icebob** [comment]
Please change & test it that it works with local addresses as well (127.0.0.255) IF yes, please create a fix PR.

**Comment by Wallacy** [comment]
Did you prefer a configurable behavior or just disable the check? On my environment is working fine with 127.0.0.255;

**Comment by icebob** [comment]
Ok, if it works, just disable the check.
