### ISSUE TITLE
[lodash] Remove usage of _.isObject

### ISSUE THREAD

**Issue by abdavid** [moleculerjs/moleculer#739]
See #433 for context.

**Describe the solution you'd like**
Remove usage of `_.isObject` throughout Moleculer. 

**Describe alternatives you've considered**
Replacing with `Object.prototype.toString.call(x) === "[object Object]"` but that would be a more equivalent of `_.isPlainObject`, but not sure if `_.isObject` is used intentionally over `_.isPlainObject`

**Additional context**
https://github.com/moleculerjs/moleculer/search?q=_.isObject&unscoped_q=_.isObject

**Comment by icebob** [comment]
The `_.isObject` looks same as your suggestion:

```
> _.isObject([])
true
> _.isObject(() => {})
true
> _.isObject(Object.create(null))
true
> Object.prototype.toString.call(Object.create(null))
'[object Object]'
>
```

`_.isPlainObject` different it returns false for Array & Function

**Comment by icebob** [comment]
Need to check every place because it might be enough your alternative.

**Comment by abdavid** [comment]
I think we can come along way with checking on the `[object x]` type. 

```
const objectObjectType = "[object Object]";
const objectFunctionType = "[object Function]";
const objectArrayType = "[object Array]"
```

but `Object.prototype.toString.call(async ()=>{}) === "[object AsyncFunction]"` so we might need to think about that also

**Comment by Wallacy** [comment]
FWIW:

On my cods i usualy use:

```javascript
function isObject(item: any): boolean {
    return item && typeof item === "object" && !Array.isArray(item);
}
```

**Comment by icebob** [comment]
Thanks @Wallacy, good idea. Btw I never use the _.isObject to accept Function in Moleculer codes, so no need to check to function :)
