### ISSUE TITLE
[lodash] Remove usage of _.isString

### ISSUE THREAD

**Issue by abdavid** [moleculerjs/moleculer#740]
See #433 for context.

**Describe the solution you'd like**
Remove usage of `_.isString` throughout Moleculer. 

**Describe alternatives you've considered**
Should be replaceable with a `Object.prototype.toString.call(str) === "[object String]"`

**Additional context**
https://github.com/moleculerjs/moleculer/search?q=_.isString&unscoped_q=_.isString

**Comment by Wallacy** [comment]
Why not a simple `typeof a_string === 'string'` ?

**Comment by abdavid** [comment]
That will suffice also, I was merely contemplating a reusable objectType detetion pattern for all the other `isX` utilities, but since we didnt go that way a regular `typeof x === "string"` will certainly do the trick.
