### ISSUE TITLE
[lodash] Remove usage of _.isPlainObject

### ISSUE THREAD

**Issue by abdavid** [moleculerjs/moleculer#741]
See #433 for context.

**Describe the solution you'd like**
Remove usage of `_.isPlainObject` throughout Moleculer. 

**Describe alternatives you've considered**
Should be replaceable by `Object.prototype.toString.call(o) ==="[object Object]"`

**Additional context**
https://github.com/moleculerjs/moleculer/search?q=_.isPlainObject&unscoped_q=_.isPlainObject

**Comment by Wallacy** [comment]
```javascript
function isPlainObject(o) {
    return Object.prototype.toString.call(o) ==="[object Object]"
}

function Foo() {
   this.a = 1
 }

$ isPlainObject(new Foo)
true
```

If the ideia is match _.isPlainObject

```javascript
function isPlainObject(obj) {
  return obj!=null ? Object.getPrototypeOf(obj)===Object.prototype || Object.getPrototypeOf(obj)===null : false
}
```
```javascript
$ isPlainObject(null)
false
$ isPlainObject(new Foo)
false
$ isPlainObject([1, 2, 3])
false
$ isPlainObject({ 'x': 0, 'y': 0 })
true
$ isPlainObject(Object.create(null))
true
```

**Comment by abdavid** [comment]
Nice! Maybe you would want to create a PR for that? 👍

**Comment by Wallacy** [comment]
Okay, i can do that.
