### ISSUE TITLE
[lodash] Remove usage of _.isNaN

### ISSUE THREAD

**Issue by abdavid** [moleculerjs/moleculer#743]
See #433 for context.

**Describe the solution you'd like**
Remove usage of `_.isNaN` throughout Moleculer. 

**Describe alternatives you've considered**
So the difference between native and lodash isNaN is that lodash only returns true if the type is actually the `NaN` type. Not certain if this is necessary? Native `isNaN` returns true for `undefined` and other non-number values. 

**Additional context**
https://github.com/moleculerjs/moleculer/search?q=_.isNaN&unscoped_q=_.isNaN

**Comment by icebob** [comment]
Native is enough.
