### ISSUE TITLE
[lodash] Remove usage of _.assign

### ISSUE THREAD

**Issue by abdavid** [moleculerjs/moleculer#744]
See #433 for context.

**Describe the solution you'd like**
Remove usage of `_.assign` throughout Moleculer. 

**Describe alternatives you've considered**
Not sure if a regular `Object.assign` is sufficient here. Clarification/Testing needed. 

**Additional context**
https://github.com/moleculerjs/moleculer/blob/46b06d72771e9c14136bfcde2e0a4ece0af839f7/src/transit.js#L585

**Comment by abdavid** [comment]
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_assign

**Comment by icebob** [comment]
I've fixed it, be worth to mention that it works `_.assign(null,null) and returns `{}` but `Object.assign(null, null)` throws error.
