### ISSUE TITLE
Create a large number of services dynamically, the services are lost after 10 minutes

### ISSUE THREAD

**Issue by fouber** [moleculerjs/moleculer#765]
Hi, guys

My project needs to dynamically create multiple services to provide some resident services. When I create more than 200 services, these services start to be disconnected irregularly. I receive such a lot of warnings from other nodes:

```
Removing offline 'mainserver22-xxxx-xxx' node from registry because it hasn't submitted heartbeat signal for 10 minutes.
```

When I call the action of these services, it has a timeout error.

I saw this description in the documentation for the latest version (v0.14.7):

> Local discovery (default option) uses the transporter module to exchange node info and heartbeat packets (for more info about packet structure check Moleculer protocol). It’s the simplest and the fastest among the available discovery mechanisms as it doesn’t require any external solutions. However, this discovery method also has some drawbacks, especially for large scale deployments with >100 nodes. The heartbeat packets can generate large amount traffic that can saturate the communication bus and, therefore, deteriorate the performance of actions and events, i.e., slow down the delivery of request/response and event packets.

I wonder if the network congestion started after creating more than 200 nodes, as the discoverer I used is Local?

In the latest version, molecular has provided other discoveres, which is really great work, but it is still in the experimental stage, should I trust them in the production environment?

### Context

* Moleculer version: 0.14.0
* NodeJS version:  v10.16.0
* Operating System: CentOS 7

**Comment by intech** [comment]
@fouber local discovery depends on the transport used. Which one are you using?
Try using redis discovery for testing.

**Comment by fouber** [comment]
@intech 

I'm using NATS transporter.

Each time a service is dynamically created, a corresponding node will appear. When the node reaches more than 200, other nodes will receive the disconnected message very frequently, resulting in frequent restart of the service

**Comment by icebob** [comment]
Try to increment the `heartbeatInterval` and `heartbeatTimeout` options.

**Comment by fouber** [comment]
I finally got to the root of the problem. My service had a serious memory leak that caused it to exceed the pM2 single-process memory limit and was killed. The killed node fails to report its disconnect status in time, resulting in a timeout for the service call

Thank you so much for your replies @intech @icebob . What a great project moleculer is!
