### ISSUE TITLE
using secure JSON parser

### ISSUE THREAD

**Issue by erfanium** [moleculerjs/moleculer#766]
https://github.com/moleculerjs/moleculer/blob/8c728a3feea0c67cea34b77df1009ce97aed2d99/src/serializers/json.js#L49

It's better to use https://www.npmjs.com/package/secure-json-parse

**Comment by icebob** [comment]
Thanks, but I don't plan to change it, because serializer is used for inside transportation between nodes and doesn't parse data from "evil" users.

Nevertheless, if somebody needs it, it takes only 5 minutes to create a SafeJsonSerializer with this lib and set in broker options.

**Comment by erfanium** [comment]
@icebob How can I fix this from API gateway side? I read the API-Gateway codes, but seems it uses the core JSON parser.

**Comment by icebob** [comment]
Yes, API gateway uses [body-parser](https://github.com/expressjs/body-parser)
