### ISSUE TITLE
Error when connect Grafana to Prometheus in Moleculer

### ISSUE THREAD

**Issue by tienhien87** [moleculerjs/moleculer#768]
I use grafana to visualize metrics data from Prometheus in Moleculer. 
I use port 3030 for Prometheus:

metrics: {
        enabled: true,
        // Available built-in reporters: "Console", "CSV", "Event", "Prometheus", "Datadog", "StatsD"
        reporter: {
            type: "Prometheus",
            options: {
                // HTTP port
                port: 3030,
                // HTTP URL path
                path: "/metrics",
                // Default labels which are appended to all metrics labels
                defaultLabels: registry => ({
                    namespace: registry.broker.namespace,
                    nodeID: registry.broker.nodeID
                })
            }
        }
    },

But when configure data source in Grafana, an error "Failed to fetch" occurred!. 
Can you have me resolve issue?

**Comment by icebob** [comment]
The Prometheus provides metrics data for Prometheus server and not for Grafana.
