### ISSUE TITLE
How can I call an external api from an action

### ISSUE THREAD

**Issue by tonychangcheng** [moleculerjs/moleculer#773]
For example "https://postman-echo.com/get?foo1=bar1&foo2=bar2".  Do I use broker.call()?

**Comment by AndreMaz** [comment]
If you want to call an external API from you service then you need to implement a HTTP client. Check this: https://github.com/moleculerjs/moleculer-http-client#actions

`broker.call()` is for calling moleculer actions.

PS: for questions use Discord https://discord.gg/TSEcDRP
