### ISSUE TITLE
HTTP based transporter for communication between microservices

### ISSUE THREAD

**Issue by guddubit** [moleculerjs/moleculer#776]
Currently all the transporter supports either Message broker or TCP for communication between Nodes, can we use HTTP for communication between Nodes?

**Comment by icebob** [comment]
With external discoverer (Redis, etcd), yes, we can create HTTP transporter, as well.

**Comment by guddubit** [comment]
Thanks so much for the quick response icebob, Do we have to create HTTP transporter and If yes could you please give me insights on how to do that?

**Comment by AndreMaz** [comment]
@guddubit if you want to implement HTTP transport then check the [Custom Transporter](https://moleculer.services/docs/0.14/networking.html#Custom-transporter) section in the docs

**Comment by guddubit** [comment]
Thanks @AndreMaz I will try to implement that.
