### ISSUE TITLE
Add ability to add global action tracing tags

### ISSUE THREAD

**Issue by kthompson23** [moleculerjs/moleculer#784]
I am using the Zipkin exporter to implement tracing. I would like to add a few fields from context.meta on all spans. Currently, as far as I can tell, the only way to add fields from context.meta is to add tracing options in each action.

We have a lot of services and actions so this would be time-consuming, repetitive, and possible forgotten in future actions that we create.

Would you accept a PR to add an optional option called `tags` to the Tracer options? This would apply to all actions and be override-able at the action level. 

Tracer options:
```js
tracing: {
	enabled: true,
	exporter: {
		type: 'Zipkin',
	},
	tags: {
		meta: ['app.id', 'user.email', 'workspace.name'],
	},
},
```

In the tracing middleware we'd do a merge like:
```js
// override global action tags with action tags
const mergedTags = { ...tracer.tags, ...opts.tags }
if (_.isFunction(mergedTags)) {
	const res = mergedTags.call(ctx.service, ctx);
	if (res)
		Object.assign(tags, res);

} else if (_.isPlainObject(mergedTags)) {
	if (mergedTags.params === true)
		tags.params = ctx.params != null ? Object.assign({}, ctx.params) : ctx.params;
	else if (Array.isArray(mergedTags.params))
		tags.params = _.pick(ctx.params, mergedTags.params);

	if (mergedTags.meta === true)
		tags.meta = ctx.meta != null ? Object.assign({}, ctx.meta) : ctx.meta;
	else if (Array.isArray(mergedTags.meta))
		tags.meta = _.pick(ctx.meta, mergedTags.meta);
```

**Comment by kthompson23** [comment]
Perhaps it'd be better to specify that they are action tags:
```js
tracing: {
  enabled: true,
  exporter: {
    type: 'Zipkin',
  },
  tags: {
    action: {          
      meta: ['app.id', 'user.email', 'workspace.name'],
    },
  },
},
```

**Comment by icebob** [comment]
Yeah, it's a good idea. But it would be cover all situations. So it should work with `params`, `meta` for `actions` and `events`. Could you create it?

**Comment by kthompson23** [comment]
Got it. I will take care of it.
