### ISSUE TITLE
Change to drive letter casing causes Babel parse errors when babel-node is used with the runner

### ISSUE THREAD

**Issue by kthompson23** [moleculerjs/moleculer#788]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior
Windows users of babel-node transpiling their JavaScript or Typescript may encounter Babel parse errors when trying to run run their services using the moleculer-runner.

For development purposes we use the following script to transpile our Typescript on the fly and run our services locally.
```
"script": {
    "dev": "nodemon --watch ./src --ext ts --exec babel-node --extensions .ts -- ./node_modules/moleculer/bin/moleculer-runner --env --repl --mask **/*.service.ts src/services --config ./src/moleculer.config.ts",
```

babel-node transpiles all Typescript files including the moleculer.config.ts file when they are required.

After [121c711](https://github.com/moleculerjs/moleculer/commit/121c711599da2f32d8cd51cf95925f93420a5fc9), we receive babel parse errors on moleculer.config.ts. Babel does not realize that this is a Typescript file and the Typescript plugin does not run. I do not think the issue is specific to Typescript. Users of babel-node transpiling es-next features like `import` statements may encounter a similar error.

We believe that because the runner changes the casing of the drive letter in the absolute path of the config file, Babel does not realize that this is the same file that it already resolved. 

## Expected Behavior

babel-node should be able to transpile the moleculer config file when used with the runner.

## Failure Information
```
C:\Users\kat\projects\moleculer-services (moleculer-services@0.0.0)
λ npm run dev

> moleculer-services@0.0.0 dev C:\Users\kat\projects\moleculer-services
> nodemon --watch ./src --ext ts --exec babel-node --extensions .ts -- ./node_modules/moleculer/bin/moleculer-runner --env --repl --mask **/*.service.ts src/services --config ./src/moleculer.config.ts

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: ts
[nodemon] starting `babel-node --extensions .ts ./node_modules/moleculer/bin/moleculer-runner --env --repl --mask **/*.service.ts src/services --config ./src/moleculer.config.ts`
[Runner] c:\Users\kat\projects\moleculer-services\src\moleculer.config.ts: Unexpected token (24:26)

> 24 | const moleculerLogLevelMap: { [key in LogLevels]: MoleculerLogLevels } = {
     |                           ^
  25 |  error: 'error',
  26 |  warn: 'warn',
  27 |  info: 'info', SyntaxError: c:\Users\kat\projects\moleculer-services\src\moleculer.config.ts: Unexpected token (24:26)

> 24 | const moleculerLogLevelMap: { [key in LogLevels]: MoleculerLogLevels } = {
     |                           ^
  25 |  error: 'error',
  26 |  warn: 'warn',
  27 |  info: 'info',
    at Parser._raise (C:\Users\kat\projects\moleculer-services\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:742:17)
... lots of stack lines
  loc: Position { line: 24, column: 26 },
  pos: 861,
  code: 'BABEL_PARSE_ERROR'
}
[nodemon] app crashed - waiting for file changes before starting...
```

Note that my drive letter in the shell prompt is in uppercase: `C:\` but the error message `[Runner] c:\Users\kat\projects\moleculer-services\src\moleculer.config.ts: Unexpected token (24:26)` has it in lowercase

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: commit 121c711599da2f32d8cd51cf95925f93420a5fc9
* NodeJS version: 12.17
* Operating System: Windows 10

**Comment by kthompson23** [comment]
[Reproduction Repo](https://github.com/kthompson23/moleculer-788-repo) 

The version of moleculer is set at 121c711. I placed an import statement in moleculer.config.js and added some basic babel libraries to transpile:

Running `npm run dev` outputs:
```
λ npm run dev

> 788-repro@1.0.0 dev C:\Users\kat\projects\788-repro
> babel-node --extensions .js -- ./node_modules/moleculer/bin/moleculer-runner --repl --hot service.js

[Runner] Unexpected token 'export' c:\Users\kat\projects\788-repro\moleculer.config.js:187
export default brokerOptions;
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Module._compile (C:\Users\kat\projects\788-repro\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (C:\Users\kat\projects\788-repro\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

Revert moleculer to 0.14.8 and the runner starts.

**Comment by icebob** [comment]
Ok, I will check it.

**Comment by icebob** [comment]
I've tried the repro repo but it works fine:

![image](https://user-images.githubusercontent.com/306521/88206738-0a915200-cc4f-11ea-85fa-2170731fddb8.png)

**Comment by kthompson23** [comment]
I think the problem is that your drive letter is in lowercase.

When I startup cmd.exe my prompt looks like this:
```
C:\Users\kat>
```

Did you set it as `d:\` at some point? All my drives get set as uppercase.

**Comment by kthompson23** [comment]
I found instructions on how to change the casing of a drive letter. It can be down when changing directories:

https://github.com/microsoft/vscode/issues/9448#issuecomment-245024153

To go uppercase:
```
cd .. && cd C%cd:~1%
```

Lowercase:
```
cd .. && cd c%cd:~1%
```

**Comment by icebob** [comment]
Thanks. In Windows, this casing issue is awful....
My original problem was that Node.js module cache stored the module filename with lowercase drive letter, but if you use `path.join` (in Runner) it uses uppercase drive letter. And the result, moleculer loaded twice and I couldn't use custom modules.

Nevermind, I will revert the https://github.com/moleculerjs/moleculer/commit/121c711599da2f32d8cd51cf95925f93420a5fc9 because I have no clue, that how I could solve both problem.
