### ISSUE TITLE
Moleculer prints colored log messages when colored log messages are disabled

### ISSUE THREAD

**Issue by oliversalzburg** [moleculerjs/moleculer#793]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

Certain log messages are colored, even though colored log messages have been disabled.

```
{"level":40,"time":1597228317296,"pid":21927,"hostname":"oliver-work","msg":"\u001b[33m\u001b[1mRedis Discoverer is an EXPERIMENTAL module. Do NOT use it in production!\u001b[39m\u001b[22m"}
```

## Expected Behavior

When colored log messages are disabled, log messages are not colored.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable the Redis Discoverer
2. Disable colors in the logger
3. Start the application

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.8
* NodeJS version: 14
* Operating System: Windows

My logger configuration:

```json
logger : {
	type : "Console",
	options : {
		colors : false,
		formatter : ( level, logElements, bindings ) => logElements
	}
},
```

**Comment by oliversalzburg** [comment]
Seems like I missed a part of our code where the logger is replaced by our own implementation.

The color is already hardcoded into the log message. The `colors` property of the ConsoleLogger refers to the coloring of entire log lines by that logger. But that logger isn't even used in our setup.

**Comment by icebob** [comment]
It can be relevant to https://github.com/moleculerjs/moleculer/issues/941
