### ISSUE TITLE
Trace spans should include the requestID as a tag to improve searchability

### ISSUE THREAD

**Issue by kthompson23** [moleculerjs/moleculer#797]
In the Datadog, Zipkin, New Relic, and Jaeger exporters, the requestID is used as the basis for the traceId. However, in all implementations the requestID is run through a convert function to strip dashes and truncate it to 16 characters. In the Jaeger exporter it is further modified by converting to hex. This makes it very difficult to search for traces using the requestID because you must know how the exporter you are using modified the requestID to generate the traceId.

Moleculer should include the requestID as a tag in all spans so users can search for spans and traces using the requestID. In our environment we include the requestID in all logs and error messages. This will allow us to easily match up logs and errors with traces and spans.

**Comment by icebob** [comment]
Good idea. Could you create a PR? I think we should add it into these parts:
https://github.com/moleculerjs/moleculer/blob/master/src/middlewares/tracing.js#L28
https://github.com/moleculerjs/moleculer/blob/master/src/middlewares/tracing.js#L146

**Comment by kthompson23** [comment]
Sure, happy to do a PR.

Any issues with adding it in the `Context.startSpan` method? That way user defined tracing spans created using ctx would also get the requestID.

Something like:

```js
/**
 * Start a new child tracing span.
 *
 * @param {String} name
 * @param {Object?} opts
 * @returns {Span}
 * @memberof Context
 */
startSpan(name, opts = {}) {
	if (!opts.tags) {
		opts.tags = { requestID: this.requestID };
	}
	else if (opts.tags.requestID == null) {
		opts.tags.requestID = this.requestID;
	}

	let span;
	if (this.span) {
		span = this.span.startSpan(name, Object.assign({ ctx: this }, opts));
	} else {
		span = this.broker.tracer.startSpan(name, Object.assign({ ctx: this }, opts));
	}

	this._spanStack.push(span);
	this.span = span;

	return span;
}
```

**Comment by icebob** [comment]
Awesome!

> Any issues with adding it in the Context.startSpan method? That way user defined tracing spans created using ctx would also get the requestID.

Ok, let's try it.

**Comment by ehaselwanter** [comment]
This might help with what I want to achieve. I have traefik in front of moleculer. I can see traces in jaeger entering traefik, I can trace them **in** moleculer, but I just don't get it right to follow the request from the web down to one of the services ..

<img width="370" alt="image" src="https://user-images.githubusercontent.com/18671/94897129-505c6900-048f-11eb-8d59-3d96d8a3f40d.png">

traefik/jaeger

```yaml
            - --tracing.jaeger=true
            - --tracing.jaeger.samplingServerURL=http://127.0.0.1:5778/sampling
            - --tracing.jaeger.samplingType=const
            - --tracing.jaeger.samplingParam=1.0
            - --tracing.jaeger.localAgentHostPort=127.0.0.1:6831
            - --tracing.jaeger.propagation=jaeger
            - --tracing.jaeger.traceContextHeaderName=uber-trace-id
```

moleculer/jaeger

```json
tracing: {
  enabled: true,
  exporter: {
   type: "Jaeger",
   options: {
    endpoint: null,
    host: "127.0.0.1",
    port: 6832,
    sampler: {
     type: "Const",
     options: {}
    },
    tracerOptions: {},
    defaultTags: null
   }
  }
 },
```

or is it something in the tracer options?

**Comment by kthompson23** [comment]
If I'm understanding you correctly, you want a complete trace that originated from the front-end and includes, front-end, traefik, and moleculer-services.

```
            - --tracing.jaeger.propagation=jaeger
            - --tracing.jaeger.traceContextHeaderName=uber-trace-id
```
In your example you have the propagation type set to "jaeger", which I'm not familiar with, but here's an example of how to use a hook in Moleculer's API gateway to pull off a zipkin type propagation header and set it as the requestID

https://github.com/moleculerjs/moleculer-web/issues/51#issuecomment-393158600
