### ISSUE TITLE
[question] how to create multipe nodes on only one service

### ISSUE THREAD

**Issue by giveerr** [moleculerjs/moleculer#800]
| service 	| version 	| state 	| actions 	| events 	| nodes 	|
|---------	|---------	|-------	|---------	|--------	|-------	|
| $node   	| -       	| ok    	| 7       	| 0      	| 1     	|
| api     	| -       	| ok    	| 1       	| 0      	| 1     	|
| math     	| -       	| ok    	| 3       	| 0      	| 1     	|

i have a service table like this but i want to increase the nodes count of only math not all of them. ( i use moleculer-runner )
the result view that i want: 

| service 	| version 	| state 	| actions 	| events 	| nodes 	|
|---------	|---------	|-------	|---------	|--------	|-------	|
| ...   	| ...       	| ...    	| ...       	| ...      	| ...     	|
| math     	| -       	| ok    	| 3       	| 0      	| 3    	|

**Comment by intech** [comment]
run moleculer-runner with env:
SERVICES=math
docs: https://moleculer.services/docs/0.14/runner.html#Services-loading-logic

**Comment by giveerr** [comment]
thanks but in this case it starts only math service i will use the other ones too.

**Comment by intech** [comment]
That's right. One broker is a monolith of the services specified in SERVICES. Your broker first loads all services.
If you need more math instances, then you have to create several brokers with SERVICES=math separately, each broker will be a separate instance.
The balancing of requests between replicas works at the broker level.

**Comment by giveerr** [comment]
I get it now. thanks
