### ISSUE TITLE
Hot Reload maximum call stack exceeded

### ISSUE THREAD

**Issue by joshmanders** [moleculerjs/moleculer#806]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

When I run with `--hot` as soon as it detects a service changed, it reloads it, then throws an error ```RangeError: Maximum call stack size exceeded```

## Expected Behavior

Hot reloading to work as it used to

## Failure Information

![image](https://user-images.githubusercontent.com/352113/91677991-f6702880-eb09-11ea-9ad3-161457e4f79d.png)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create an app
2. Create a couple services
3. start with `--hot`
4. Change a service

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: v0.14.10
* NodeJS version: v14.8.0
* Operating System: macOS Catalina

**Comment by joshmanders** [comment]
I just booted up my app and let it sit for a bit and after about 2-3 minutes it "detected" a change event in one of my services and reloaded it, then immediately errored out with the call stack exceeded.

**Comment by icebob** [comment]
I can't reproduce it, please make a repro repo.

**Comment by joshmanders** [comment]
Hey @icebob, not sure what was going on, but I recently restarted my machine for a macOS update and it hasn't happened again. So I'll close as some fluke with my machine that restarting fixed.

**Comment by zhangfisher** [comment]
I also found the same problem

fix on `middlewares/hot-reload.js` ,function: `processModule`

```js
			mod.children.forEach(m => {
				if(m.filename.indexOf("node_modules") !== -1) return;      // add this line
				processModule(m, service, service ? level + 1 : 0, parents)
			});
```
