### ISSUE TITLE
waitForServices should fail immediately if the broker is not started

### ISSUE THREAD

**Issue by gautaz** [moleculerjs/moleculer#819]
**Is your feature request related to a problem? Please describe.**
A common error is to ask the broker to wait for some services without ensuring that the broker is started first.
Currently `waitForServices` just waits indefinitely.

**Describe the solution you'd like**
`waitForServices` should simply fail (promise rejection) when the broker is not started.

**Describe alternatives you've considered**
Well, be more cautious when using `waitForServices` ;-).

**Comment by icebob** [comment]
I don't like the suggested solution because I think you can wait for a service before broker started because you will start it later. If you don't want to wait indefinitely, set the timeout parameter in `waitForServices`

**Comment by gautaz** [comment]
@icebob You're right, I was narrowing the use of `waitForServices` to my particular use case, closing :-).
