### ISSUE TITLE
Inject custom tags dynamically in Datadog logger.

### ISSUE THREAD

**Issue by edud69** [moleculerjs/moleculer#821]
**Is your feature request related to a problem? Please describe.**
Moleculer offers a way to have static tags, but for a context-bound tag nothing is possible.
Currently, to track user logs with Datadog, we inject the request context (current connected user email, request ID) in the arguments of logged lines behind a wrapper that we have created:
```typescript
export class LoggerWrapper implements Logger {

    constructor(context : Context<any>, user : User) {
        this._user = user;
        this._internalLogger = context.service.logger;
    }

    debug(...args: any[]): void {
        this._internalLogger.debug(...this._appendContext(args));
    }

    private _appendContext(args: any[]) {
        if(this._user?.email) {
            return args.concat(["\n\nContext:", { user: this._user.email, domain: this._user.domain, requestID: this._requestID }]);
        }
        return args;
    }
}
```

**Describe the solution you'd like**
It would be nice if the Moleculer config exposes some kind of callback based on the context.
```typescript
{
    type: "Datadog",
    options: {
        level: "info",
        ...
        customTags: (context? : Context<any>) => {
            return { "A_TAG_KEY_01" : context?.meta?.someDynamicValue }
        }
    }
```

Something really close to what was done in:
PR : https://github.com/moleculerjs/moleculer/pull/789
Issue: https://github.com/moleculerjs/moleculer/issues/784

**Describe alternatives you've considered**
Logging the context directly in the message is a workaround, but having it as a tag would be much easier and remove the noise of some messages that are not related.

**Comment by icebob** [comment]
I'm closing this issue because we will [remove ](https://github.com/moleculerjs/moleculer/discussions/1125) the built-in trace/metrics features in the future versions.
