### ISSUE TITLE
How to add cookie to response from actions

### ISSUE THREAD

**Issue by goldytech** [moleculerjs/moleculer#823]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

I want to set the cookie in res object in the action method or after hook in the action method.

Also how can I send http response status code other than 200 

Can you please provide the sample code of how can I do this in moleculer ?
## Expected Behavior

Should able to set the cookie in response return to client
something similar to Nodejs express
` res.cookie("token", token, { httpOnly: true });
`
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Reproduce code snippet

```js
const broker = new ServiceBroker({
    logger: console,
    transporter: "NATS"
});

broker.createService({
    name: "test",
    actions: {
        empty(ctx) {
            return "Hello"
        }
    }
});
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14
* NodeJS version: 12.x
* Operating System: Mac OS

### Failure Logs
```

```

**Comment by icebob** [comment]
You can use the `Set-Cookie` in the header:

```
ctx.meta.$responseHeaders: {
	"Set-Cookie": "...."
}
```

**Comment by goldytech** [comment]
Thanks that works

```
ctx.meta.$responseHeaders = {
						"Set-Cookie": `token=${token};HttpOnly`,
					};

```

Now if I want to remove the cookie , I'm using this code but it doesn't work and cookie is still persisted

```
ctx.meta.$responseHeaders = {
						"Clear-Site-Data":"cookies"
					};
					return new MoleculerClientError("Invalid credentials", 401,"",[{message:"Invalid credentials"}]);
```

Also I'm not getting json message in the response body.

Please help
