### ISSUE TITLE
Broker does not stop with multiples 'createService'

### ISSUE THREAD

**Issue by 23pablo97** [moleculerjs/moleculer#827]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [Y] I am running the latest version
- [Y] I checked the documentation and found no answer
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository

## Current Behavior
I’m doing some test in jest for a service action that call another action from other service

```
//suggestion action
async build(ctx) {
   ...
   const filter = await ctx.call('filter.get', {id: strategy.filterId.toString()});
   ...
 
   const sequence = await ctx.call('sequence.build', {
     id: strategy.sequenceId.toString(), parameters: strategy.parameters,
   });
   ...
 
   return suggestion;
 }

```
So in the test, I’m creating a broker that “create” a the services necessaries to exec the action

```
let strategyService;
 const broker = new ServiceBroker();
 
 beforeAll(async () => {
   strategyService = broker.createService(StrategyService);
   broker.createService(FilterService);
   broker.createService(SequencesService);
   return await broker.start();
 });
 
 afterAll(async () => {
   broker.destroyService(StrategyService);
   broker.destroyService(FilterService);
   broker.destroyService(SequencesService);
   return await broker.stop();
 });
```

but jest does not terminate the exec and print
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

Also, I created different broker to different services but i have the same error and I cannot comunicate the action between brokers (maybe a bad config in the nats)

## Expected Behavior

The expected behavior would be to stop the broker and finish the process

### Steps to Reproduce

1. First create two services with one actions each one (you can use the molecular template)
2. In one of them call the action of the other service 

```
//example
async build(ctx) {
   ...
   const filter = await ctx.call('filter.get', {id: strategy.filterId.toString()});
   ...
 
   return suggestion;
 }

```

3. Create a broker
4. adding to the broker both services, and start the broker

```
beforeAll(() => {
  broker.createService(service1);
  broker.createService(service2);
  return broker.start()
});
```

5. create some test to exec the service
6. After all `broker.stop()`
7. in the test will have some connections open

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.14
* NodeJS version:  v14.2.0
* Operating System: macOS Catalina 10.15.6

### Failure Logs
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by icebob** [comment]
Please create a fully reproduce repo.

**Comment by 23pablo97** [comment]
Sorry, I fixed it... It was a problem with the mongoose connection... sorry for the time and thx for answering me
