### ISSUE TITLE
Event tracer sends tracing events about tracing events

### ISSUE THREAD

**Issue by cs4inctec** [moleculerjs/moleculer#836]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

When using the 'Events' tracer, a `samplingRate` of 1.0 with trace events about events on, eg.

```
tracing: {
      enabled: true,
      sampling: {
        rate: 1.0,
      },
      events: true,
      exporter: {
        type: 'Event',
    },
}
```

then it seems that even trace events are generating trace events, until Node crashes.

## Expected Behavior

Trace events themselves shouldn't generate trace events.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.11
* NodeJS version: 15.2.1
* Operating System: Linux

**Comment by icebob** [comment]
Ohh, nice catch, thanks.
