### ISSUE TITLE
Load Balancing on call to action on the same service.

### ISSUE THREAD

**Issue by romanpDev** [moleculerjs/moleculer#844]
Hi,
I did a little test to check if there is a load balancing when I have a service with action that calls to another action on the same service.

I created 2 instances of the same service and simulated 10,000 calls to that action(that calls to another action on the service).
In the logs I always saw that the nodeID is the same on the call to the main action and in the  action that he called.

Although load balancing exists on the call to the main action , but the "internal calls" were always on the same instance.

Now, I want to be sure that is the default behavior ? if there is something can be done , some configuration or some way to perform the call to action on same service so the load balancing will be available? 

Thanks.

**Comment by intech** [comment]
![Снимок экрана от 2020-12-15 20-15-45](https://user-images.githubusercontent.com/451306/102248572-5a302d00-3f12-11eb-9ee5-db47deb6e3f4.png)
https://moleculer.services/docs/0.14/concepts.html#Architecture

**Comment by icebob** [comment]
The ServiceBroker first tries to call the local instances of service (if exists) to reduce network latencies. This logic can be turned off in broker options with preferLocal: false property under the registry key.

**Comment by romanpDev** [comment]
Thanks for the quick response😀
I will try it.
