### ISSUE TITLE
Redis Transporter (Support for Redis Sentinel)

### ISSUE THREAD

**Issue by Jeffrey1207** [moleculerjs/moleculer#845]
When we using the Redis transporter for a single redis server is working perfectly, but when we using the redis transporter to connect a redis sentinel pool, the application will alert many reconnect message about connecting to a 127.0.0.1:6379. 

Is the redis transporter support Redis sentinel feature?

Thanks

**Comment by gionaico** [comment]
Is there any answer about this problem?

**Comment by gionaico** [comment]
It works but the correct way to use __"Redis-Sentinel"__ as transporter is this: 

```js
  transporter: {
    type: "Redis",
    options: {
      // Prefix for keys
      prefix: process.env.APP_NAME,
      ttl: 60 * 60,
      // Turns Redis client monitoring on.
      monitor: false,
      sentinels: [
        {
          host: process.env.REDIS_HOST,
          port: process.env.REDIS_SENTINEL_PORT,
          connectTimeout: 50000,
        },
      ],
      name: "mymaster"
    }
  }
```
