### ISSUE TITLE
Using two different transporters

### ISSUE THREAD

**Issue by bar-colu** [moleculerjs/moleculer#847]
We would like to be able to use two different types of transporters (specifically TCP & MQTT) and be able to "tell" each call which transporter to use. We would also like that the MQTT will be a fallback to the TCP.

My guess is that it will be possible by sending the transporter option an array instead of a string/object/class. 
But that will also mean a huge change in code in the initialization and the send function as well. 

I thought about using the custom transporter option to initialize 2 different transporters of my choice and implement the "send" function with the fallback I need (using the meta to know which transporter to try first).

I wanted to know if that's an option someone already thought of or if you have any idea on how to do something like that.

Köszenem szepen!

**Comment by icebob** [comment]
Hi @bar-colu, yeah, the codebase supports only one transporter, and it would be hard to change it. Your custom transporter can be a good option. Another option is maybe [the inter-namespace middleware](https://gist.github.com/icebob/c0bce54436379d29c1bee8521ceb5348). You can define multiple brokers with different settings.

**Comment by bar-colu** [comment]
Thanks @icebob will look into it!
