### ISSUE TITLE
Incorrect Avro schema for EVENT Packet causing service to crash

### ISSUE THREAD

**Issue by JordanPawlett** [moleculerjs/moleculer#856]
Found a bug in the Avro Serializer.
https://github.com/moleculerjs/moleculer/blob/d84a6916a012664cdcc4e88fab5a780a816584be/src/serializers/avro.js#L39

Seems like needAck defaults to null, which breaks the schema causing a fatal error... 
I guess it should be 
`{ name: "needAck", type: ["null", "boolean"], default: null }`

**Comment by icebob** [comment]
Thanks, fixed.
