### ISSUE TITLE
Keep Moleculer error classes for calls between services

### ISSUE THREAD

**Issue by gautaz** [moleculerjs/moleculer#861]
**Is your feature request related to a problem? Please describe.**
From my understanding, the current Moleculer behavior when throwing an exception from a service B called by a service A is for the service A to receive the error as a generic Javascript [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) instance.
Whether the original error is a [MoleculerError, MoleculerClientError, MoleculerServerError](https://moleculer.services/docs/0.14/errors.html) or a custom error inheriting from the previous ones does not seem to change this behavior.

**Describe the solution you'd like**
Service A cannot know of custom error classes defined in service B but at least it is aware of all Moleculer error classes.
From service A point of view, it would help to distinguish client errors from server errors, this could be handled by receiving a MoleculerClientError or a MoleculerServerError depending on what the original error from service B inherited from.
In fact, that was what one of my developers expected naturally.

**Describe alternatives you've considered**
AFAIK we can only rely on error names, type codes or any other mean detailed in the error content.
I did not find for now a native "generic way" to know if the error is due to the caller or the callee.

**Additional context**
N/A

**Comment by icebob** [comment]
The `Transit` tries to recreate the original error based on the error name here:
https://github.com/moleculerjs/moleculer/blob/498b008c1e8bcf6049f6bd762c0015d4c47f6100/src/errors.js#L389-L415

Could you create a minimal reproduce example the we can investigate it?

**Comment by gautaz** [comment]
@icebob Thanks for your answer.

I guess the issue here is more about documentation as the behavior you describe should be detailed in https://moleculer.services/docs/0.14/errors.html.

In particular in the section [Create custom errors](https://moleculer.services/docs/0.14/errors.html#Create-custom-errors), the documentation should perhaps emphasize the fact that the name is used later on to unmarshall errors.

What is also perhaps bothering for developers is that they cannot set their own error names without crippling the error unmarshalling.
Perhaps a field name that clarifies the intention (something like "moleculerErrorClass" instead of "name") would help understanding its effect without looking at the documentation.

**Comment by gautaz** [comment]
@icebob The problem can easily be reproduced:

```js
const { MoleculerClientError } = require("moleculer").Errors;

class CustomClientError extends MoleculerClientError {
    constructor(msg, data) {
        super(msg || `This is a custom client error.`, 400, "CUSTOM_CLIENT_ERROR", data);
    }
}

const testError = new CustomClientError();
console.log(testError.name);
```

Executing the previous code displays `CustomClientError`.

This means that subclassing a MoleculerClientError will by default change the name from `MoleculerClientError` to `CustomClientError` thus the translation to an `Error` during the broker unmarshalling: https://github.com/moleculerjs/moleculer/blob/498b008c1e8bcf6049f6bd762c0015d4c47f6100/src/transit.js#L542-L544

**Comment by FFKL** [comment]
@icebob I recently ran into this problem. What is the status of this PR? I can help with implementation of the custom `recreateError` function or some other solution.

**Comment by icebob** [comment]
PRs are welcome.
