### ISSUE TITLE
Use Deno instead of Nodejs

### ISSUE THREAD

**Issue by FlorianPons** [moleculerjs/moleculer#863]
Deno is a very insteresting project to replace Nodejs, it would be nice one day to be able to choose between both.

**Comment by Wallacy** [comment]
To make that work, first we need: https://github.com/moleculerjs/moleculer/issues/433

**Comment by duurland** [comment]
It's worth noting that Deno aims to be [browser-compatible](https://deno.land/manual#goals) (ES Modules). A good opportunity for official [moleculer-browser support](https://github.com/geut/moleculer-browser).
