### ISSUE TITLE
Cron jobs with graceful exits are still being reported as Lost after 10 minutes due to heartbeats missing.

### ISSUE THREAD

**Issue by morkeleb** [moleculerjs/moleculer#866]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

We're starting moleculer instances on cron jobs, they run to completion successfully. Yet we always get a heartbeat message on all the services even though we do a graceful close of the broker in the cron jobs.

## Expected Behavior

That the graceful exit doesn't produce the registry heartbeat signal.

## Failure Information

We're using the AMQP transporter.
The jobs run as cronjobs in a kubernetes cluster.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. have a service running amqp in a kuberentes cluster
2. start a cron job start create a broker
3. when the cron job runs to completetion, wait 10 minutes and the check to log of the service.

### Reproduce code snippet

Cron job code
```js
try {
  const broker = new ServiceBroker(brokerConfig);
  await broker.start();
    await job(broker);
    console.log('DONE');
  } catch (error) {
    console.error(error);
    console.log('exiting due to catch');
  } finally {
    console.log('stopping broker');
    broker && (await broker.stop());
    console.log('broker stopped');
    const result = perf.stop();
    console.log('resulting time', result.time);
  }
```

Services are just normal moleculer services. Both configured with AMPQ as transport.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.12
* NodeJS version: 14.15.2
* Operating System: Linux (same on Mac)

### Failure Logs
```
[2021-02-05T12:26:24.614Z] WARN  crm-b4c5dcd6-hldrc-19/DISCOVERY: Removing offline 'order-flow-1612527300-wpvbt-1' node from registry because it hasn't submitted heartbeat signal for 10 minutes.
[2021-02-05T12:30:24.616Z] WARN  crm-b4c5dcd6-hldrc-19/DISCOVERY: Removing offline 'order-flow-1612527600-blnld-1' node from registry because it hasn't submitted heartbeat signal for 10 minutes.
```

**Comment by intech** [comment]
@morkeleb
1. Have you tried to check the problem on another transport?
2. Could you please provide the code to reproduce.

**Comment by morkeleb** [comment]
The issue was that the cron job pods were deleted before the disconnect messages were delivered through the queuing system. Making sure kuberentes does not kill the pod before all messages have been drained through the system solved the issue.

This is done by adding a lifeCycle wait period in the cron job definition.

```
              lifecycle:
                preStop:
                    exec:
                      command:
                          - sh
                          - -c
                          - sleep 25
```

This makes sure the pods are disconnected properely.
