### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by akshaykarode** [moleculerjs/moleculer#868]
https://moleculer.services/ is down. Please get it up !

**Comment by AndreMaz** [comment]
It's up and running. Can you check again, please?

**Comment by intech** [comment]
All ok https://www.host-tracker.com/v3/check/2/8885866c-39bf-4468-b496-971182ae6a09
We had a similar problem in Russia, because the site is hosted on a CDN, then some servers were included in the state blocking list and the site sometimes worked, then not.
