### ISSUE TITLE
Setting up infraestructure using moleculer and kubernetes (doubts)

### ISSUE THREAD

**Issue by developez** [moleculerjs/moleculer#873]
I am testing moleculer microservices framework to setting up an infraestructure. I will to use typescript (https://github.com/moleculerjs/moleculer-template-project-typescript). My idea is according the documentation is:

Create one project for with API Gateway => make doker => make k8s deployment with N replicas
create 1 project per microservice 1 => dockerize => make k8s deployment with N replicas
create 1 project per microservice 2 => dockerize => make k8s deployment with N replicas 
...
create 1 project per microservice 3 => dockerize => make k8s deployment with N replicas

I will use redis as transporter. I want to use redis also in development.

I have got this doubt, because you can create in the same project all the microservices, but in this way, you are developing a monolitic application and only in one thread ¿?, and I think that you need to sepparate each microservice in independent (typescripts) projects to make it pods in k8s in the deployment phase.

It would be possible to clarify this point to me?

**Comment by icebob** [comment]
I post the answer to [SO](https://stackoverflow.com/questions/66275042/setting-up-infraestructure-using-moleculer-and-kubernetes-doubts/66275457#66275457)
_Please don't post your question multiple times._
