### ISSUE TITLE
Make Transporter prefix an option

### ISSUE THREAD

**Issue by Hrafven** [moleculerjs/moleculer#879]
**Is your feature request related to a problem? Please describe.**

With heroku kafka Basic plan topics have a dynamic prefix. I can't change the default MOL prefix to a dynamic value.

**Describe the solution you'd like**

Add an option to the service broker configuration

Thanks !

**Comment by AndreMaz** [comment]
It uses the MOL prefix because of moleculer's communication protocol (more info [here](https://github.com/moleculer-framework/protocol/blob/master/4.0/PROTOCOL.md)). If you change it to something else services won't be able to communicate with each other
