### ISSUE TITLE
How to send heartbeats when under heavy load and prevent service disconnection

### ISSUE THREAD

**Issue by leobudima** [moleculerjs/moleculer#891]
Hi, 

I have a question on how to prevent the service from being considered disconnected, when it is unable to send heartbeats in required interval since it's under load. 

Here are the factors that dictate the situation:

- I have a mixed architecture, with a custom API Gateway, connected through Moleculer (using NATS transport) with a number of nodes where multiples of services are running on each

- because of CI/CD, we need to react to disconnected services quickly, and not send requests to them - that's why I keep the heartbeat and timeout relatively small (15 sec interval, 45 sec timeout)

- however, some of the services do heavy processing (while also needing other services, database connection etc, so it's hard to isolate their code and spawn in another process), so those nodes are often not able to send heartbeats in required intervals. When that happens, API Gateway considers them disconnected (missing heartbeats) and drops the HTTP request that's waiting on service response.

I was curious if anyone else had similar challenges and if what would be ways to mitigate this...First thought that comes to my mind is that, if doing service work in another process / thread is difficult because of all the dependencies, maybe heartbeats could be sent from another process so that CPU load / single-thread nature of Node.js does not block them?

Thank you!

**Comment by intech** [comment]
The correct solution would be to move the blocked event loop operations through worker threads. The service starts calculations and communicates via the bus. You can use for example [bree](https://www.npmjs.com/package/bree).

The second option is to start the broker only with this loaded service in [cluster mode](https://moleculer.services/docs/0.14/runner.html#Built-in-clustering) and set the [load balancing for cpu](https://moleculer.services/docs/0.14/balancing.html#CPU-usage-based-strategy) in its configuration.

**Comment by leobudima** [comment]
Thanks a lot for your comment @intech - I haven't seen bree before and it seems even better than what we started with (bullmq), so we'll look into isolating service code some more and running it in separate workers via bree after all. Thanks again!
