### ISSUE TITLE
Expose the Cacher middleware

### ISSUE THREAD

**Issue by srosset81** [moleculerjs/moleculer#892]
**Is your feature request related to a problem? Please describe.**
I use a custom middleware that must be called *before* the Cacher middleware. The problem is that the Cacher middleware is the only one which is not exposed (as can been seen [here](https://github.com/moleculerjs/moleculer/tree/master/src/middlewares)), probably because it requires to have the broker object passed down to it during the initialization. So I cannot disable internal middlewares and re-order all middlewares as I need.

**Describe the solution you'd like**
Expose the cacher middleware to be able to use it like other internal middlewares. I found this solution which seems to work:

```js
const Cachers = require('moleculer').Cachers;

let cacherMiddleware;

const CacherMiddleware = opts => ({
  name: "CacherMiddleware",
  created(broker) {
    if( opts ) {
      const cacher = Cachers.resolve(opts);
      cacher.init(broker);
      cacherMiddleware = cacher.middleware();
    }
  },
  localAction(next, action) {
    if( cacherMiddleware ) {
      return cacherMiddleware(next, action);
    } else {
      return next;
    }
  }
});

module.exports = CacherMiddleware;
```

**Additional context**
I can create a PR if this seems to be a good solution.

**Comment by srosset81** [comment]
Little correction on the middleware, so that we can access `this.broker.cacher` everywhere:

```js
const Cachers = require('moleculer').Cachers;

let cacherMiddleware;

// It has been suggested to put this middleware in Moleculer core code:
// https://github.com/moleculerjs/moleculer/issues/892
const CacherMiddleware = opts => ({
  name: "CacherMiddleware",
  created(broker) {
    if( opts ) {
      broker.cacher = Cachers.resolve(opts);
      broker.cacher.init(broker);
      cacherMiddleware = broker.cacher.middleware();
    }
  },
  localAction(next, action) {
    if( cacherMiddleware ) {
      return cacherMiddleware(next, action);
    } else {
      return next;
    }
  }
});

module.exports = CacherMiddleware;
```

**Comment by icebob** [comment]
I think would be much simpler if we keep the cacher initialization inside constructor of broker and just call the `middleware` method:
```js
module.exports = broker => {
    return {
        name: "CacherMiddleware",

        localAction(next, action) {
            if (broker.cacher) return broker.cacher.middleware(next, action);
            return next;
        }
    }
};
```
What do you think? Is it cover your issue?
