### ISSUE TITLE
Mixins with Typescript template & decorators way

### ISSUE THREAD

**Issue by Kamil93** [moleculerjs/moleculer#896]
Latest version of moleculer.js: 0.14.12

None of `methods` from `HttpService` are accessible within `MainService`.
None of `actions` from `HttpService` are accessible in system, like they don't exist.

Why?

When instead of `HttpService` I'll use `moleculer-db` `service` as `mixin`, all `actions` from `moleculer-db` are accessible and exist in system.

How to use `mixins` with `typescript` & `decorators` way?

HttpService:
```
"use strict";

import * as Mol            from "moleculer";
import * as MolDec	     from "moleculer-decorators";

import http                  from "http";

//

@MolDec.Service({
	name: "http"
})
export default class HttpService extends Mol.Service {
    server:     http.Server;

    //

    created() {
        this.server = http.createServer(this.requestListener.bind(this));
    }

    //

    @MolDec.Method
    requestListener(req: http.IncomingMessage, res: http.ServerResponse) {
       
    }

    @MolDec.Method
    async listen(port: number) {
        const promise = new Promise<void>((resolve, reject) => {
            this.server.listen(port, () => {
                resolve();
            });
        });

        return await promise;
    }

    @MolDec.Action()
    public hello(): string {
		return "Hello Moleculer";
    }
}
```

MainService:
```
"use strict";

import * as Mol            from "moleculer";
import * as MolDec	     from "moleculer-decorators";

import HttpService       from "./helpers/http.service";

//

@MolDec.Service({
    name: "main",

    mixins: [HttpService]
})
export default class MainService extends Mol.Service {
    created() {
        this.logger.info("TEST", !!this.listen); // prints: "TEST false", should be "TEST true", because method listen exists in HttpService
    }
}
```

**Comment by ujwal-setlur** [comment]
+ @ColonelBundy: any thoughts?

**Comment by m1losz** [comment]
https://github.com/ColonelBundy/moleculer-decorators seems to be nonactive? should it officially forked & maintained within moleculerjs org?

**Comment by ujwal-setlur** [comment]
We just forked it to add another decorator. But yes, it might make sense to put this under the moleculerjs umbrella

**Comment by m1losz** [comment]
@icebob what do you think?

**Comment by ColonelBundy** [comment]
> https://github.com/ColonelBundy/moleculer-decorators seems to be nonactive? should it officially forked & maintained within moleculerjs org?

Life has been getting in the way and it's been difficult to dedicate any time to opensource lately so It's been a bit inactive yes but I do accept pr's

> We just forked it to add another decorator. But yes, it might make sense to put this under the moleculerjs umbrella

This does make sense and if @icebob Would like to take ownership of moleculer-decorators and continue to support it I'd be happy to transfer ownership to the moleculerjs org.

**Comment by icebob** [comment]
Hi @ColonelBundy,

I'm not a TS guy, so I will able to take ownership if there is somebody who will maintain it :)

**Comment by ujwal-setlur** [comment]
We use this heavily, so I am happy to maintain it. I am not a TS expert, but proficient enough to be dangerous. I can always @shawnmcknight for help ;)

**Comment by ujwal-setlur** [comment]
@icebob, let me know if you are ok with me maintaining it.
