### ISSUE TITLE
Trace spans have inconsistent timing

### ISSUE THREAD

**Issue by ngraef** [moleculerjs/moleculer#897]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

Trace spans from moleculer don't line up with spans from third-party modules or moleculer spans from remote services (different processes/brokers). For example, the red span in the image below should fully contain the green and purple spans under it.

<img width="372" alt="span offset" src="https://user-images.githubusercontent.com/1031317/112694294-1b363f80-8e50-11eb-8991-2eb5fa32f2d5.png">

## Expected Behavior

Span times should be as consistent as possible across all modules.

<img width="528" alt="Screen Shot 2021-03-26 at 4 50 01 PM" src="https://user-images.githubusercontent.com/1031317/112696188-5b4af180-8e53-11eb-91da-9b523073b942.png">

## Failure Information

This is caused by clock drift in moleculer's `tracing/now.js` implementation, which is used to set the `startTime` of spans. The following code and charts test this behavior and show how much a span could drift compared to `Date.now()`.

### Reproduce code snippet

```js
const now = require("./src/tracing/now");

// Output CSV for analysis
console.log(`"Time elapsed (ms)","Drift (ms)"`);

const startTime = Date.now();
console.log(`0,${now() - startTime}`);

setInterval(() => {
    const time = Date.now();
    console.log(`${time - startTime},${now() - time}`);
}, 5e3);
```

Here are charts from two sample runs:

20 minutes, 25 ms drift
![span time drift](https://user-images.githubusercontent.com/1031317/112689341-25544000-8e48-11eb-83ee-5169f766e719.png)

60 minutes, 42 ms max drift
![span time drift 2](https://user-images.githubusercontent.com/1031317/112695032-62710000-8e51-11eb-89e1-ad66cc2edbf1.png)

### Context

* Moleculer version: master
* NodeJS version: 12.21.0
* Operating System: macOS 10.15.7

**Comment by intech** [comment]
@icebob maybe we should go to [perf_hook](https://nodejs.org/api/perf_hooks.html)?

**Comment by intech** [comment]
@ngraef fast PR, thanks!

**Comment by ngraef** [comment]
@intech I made the fix while the second test was running 😁

**Comment by intech** [comment]
I also think that it is necessary to fix a similar problem in other places of the project, such as rate limiter and metrics. 🤔
