### ISSUE TITLE
List of service not working properly

### ISSUE THREAD

**Issue by f4bb1o** [moleculerjs/moleculer#900]
Hi,
I'm running Moleculer 0.14.12
I saw the documentation at the following link https://moleculer.services/docs/0.14/services.html#List-of-services.
I couldn't find any issue about my problem.
The problem is the following : 

I need to see full list of all services (Available and not available) but when I call the method broker.destroyService and then make a request to get the services list, the destroyed service isn't listed.
Can please anyone help me?
Thank you

**Comment by f4bb1o** [comment]
Thank you for the answer.
I can not find the way to stop a service (unavailable) without calling destroyService. Is there a way to do that?
I would need to stop and restart the services manually.
Thank you.

**Comment by intech** [comment]
`destroyService` only changes information in the` registry`. 
The service itself is in the same process as the broker that launches it. Therefore, it is technically impossible to restart one service.

You can stop the broker with all services and restart it. This can be done by simply stopping the process `process.exit()` and restarting it at the containerization level.
