### ISSUE TITLE
Benchmarking score seems to be much less than the numbers given in the documentation.

### ISSUE THREAD

**Issue by luongngocminh** [moleculerjs/moleculer#901]
Here are my platform info:
==============
   Linux 4.19.104-microsoft-standard x64
   Node.JS: 12.18.3
   V8: 7.8.279.23-node.39
   AMD Ryzen 7 3700X 8-Core Processor × 16
I'm using NATS docker version for my transporter 
   
I tried to benchmark moleculer using either this repo or by using the icebob/microservices-benchmark repo, the result is still the same with only average at about 700-800rps 1ms , never over 1000rps. Am I doing anything wrong, or is there a way to tweak moleculer and the NATS docker server to have better results?

**Comment by intech** [comment]
Testing in different environments will give different results.
It is impossible to unequivocally answer the question why. There can be many reasons.

I also suspect that the benchmark results published now are a little out of date. Our project is actively developing and projects of dependent packages are developing along with it, many changes are made to the code, so the results of such tests will always be subjective.
