### ISSUE TITLE
Transporter NATS can not connect "client.on is not a function".

### ISSUE THREAD

**Issue by rozhddmi** [moleculerjs/moleculer#903]
molecular:  "version": "0.14.12",
"nats": "^2.0.0",

moleculer\src\transporters\nats.js

![image](https://user-images.githubusercontent.com/1440336/113404434-731cfb00-93a8-11eb-937c-f1eb1bef3df2.png)
This throws client.on is not a function because Nats.connect return a Promise, thus need to use await .
 Or am I missing something ?

**Comment by rozhddmi** [comment]
ok it seems to be a breaking changes in NATS from version 1.14.12 -> 2.
And currently Moleculer supports 1.X.X version, probably a note in documentation or update of the nats.js to support latest version on nats package

**Comment by intech** [comment]
That's all right. NATS has been updated without backward support and it will take us a while to create a new transport for v2.

Thanks for the comment, let's add information about this to the documentation.

**Comment by AndreMaz** [comment]
Hi @rozhddmi there's a note about nats v2 in the [docs](https://moleculer.services/docs/0.14/networking.html#NATS-Transporter) and support for it is on our ToDo list.

**Comment by icebob** [comment]
@rozhddmi please search issues before open a duplicated topic.
https://github.com/moleculerjs/moleculer/issues/893
