### ISSUE TITLE
Abort or cancel a service action

### ISSUE THREAD

**Issue by palpinter** [moleculerjs/moleculer#904]
**Is your feature request related to a problem? Please describe.**

I have a long running service action on my system. (This is a bulk import function) Is there any possibilty to abort or cancel a running action? I haven't found any information about it in the documentation, or in the issue tracking list.

Thanx
Pal

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by intech** [comment]
Any call is a `promise` and there is no way to cancel it by means of the framework.
You can implement the logic using the library [p-cancelable](https://www.npmjs.com/package/p-cancelable).
I recommend using a [bree](https://www.npmjs.com/package/bree) or [bull](https://www.npmjs.com/package/bull) queue for long calls to give you more control and scalability.

**Comment by palpinter** [comment]
Thnak you very much.
