### ISSUE TITLE
Catching errors between nodes

### ISSUE THREAD

**Issue by Kamil93** [moleculerjs/moleculer#906]
Is it possible right now to catch error that was thrown in another node? For example:

We had `Node0` that contains service `abc` with `action` called `dosth`; That action inside calls `xyz.gandalf` and wait for it completes and also listen for errors to catch:

```
try {
await broker.call("xyz.gandalf", params, options);
}
catch(err) {
console.error(err);
}
```

We had also `Node1` that contains service `xyz` with `action` called `gandalf` - which always throws error like this: `throw new Error("You shall not pass");`

Does that kind of catching errors works with moleculer.js?
Does moleculer.js sends errors through transporter?

**Comment by icebob** [comment]
Yeah, the `Error` will be serialized and transferred to the caller service.

**Comment by Kamil93** [comment]
Thanks. BTW. Really awesome framework. A library that focuses mainly on micro-services was very much needed. It is very logical and well organized.

**Comment by icebob** [comment]
Thank you!
