### ISSUE TITLE
Utils type definitions not defined, preventing typescript import

### ISSUE THREAD

**Issue by srMarquinho** [moleculerjs/moleculer#909]
## Current Behavior

`import { Utils } from 'moleculer';`
`Module '"moleculer"' has no exported member 'Utils'.ts(2305)`

## Expected Behavior

`import { Utils } from 'moleculer';`
`Utils.function()` * success

## Failure Information

`Utils` type declarations seem to not be defined, falling import using typescript. However, the module is exported as follows.
https://github.com/moleculerjs/moleculer/blob/c1aa5833c9701dbdec7516e3ee88d170dbef4162/index.js#L42

### Steps to Reproduce

When typescript:
`import { Utils } from 'moleculer';`

### Context

* Moleculer version: v0.14.13
* NodeJS version: latest
* Operating System: any

**Comment by srMarquinho** [comment]
If this is reasonable I can submit a PR.

**Comment by icebob** [comment]
Yeah, please create a PR, thanks!
