### ISSUE TITLE
moleculer init project failing with error

### ISSUE THREAD

**Issue by vrock28** [moleculerjs/moleculer#914]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- I am running the latest version
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed
- I'm reporting the issue to the correct repository

## Current Behavior

I followed the installation steps mentioned on the moleculer website and used the below commands 
1)  npm i moleculer --save
2) npm i moleculer-cli -g
3) moleculer init project moleculer-demo

## Expected Behavior

I believe this should have been a straight forward step with the project being created. 

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.13
* NodeJS version: v6.11.4
* Operating System: Windows 10 Pro

### Failure Logs
```
PS C:\Users\sandg> moleculer init project moleculer-demo
C:\Users\sandg\AppData\Roaming\npm\node_modules\moleculer-cli\node_modules\update-notifier\index.js:103
        async fetchInfo() {
              ^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sandg\AppData\Roaming\npm\node_modules\moleculer-cli\bin\moleculer.js:8:24)
```

**Comment by AndreMaz** [comment]
You're using node `v6.11.4` which is EOL for a long time and if I remember correctly nodejs v6 doesn't support `async`. 
Can you try to upgrade to a more recent version of node and try it out again?

**Comment by vrock28** [comment]
@AndreMaz : Thanks for the quick update. I managed to upgrade node and gave this a try once again and it worked. Appreciate the inputs!

P.S: Is there a public slack channel where i could have a discussion around my use case with Moleculer framework ?

**Comment by intech** [comment]
@vrock28 only [discord](https://discord.gg/5yFpdvxU)
