### ISSUE TITLE
Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by mabc224** [moleculerjs/moleculer#915]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

Error appear after few min and it disconnect automatically.

## Expected Behavior

It should not disconnect and error should not appear.

### Context

* Moleculer version: 0.14.12
* NodeJS version: 12.18.0
* Operating System: ubuntu

### Failure Logs
```
[Runner] Cannot read property 'remove' of undefined TypeError: Cannot read property 'remove' of undefined                   at REPL (/d/job-1/search/node_modules/moleculer-repl/src/index.js:39:21)                             at ServiceBroker.repl (/d/job-1/search/node_modules/moleculer/src/service-broker.js:583:11)          at /d/job-omar/boomjam/boomjam-search/node_modules/moleculer/src/runner.js:461:18                                       at processTicksAndRejections (internal/process/task_queues.js:97:5)                
```

**Comment by AndreMaz** [comment]
HI @mabc224 can you provide more info and a repro example?

**Comment by mabc224** [comment]
actually, it does not show any more info. It is all I have.

![image](https://user-images.githubusercontent.com/1754418/115703201-45155000-a383-11eb-8bf8-a4dad0cebab6.png)

**Comment by AndreMaz** [comment]
Can you create a simple repro repo? Also, do you have any custom REPL commands?

**Comment by mabc224** [comment]
No, I don't use any custom configuration. All are default. 

Sample repo: https://codesandbox.io/s/moleculer-sample-forked-vmtgy

PS: Is it because, I don't have any action with name `remove` ?

**Comment by AndreMaz** [comment]
> PS: Is it because, I don't have any action with name remove ?

No, it's not. The issue comes from `moleculer-repl/src/index.js:39`

**Comment by AndreMaz** [comment]
The repo that you've provided works fine both in codesandbox and on my machine, i.e., I don't see the error
![image](https://user-images.githubusercontent.com/9802754/115710222-032be000-a36a-11eb-98f3-6e1dea1f6363.png)

**Comment by mabc224** [comment]
I am using molecular with NATS transporter. and running it in dev mode locally. 

I try to set up repo here, but don't have live credentials to use NATS . But you can get an idea by taking a look here.
https://codesandbox.io/s/moleculer-sample-forked-bev48

**Comment by AndreMaz** [comment]
What version are you using? In sandbox it says `0.14.1` but in the OP you indicated `0.14.12`. 

I've tested the code that you've provided and got the following error: ` Unable to start all services. TypeError: Cannot read property 'request' of undefined` that was caused by `disableBalancer: true` in `moleculer.config` file.

However, after upgrading to `0.14.13` the issue disappeared. Can you update your deps and try again?
