### ISSUE TITLE
distributed transaction?

### ISSUE THREAD

**Issue by JulianXin** [moleculerjs/moleculer#929]
Does moleculer integrates any solution  about  distributed transaction?

**Comment by intech** [comment]
This [example](https://github.com/moleculerjs/moleculer/blob/master/dev/saga.js) used a [saga pattern](https://microservices.io/patterns/data/saga.html), or it is best to use databases with support for distributed transactions, such as [cockroachdb](https://www.cockroachlabs.com/docs/v21.1/architecture/life-of-a-distributed-transaction.html)
