### ISSUE TITLE
makeBalancedSubscriptions is never invoked on the transporter when using Redis and etcd3 discoverers

### ISSUE THREAD

**Issue by JordanPawlett** [moleculerjs/moleculer#933]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

`makeBalancedSubscriptions` is never invoked on the transporter when a redis or etcd3 discover is used. This is due to `sendNodeInfo` never being invoked on the `transit` (for obvious reason).

## Expected Behavior

`makeBalancedSubscriptions` should be called sometime on start up.

Suggested fix: `makeBalancedSubscriptions` could be removed from the `sendNodeInfo` handler and called when `makeSubscriptions` is invoked in `afterConnect`

https://github.com/moleculerjs/moleculer/blob/9f83615bc5ee0e93335067c2cea224b896fe79c5/src/transit.js#L116

Although... At this time during `afterConnect` is called `this.broker.getLocalNodeInfo().services` would return an empty array. So balanced subscriptions would not be able to be made yet.

**Comment by icebob** [comment]
I can't move the `makeBalancedSubscriptions` to the `afterConnect` because it's called only once. If you add or remove services at runtime, the `sendNodeInfo` always called and the balanced subscription has been updated correctly. We should move it into the discoverer modules from transit.
