### ISSUE TITLE
etcd3 discoverer throws message serialization error on heartbeat

### ISSUE THREAD

**Issue by JordanPawlett** [moleculerjs/moleculer#943]
When the etcd3 discoverer tries to add a heartbeat to the etcd client it throws the bleow error.

```console.js:59 [2021-06-15T10:22:23.530Z] ERROR 78abb0a1ad1d-35/DISCOVERY: Error occured while collect etcd keys. 
GRPCInternalError: 13 INTERNAL: Request message serialization failure: util.Long.fromValue is not a function
```

It appears that the npm module `long` is having its version overridden somewhere. Updating to long 4.0.0 in my application fixed the serialization issue.

**Comment by icebob** [comment]
The `long` is a dependency of the `etcd3` pkg?
