### ISSUE TITLE
Additional log level

### ISSUE THREAD

**Issue by Kamil93** [moleculerjs/moleculer#944]
It would be very usefull to have additional "DEBUG" like log level, that will show only debug logs of end-project, without moleculer debug logs. It can be "devdebug" level or moleculer could use "sysdebug" and then "debug" can be used for that idea.

**Comment by intech** [comment]
You can now [filter the output of logs](https://moleculer.services/docs/0.14/logging.html#Filtering) for each service and middleware moleculer.
Set `debug` for your service name and `info` for `**`

**Comment by Kamil93** [comment]
Thanks :)
