### ISSUE TITLE
How it compares to NestJS?

### ISSUE THREAD

**Issue by petrovalex** [moleculerjs/moleculer#946]
What are the advantages of using moleculer, compare to NestJS microservices?
Trying to pick one of those for the project

**Comment by intech** [comment]
@petrovalex There are many other frameworks, you can only understand by comparison, try to make small projects on each of the frameworks and then draw conclusions for yourself the pros and cons for each.

The choice usually depends on your development experience, so this is a very individual choice.

**Comment by HazemKhaled** [comment]
this one maybe jelp https://github.com/jiangzhuo/nestjs-moleculer
