### ISSUE TITLE
Typescript: ThisType in ActionHandler is not work

### ISSUE THREAD

**Issue by moonrailgun** [moleculerjs/moleculer#949]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

For example code below:
```typescript
    this.parseServiceSchema({
      name: 'user',
      mixins: [DbService],
      actions: {
        login: {
          rest: 'POST /login',
          async handler(ctx: Context) {
            return {
              id: 1,
              username: 'test',
            };
          },
        },
      },
    });
```

I try to typing `this.` and not any type suggest display.

When i try to check the type of `this`, just any.

## Expected Behavior

Maybe we should change 
```typescript
type ActionHandler<T = any> = ((ctx: Context<any, any>) => Promise<T> | T) & ThisType<Service>;
```
to
```typescript
type ActionHandler<T = any> = ((this: Service, ctx: Context<any, any>) => Promise<T> | T);
```

`ThisType` looks like use in parent, not in `ActionHandler` self

https://github.com/moleculerjs/moleculer/blob/7b94f7cac722f5f82a1b5ed8906a915fa586b79f/index.d.ts#L47

**Comment by shawnmcknight** [comment]
It appears that `ThisType` is only to be used with objects and not with methods, so the typing does appear to be incorrect.  Your proposal looks correct to me -- can you create a PR?

**Comment by moonrailgun** [comment]
@shawnmcknight .Hi, thanks for your reply. I submmit a `pr` for my mind, pls take a look

**Comment by dprslt** [comment]
Hi, 

I'm not sure if this is related, but i cannot use this with typescript in the following snippet : 

```ts
   public constructor(public broker: ServiceBroker) {
        super(broker);
        this.parseServiceSchema({
            name: "greeter",
            actions:{
                hello: {
                    async handler(): Promise<string> {
                        return this.ActionHello();
                    },
                },
                welcome: {
                    
                    params: {
                        name: "string",
                    },
                    async handler(ctx: Context<{name: string}>): Promise<string> {
                        await this.actions.hello(null, {parentCtx: ctx})
                        return this.ActionWelcome(ctx.params.name);
                    },
                },
            },
        });
    }
...
}
```

This file does not compile with the following error from ts : 

```
[2021-07-02T15:00:18.889Z] ERROR citopia-theo.local-30460/BROKER: Failed to load service '/Users/dprslt/Projects/moleculer/node1/src/services/greeter.service.ts' src/services/greeter.service.ts:24:31 - error TS2684: The 'this' context of type 'ServiceActions' is not assignable to method's 'this' of type 'Service<ServiceSettingSchema>'.
  Type 'ServiceActions' is missing the following properties from type 'Service<ServiceSettingSchema>': parseServiceSchema, name, fullName, settings, and 12 more.

24                         await this.actions.hello(null, {parentCtx: ctx})
                                 ~~~~~~~~~~~~

```

I've tried with a simple export, but the problem stay the same

```ts
const ImagesService: ServiceSchema = {
    name: "files.images",
        actions:{
            ... 
        }
}
```

This error is only ts related because a `@ts-ignore` make it works.

`"version": "0.14.14"`

**Comment by moonrailgun** [comment]
@dprslt Hi, its is an interesting usage, i am not sure its a correct way to call action.

This a `this` pointer problem in js

in `hello`. `this.actions.hello` 's `this` is `actions`
and in `handler` self, `this` is `service`.

We dont like to guess whats `this` pointer

So for fix this problem. you can try:
```typescript
this.actions.hello.call(this, null, {parentCtx: ctx})
```

or

```typescript
this.broker.call('greeter.hello')
```

**Comment by dprslt** [comment]
I'll give this syntax a try. 

I've just started using the framework and this snippet was take directly from the doc. 

The section is Actions > Internal calls.

However it seems valid and working in plain js, this is why it let me think of a typing problem

**Comment by moonrailgun** [comment]
@shawnmcknight After recheck the code, this looks like have some wrapper to make sure `this` is correct. should this is a correct way? why not provide a method like `call`, for example `this.broker.localCall` ?

https://github.com/moleculerjs/moleculer/blob/55e8c7706fa8c73c58425a58a248c18fd9bd08ee/src/service.js#L135-L161

**Comment by dprslt** [comment]
IMHO, this api as it's described in the doc is super cool for the user.

It easier to write and to read than the one with the `.call`
It's enforce the name of the action and avoid dumb typo when using a string

**Comment by moonrailgun** [comment]
> IMHO, this api as it's described in the doc is super cool for the user.
> 
> It easier to write and to read than the one with the `.call`
> It's enforce the name of the action and avoid dumb typo when using a string

`call` use string style because it should transport action between multiple nodes. this a RPC call.

and i dont think its easier to write —— its should depend by typescript infer. and `this` have ambiguity in this way.

I dont know is it a correct. But i think type should be more strict, unless they dont know..

**Comment by ccampanale** [comment]
@moonrailgun Yes, the framework absolutely does intentionally map and wrap the action handlers provided on a service schema to actions within the resulting service object that can be called directly as internal calls. This is documented in the **Internal Calls** paragraph of the Metadata section of the Moleculer actions documentation: https://moleculer.services/docs/0.14/actions.html#Metadata

I believe this can be useful at times when there is no desire to broker the call. I have personally implemented this myself and it works great.

That being said there is definitely a typing complexity when it comes to Typescript. The type declaration should, in my opinion, make it clear that action handlers defined on a service schema will, at runtime, have a `ThisType` of `Service`. Ideally, the `Service` would be more generic than it is currently, as it only supports a `ServiceSettingSchema` type parameter. This is great for allowing action handlers to be aware that the service instance will have `this.settings` that adheres to the settings schema but falls short on things like methods defined in the service schema itself which would ultimately be available by `this.<methodName>`. 

In any event, I personally get around this by defining my own interfaces and providing the `ThisType` to the action handler functions.

For example:

```ts
type MyExampleServiceSettings = SomeMixinSettingsInterface & {
  someOtherSetting: string;
}

type MyExampleService = Service<MyExampleServiceSettings> & SomeMixinServiceType & {
  test(): Promise<void>;
};

const MyExampleServiceSchema: ServiceSchema<MyExampleServiceSettings> = {
  name: 'example',
  mixins: [
    SomeMixin
  ],
  settings: {
    someOtherSetting: 'test',
    someMixinSetting: process.env.MY_MIXIN_SETTING,
  },
  actions: {
    test: {
      async handler(this: MyExampleService) {
        await this.test();
      }
    }
  },
  methods: {
    async test(this: MyExampleService) {
      const res = await this.mixinProvidedMethod();
      this.logger.info(res);
    }
  }
}
```

**Comment by moonrailgun** [comment]
@ccampanale 

Follow the document, in my project, i move everything into class methods and make schema as a wrapper, so i can work around with `this` problem in object.

`Any` is bad in typescript

For example:
```typescript
interface UserService extends MixinService<UserDocument> {}
class UserService extends Service {
  constructor(broker: ServiceBroker) {
    super(broker);
    this.parseServiceSchema({
        actions: {
          test: this.test
        }
    });
  }

  test(ctx) {
    console.log(ctx)
  }
}
```

**Comment by shawnmcknight** [comment]
The original problem on this issue related to the `ActionHandler` type, although the PR was a bit broader and changed other areas where `ThisType` was being referenced.

I've been playing around a bit with this today and if we eliminate the `this: Service<S>` from the `ServiceAction` type, but leave the `ActionHandler` type alone, both the original problem and this follow-up problem appear to be resolved.

Perhaps that is the path of least resistance here.

**Comment by moonrailgun** [comment]
> The original problem on this issue related to the `ActionHandler` type, although the PR was a bit broader and changed other areas where `ThisType` was being referenced.
> 
> I've been playing around a bit with this today and if we eliminate the `this: Service<S>` from the `ServiceAction` type, but leave the `ActionHandler` type alone, both the original problem and this follow-up problem appear to be resolved.
> 
> Perhaps that is the path of least resistance here.

@shawnmcknight ,

Maybe you r right. After some thinking, we might not need `this` in Service.action. Because of we just define it and use it in schema.

**Comment by icebob** [comment]
@shawnmcknight so I should wait a fix before releasing a new version?

**Comment by shawnmcknight** [comment]
@icebob Yes I think so.

@moonrailgun Will you submit a PR for this?

**Comment by moonrailgun** [comment]
@shawnmcknight 
pls take a look for this pr, which fix this problem and i find how to append some test case for `this` ref in tsd

https://github.com/moleculerjs/moleculer/pull/958

**Comment by shawnmcknight** [comment]
@moonrailgun So I've finally gotten around to upgrading moleculer today and I'm hitting some of the type issues reported by others, particularly in my middleware definitions in my moleculer config.  The issues are similar to those reported previously in that the `this` type is not compatible due to the changes made to the `ActionHandler` type.

After a bunch of poking around, I think I came up with a solve that gets rid of these problems and your original issue.  I first reverted your changes on the `ActionHandler` type:

```ts
type ActionHandler<T = any, S = ServiceSettingSchema> = (ctx: Context<any, any>) => Promise<T> | T;
```

I then modified the `ActionSchema` type to be:
```ts
	type ActionSchema = {
		name?: string;
		rest?: RestSchema | string | string[],
		visibility?: ActionVisibility;
		params?: ActionParams;
		service?: Service;
		cache?: boolean | ActionCacheOptions;
		handler?: ActionHandler;
		tracing?: boolean | TracingActionOptions;
		bulkhead?: BulkheadOptions;
		circuitBreaker?: BrokerCircuitBreakerOptions;
		retryPolicy?: RetryPolicyOptions;
		fallback?: string | FallbackHandler;
		hooks?: ActionHooks;

		[key: string]: any;
	} & ThisType<Service>
```

In my testing of this, the type errors I was getting in my middleware definitions went away, but I'm still able to get type completion in an action handler:

![image](https://user-images.githubusercontent.com/4583869/128264927-4c69125d-842f-4677-807a-55f8ce2af9f6.png)

I'd like to propose reverting your original changes and replacing it with this change.  Can you confirm that this alteration satisfies your original problem?

**Comment by shawnmcknight** [comment]
I've pushed up a branch with my changes [here](https://github.com/moleculerjs/moleculer/compare/master...shawnmcknight:revert-950).

I had to make a few more tweaks than I originally proposed, but this seems to do the trick and the `tsd` tests are continuing to pass (once I enabled the `noImplicitThis` compiler rule, which is necessary for `ThisType` to work).

@moonrailgun Can you try things out with my branch to confirm this works for you?

**Comment by moonrailgun** [comment]
Hi, @shawnmcknight 

I checkout to your branch and have a simple test in our tsd test case(moleculer/test/typescript/tsd/ServiceActions.test-d.ts). Its looks like cannot recognize `ThisType`. How `ThisType` work?

The resource of pass testcase is make type into `any`
![image](https://user-images.githubusercontent.com/6964737/128286507-162b6efd-7a44-4413-b4a5-82a43ba5a5de.png)

**Comment by moonrailgun** [comment]
Your mind is add `noImplicitThis` in all typescript which use `moleculer` to make sure `ThisType` work?

Looks like we have not a standard tsconfig in `moleculer`. should we add one?

**Comment by moonrailgun** [comment]
FYI, a problem of this way is, we cannot use `ActionHandler` independent.

In my repo, i wrap api like below:
```typescript
regAction(name: string, handler: ActionHandler, schema?: ActionSchema)
```

**Comment by shawnmcknight** [comment]
>I checkout to your branch and have a simple test in our tsd test case(moleculer/test/typescript/tsd/ServiceActions.test-d.ts). Its looks like cannot recognize ThisType. How ThisType work?

I think you've figured this out already based on your other comment, but `noImplicitThis` must be `true` for `ThisType` to function.  In my branch I adjusted the `tsd` settings in package.json so that the test runs will have it active, but without a `tsconfig` file in the project normal intellisense will not work in vscode.

>Your mind is add noImplicitThis in all typescript which use moleculer to make sure ThisType work?

Yes, if someone needs accurate `this` typing for the handlers then they would need `noImplicitThis` on.  That's automatically activated whenever `strict: true` is set which is the default tsconfig value.

>Looks like we have not a standard tsconfig in moleculer. should we add one?

Since moleculer is a js and not a ts repo, I'm not sure its appropriate to have a project-wide tsconfig file.  I had originally generated one to set `noImplicitThis` so that the `tsd` tests passed, but then I settled on modifying the configuration in the `package.json` instead.

>FYI, a problem of this way is, we cannot use ActionHandler independent.
In my repo, i wrap api like below:
regAction(name: string, handler: ActionHandler, schema?: ActionSchema)

I'm not understanding the full context of the problem.  Can you give me some more detail?

**Comment by moonrailgun** [comment]
@shawnmcknight Hi, after a moment of think, I found you are right. Its my fault, everything work well and i broken it :( ...

I am support you to revert my changes.

And I think we should add a section in document about how to integrate `moleculer` in `typescript`.

-------------------------

> > FYI, a problem of this way is, we cannot use ActionHandler independent.
> > In my repo, i wrap api like below:
> > regAction(name: string, handler: ActionHandler, schema?: ActionSchema)
> 
> I'm not understanding the full context of the problem. Can you give me some more detail?

Just forget it, its not important.
