### ISSUE TITLE
0.14.14 in combination with nats 2.0.8 incorrectly handles "transporter": "nats://server:port" shortcut option

### ISSUE THREAD

**Issue by JMS-1** [moleculerjs/moleculer#953]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version [this is the problem]
- [x] I checked the documentation and found no answer [release notes]
- [x] I checked to make sure that this issue has not already been filed [did my best]
- [x] I'm reporting the issue to the correct repository [are quite sure]

## Current Behavior

Before migrating from 0.14.13 and nats 1.X we use the configuration setting "transporter": "nats://server:port". This is no longer working: nats 2.X tries to connect to localhost:4222 (fallback).

## Expected Behavior

nats 2.X should respect the indicated server and port

## Failure Information

Wie analysed the problem: in this case molecular passed the transporter as is as a property **url** to nats. This propery ist respected in nats 1.X but not in nats 2.X where only the **servers** property is inspected. In case of missing servers the fallback ist used.

https://github.com/moleculerjs/moleculer/blob/v0.14.14/src/transporters/nats.js#L33

### Steps to Reproduce

Just try to connect to a remote NATS using the "transporter": "nats://server:port" shortcut configuration and make sure, that no NATS is running on localhost:4222.

### Context

* Moleculer version: 0.14.14
* NodeJS version: 14
* Operating System: Ubuntu 20.10

### Work-Around

Easy but should be noted in the release note as a breaking change - since this configuration works for NATS 1.X as will in prinicple we're fine! 

Or simply change the handling of the "nats://" URL not to just set the url property but the full configuration wirh servers. In my opionion this is the reason this should be considered a bug.

```
"transporter": { "type": "NATS", "options": { "servers": ["server:port"] } } }
```

**Comment by gautaz** [comment]
Hello,

Same issue here :-).

I agree with @JMS-1 considering the current documentation on this matter:
https://moleculer.services/docs/0.14/networking.html#NATS-Transporter

Which displays examples like:
```
module.exports = {
    nodeID: "server-1",
    transporter: "nats://nats.server:4222"
};
```
