### ISSUE TITLE
About formatter in moleculer

### ISSUE THREAD

**Issue by moonrailgun** [moleculerjs/moleculer#959]
**Is your feature request related to a problem? Please describe.**

I think basic project style is too simple, why not use a standard formmatter (like [prettier](https://prettier.io/)) to unity your project style? This important for open source project

**Describe the solution you'd like**

[prettier](https://prettier.io/) or other popular code formatter

**Describe alternatives you've considered**

**Additional context**

When i try to make some contributing, i am feel troubled with code style. my global formatter always try to format everything. —— and in your document, not point out more detail for code style.

[https://moleculer.services/docs/0.14/contributing.html](https://moleculer.services/docs/0.14/contributing.html)

**Comment by icebob** [comment]
It will be added in 0.15.
