### ISSUE TITLE
Manageing inter communication

### ISSUE THREAD

**Issue by sachinda123456** [moleculerjs/moleculer#967]
Is there any que management possibility with context.object?
My concern is mostly when in a situation where huge loads of emits happens.
Is there a better way to handle it

**Comment by ccampanale** [comment]
Based on this and other issues you've opened I highly suggest spending some time familiarizing yourself with the Moleculer documentation. There is a lot of extremely useful information documented as it pertains to implementing the framework to solve various problems. Additionally, there is an entire section for tracking associated and supported modules writing for various concerns such as this. Please see the section for modules helping to tackle [Tasks, Queues, and Jobs](https://moleculer.services/modules.html#tasks).
