### ISSUE TITLE
Pino has deprecated bindings.level

### ISSUE THREAD

**Issue by savearray2** [moleculerjs/moleculer#973]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

`Moleculer v0.14.16`

Using Pino with the following options:
```
    logger: {
        type: 'Pino',
        options: {
            level: 'info'
        }
    },
```

I get the following output:
```
(node:1) [PINODEP007] Warning: bindings.level is deprecated, use options.level option instead
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) [PINODEP007] Warning: bindings.level is deprecated, use options.level option instead
(node:1) [PINODEP007] Warning: bindings.level is deprecated, use options.level option instead
(node:1) [PINODEP007] Warning: bindings.level is deprecated, use options.level option instead
(node:1) [PINODEP007] Warning: bindings.level is deprecated, use options.level option instead
```
I unfortunately haven't had the time yet to track this down in Moleculer, but it seems Pino has deprecated `bindings.level`:
https://github.com/pinojs/pino/blob/v6.13.0/lib/proto.js#L101-L104

**Comment by valeeum** [comment]
Pretty sure the following line `this.pino.child({}, { level, ...bindings });` should be `this.pino.child(bindings, { level});`.

The child function signature is as follows: `function child (bindings, options) {...}`.  Reference line 79 in https://github.com/pinojs/pino/blob/master/lib/proto.js

I discovered this problem researching another unrelated issue (i think?) where logging calls are not consistently being output to stdout originating from graphql requests via [moleculer-apollo-server](https://github.com/moleculerjs/moleculer-apollo-server).
