### ISSUE TITLE
Event handlers, destructuring & minifiers

### ISSUE THREAD

**Issue by gautaz** [moleculerjs/moleculer#976]
**Is your feature request related to a problem? Please describe.**

Currently when one wants to use the latest event handler signature, it has to be ```function(ctx)``` (see https://moleculer.services/docs/0.14/events.html#Subscribe-to-events).

Any other signature will fall back to be interpreted as ```function(payload,  sender, eventName, ctx)```.

This means:

- one cannot use argument destructuring on `ctx` with the new signature
- one cannot use a minifier as `ctx` will most of the time be renamed 

**Describe the solution you'd like**

Why not simply dropping backward compatibility?

Does the old signature provide features that cannot be implemented with the new one?

**Describe alternatives you've considered**

For the destructuring issue, the simplest workaround is to destructure in the function's body.

For the minification issue, I do not see any other workaround than removing the minifier.

**Additional context**

N/A

**Comment by icebob** [comment]
As I see, the documentation does not mention that the `context: true` event option which solve it.

```js

	events: {
		"user.created": {
			context: true,
			handler(other) {
				this.logger.info(kleur.yellow(`${this.broker.nodeID}:${this.fullName}: Event '${other.eventName}' received. Payload:`), other.params, other.meta);
			}
		}
	}
```

**Comment by icebob** [comment]
@AndreMaz please help with mentioning it in the event page of docs. Thanks in advance!

**Comment by gautaz** [comment]
@icebob Thanks, you've just saved us from a lot of hassle :-).

Do you want me to keep the issue opened until the documentation details this option?

**Comment by AndreMaz** [comment]
@icebob will do.  @gautaz  Yes, keep it open

**Comment by AndreMaz** [comment]
Fixed in https://github.com/moleculerjs/site/commit/f6b4ab01b63f08ea1b56ada9d6bcf56f9e62dd1f
