### ISSUE TITLE
Cacher should be ignored by the action handler if cacher is not connected

### ISSUE THREAD

**Issue by JordanPawlett** [moleculerjs/moleculer#978]
**Is your feature request related to a problem? Please describe.**
Currently if the cacher for a service is not in a healthy state, the service will fail to respond to action calls as it's trying to handle the action from the underlying cache associated with the broker.

This isn't ideal in a microservice world as it creates a strict dependency between the service and the cache.

If this weren't the case, it would allow the developer to write much more fault tolerant services.

**Describe the solution you'd like**
I propose a `connected` flag should be implemented by the cachers. Then the handler middleware could check the connected state of the cacher before attempting to get/set, if `connected === false` the request should be directed straight to the handler and the response should not be set in the cache.

There will be some cases where the service is strictly dependent on the underlying broker cacher. However, i believe it should be the responsibility of the developer to decide whether their service is healthy when the cacher is offline on a service by service basis.

**Comment by icebob** [comment]
Interesting suggestion. I approve of it.
