### ISSUE TITLE
Example of object-mode-streaming in documentation

### ISSUE THREAD

**Issue by JordanPawlett** [moleculerjs/moleculer#979]
It would be great if we could get an example of object-mode streaming in the documentation! 
Also, does this work with moleculer-web out of the box? i.e. will a route handler be able to handle an action that returns an object stream?

I imagine it looks a bit like the following?
```js
  function handler() {
    const stream = new Stream.Readable({
      objectMode: true,
      read() { }
    });
    
    const largeObject;
    process.nextTick(() => {
      stream.push(largeObject)
    });
    return stream;
  }
```

Would the largeObject in this case have to be split and pushed in chunks, then re-merged at the other side?

e.g. the Producer would stringify and split on comma, then the consuming would have to piece the individual chunks together?

**Comment by icebob** [comment]
There are some integration test for objectMode stream. Can it help you?
https://github.com/moleculerjs/moleculer/blob/eb47c6c81784322f026d237a39f79de444aedde5/test/integration/stream.spec.js#L362-L430

**Comment by JordanPawlett** [comment]
Thanks, i'll have a look through this!
