### ISSUE TITLE
memory (and memoryLRU) Cacher cloning issue

### ISSUE THREAD

**Issue by thib3113** [moleculerjs/moleculer#981]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

## Current Behavior

The content of the action cache can be updated by the code calling the action .

```typescript
// action A is cached in memory or memoryLRU
const numbers = ctx.call('A'); 

console.log(numbers);
// [1,2]

//update the content of numbers
console.log('get last number', numbers.pop());

// here, the call will hit the memory cache
const numbers = ctx.call('A'); 

console.log(numbers);
// [1] => 2 was poped out
```

## Expected Behavior

```typescript
// action A is cached in memory or memoryLRU
const numbers = ctx.call('A'); 

console.log(numbers);
// [1,2]

//update the content of numbers
console.log('get last number', numbers.pop());

// here, the call will hit the memory cache
const numbers = ctx.call('A'); 

console.log(numbers);
// [1,2]
```

### Steps to Reproduce

code on the `current behavior`

### Reproduce code snippet
https://codesandbox.io/s/moleculer-sample-forked-4nris?file=/index.js

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.16
* NodeJS version: 14.17.1
* Operating System: Windows 10
* moleculer nodes : only one

### Possible resolution

In my opinion, the problem come because you clone the object on GET, but not on SET .
Why not just cloning the object when storing it ? so the cache is untouched by the caller, and you don't need to clone it when you GET it ?

**Comment by icebob** [comment]
Cloning only at storing give the same issue. Because first received non-cloned cached response changes affected the other gets.
So it will be good if we clone on both set and get.
